from hl7trans import *
import compositetrans
transforms = {\
    'DLT': {\
        'range': (1, compositetrans.fieldtransformNR),
        'numeric_threshold': (2, numtransform),
        'change_computation': (3, None),
        'length_of_time_days': (4, numtransform),
},
    'SI': {\
        'value': (1, None),
},
    'VR': {\
        'first_data_code_value': (1, None),
        'last_data_code_calue': (2, None),
},
    'DLN': {\
        'drivers_license_number': (1, None),
        'issuing_state_province_country': (2, None),
        'expiration_date': (3, datetransform),
},
    'ST': {\
        'value': (1, None),
},
    'TM': {\
        'value': (1, None),
},
    'QIP': {\
        'field_name': (1, None),
        'value': (2, None),
},
    'EI': {\
        'entity_identifier': (1, None),
        'namespace_id': (2, None),
        'universal_id': (3, None),
        'universal_id_type': (4, None),
},
    'NM': {\
        'value': (1, numtransform),
},
    'TN': {\
        'value': (1, None),
},
    'VH': {\
        'start_day_range': (1, None),
        'end_day_range': (2, None),
        'start_hour_range': (3, datetransform),
        'end_hour_range': (4, datetransform),
},
    'XCN': {\
        'id_number_st': (1, None),
        'family_last_name': (2, compositetrans.fieldtransformFN),
        'given_name': (3, None),
        'middle_initial_or_name': (4, None),
        'suffix': (5, None),
        'prefix': (6, None),
        'degree': (7, None),
        'source_table': (8, None),
        'assigning_authority': (9, compositetrans.fieldtransformHD),
        'name_type_code': (10, None),
        'identifier_check_digit': (11, None),
        'code_identifying_the_check_digit_scheme_employed': (12, None),
        'identifier_type_code': (13, None),
        'assigning_facility': (14, compositetrans.fieldtransformHD),
        'name_representation_code': (15, None),
},
    'DT': {\
        'value': (1, None),
},
    'TS': {\
        'time_of_an_event': (1, None),
        'degree_of_precision': (2, None),
},
    'TX': {\
        'value': (1, None),
},
    'PPN': {\
        'id_number_nm': (1, numtransform),
        'family_last_name': (2, compositetrans.fieldtransformFN),
        'given_name': (3, None),
        'middle_initial_or_name': (4, None),
        'suffix': (5, None),
        'prefix': (6, None),
        'degree': (7, None),
        'source_table': (8, None),
        'assigning_authority': (9, compositetrans.fieldtransformHD),
        'name_type_code': (10, None),
        'identifier_check_digit': (11, None),
        'code_identifying_the_check_digit_scheme_employed': (12, None),
        'identifier_type_code': (13, None),
        'assigning_facility': (14, compositetrans.fieldtransformHD),
        'datetime_action_performed': (15, datetransform),
        'name_representation_code': (16, None),
},
    'AD': {\
        'street_address': (1, None),
        'other_designation': (2, None),
        'city': (3, None),
        'state_or_province': (4, None),
        'zip_or_postal_code': (5, None),
        'country': (6, None),
        'address_type': (7, None),
        'other_geographic_designation': (8, None),
},
    'SCV': {\
        'parameter_class': (1, None),
        'parameter_value': (2, None),
},
    'LA1': {\
        'point_of_care_is': (1, None),
        'room': (2, None),
        'bed': (3, None),
        'facility_hd': (4, compositetrans.fieldtransformHD),
        'location_status': (5, None),
        'person_location_type': (6, None),
        'building': (7, None),
        'floor': (8, None),
        'address': (9, compositetrans.fieldtransformAD),
},
    'PEN': {\
        'penalty_type': (1, None),
        'penalty_amount': (2, numtransform),
},
    'CX': {\
        'id': (1, None),
        'check_digit': (2, numtransform),
        'code_identifying_the_check_digit_scheme_employed': (3, None),
        'assigning_authority': (4, compositetrans.fieldtransformHD),
        'identifier_type_code': (5, None),
        'assigning_facility': (6, compositetrans.fieldtransformHD),
},
    'XAD': {\
        'street_address': (1, None),
        'other_designation': (2, None),
        'city': (3, None),
        'state_or_province': (4, None),
        'zip_or_postal_code': (5, None),
        'country': (6, None),
        'address_type': (7, None),
        'other_geographic_designation': (8, None),
        'countyparish_code': (9, None),
        'census_tract': (10, None),
        'address_representation_code': (11, None),
},
    'OSP': {\
        'occurrence_span_code': (1, compositetrans.fieldtransformCE),
        'occurrence_span_start_date': (2, datetransform),
        'occurrence_span_stop_date': (3, datetransform),
},
    'DLD': {\
        'discharge_location': (1, None),
        'effective_date': (2, datetransform),
},
    'DIN': {\
        'date': (1, datetransform),
        'institution_name': (2, compositetrans.fieldtransformCE),
},
    'JCC': {\
        'job_code': (1, None),
        'job_class': (2, None),
},
    'TQ': {\
        'quantity': (1, compositetrans.fieldtransformCQ),
        'interval': (2, compositetrans.fieldtransformRI),
        'duration': (3, None),
        'start_datetime': (4, datetransform),
        'end_datetime': (5, datetransform),
        'priority': (6, None),
        'condition': (7, None),
        'text': (8, None),
        'conjunction': (9, None),
        'order_sequencing': (10, compositetrans.fieldtransformOSD),
        'occurrence_duration': (11, compositetrans.fieldtransformCE),
        'total_occurences': (12, numtransform),
},
    'DTN': {\
        'day_type': (1, None),
        'number_of_days': (2, numtransform),
},
    'ID': {\
        'value': (1, None),
},
    'PT': {\
        'processing_id': (1, None),
        'processing_mode': (2, None),
},
    'CP': {\
        'price': (1, compositetrans.fieldtransformMO),
        'price_type': (2, None),
        'from_value': (3, numtransform),
        'to_value': (4, numtransform),
        'range_units': (5, compositetrans.fieldtransformCE),
        'range_type': (6, None),
},
    'MSG': {\
        'message_type': (1, None),
        'trigger_event': (2, None),
        'message_structure': (3, None),
},
    'SPS': {\
        'specimen_source_name_or_code': (1, compositetrans.fieldtransformCE),
        'additives': (2, None),
        'freetext': (3, None),
        'body_site': (4, compositetrans.fieldtransformCE),
        'site_modifier': (5, compositetrans.fieldtransformCE),
        'collection_modifier_method_code': (6, compositetrans.fieldtransformCE),
        'specimen_role': (7, compositetrans.fieldtransformCE),
},
    'MOC': {\
        'dollar_amount': (1, compositetrans.fieldtransformMO),
        'charge_code': (2, compositetrans.fieldtransformCE),
},
    'NR': {\
        'low_value': (1, numtransform),
        'high_value': (2, numtransform),
},
    'PLN': {\
        'id_number_st': (1, None),
        'type_of_id_number_is': (2, None),
        'stateother_qualifying_info': (3, None),
        'expiration_date': (4, datetransform),
},
    'TX_CHALLENGE': {\
        'challenge_information': (1, None),
        'challenge_information': (2, None),
},
    'RCD': {\
        'segment_field_name': (1, None),
        'hl7_date_type': (2, None),
        'maximum_column_width': (3, numtransform),
},
    'PI': {\
        'id_number_st': (1, None),
        'type_of_id_number_is': (2, None),
        'other_qualifying_info': (3, None),
},
    'NDL': {\
        'name': (1, compositetrans.fieldtransformCN),
        'start_datetime': (2, datetransform),
        'end_datetime': (3, datetransform),
        'point_of_care_is': (4, None),
        'room': (5, None),
        'bed': (6, None),
        'facility_hd': (7, compositetrans.fieldtransformHD),
        'location_status': (8, None),
        'person_location_type': (9, None),
        'building': (10, None),
        'floor': (11, None),
},
    'RMC': {\
        'room_type': (1, None),
        'amount_type': (2, None),
        'coverage_amount': (3, numtransform),
},
    'XON': {\
        'organization_name': (1, None),
        'organization_name_type_code': (2, None),
        'id_number_nm': (3, numtransform),
        'check_digit': (4, numtransform),
        'code_identifying_the_check_digit_scheme_employed': (5, None),
        'assigning_authority': (6, compositetrans.fieldtransformHD),
        'identifier_type_code': (7, None),
        'assigning_facility_id': (8, compositetrans.fieldtransformHD),
        'name_representation_code': (9, None),
},
    'UVC': {\
        'value_code': (1, None),
        'value_amount': (2, numtransform),
},
    'VID': {\
        'version_id': (1, None),
        'internationalization_code': (2, compositetrans.fieldtransformCE),
        'international_version_id': (3, compositetrans.fieldtransformCE),
},
    'AUI': {\
        'authorization_number': (1, None),
        'date': (2, datetransform),
        'source': (3, None),
},
    'RFR': {\
        'reference_range': (1, compositetrans.fieldtransformNR),
        'administrative_sex': (2, None),
        'age_range': (3, compositetrans.fieldtransformNR),
        'gestational_age_range': (4, compositetrans.fieldtransformNR),
        'species': (5, None),
        'racesubspecies': (6, None),
        'conditions': (7, None),
},
    'DDI': {\
        'delay_days': (1, numtransform),
        'amount': (2, numtransform),
        'number_of_days': (3, numtransform),
},
    'CQ': {\
        'quantity': (1, numtransform),
        'units': (2, compositetrans.fieldtransformCE),
},
    'PCF': {\
        'pre_certification_patient_type': (1, None),
        'pre_certification_required': (2, None),
        'pre_certification_window': (3, datetransform),
},
    'PTA': {\
        'policy_type': (1, None),
        'amount_class': (2, None),
        'amount': (3, numtransform),
},
    'XTN': {\
        '999_999_9999_x99999c_any_text': (1, None),
        'telecommunication_use_code': (2, None),
        'telecommunication_equipment_type_id': (3, None),
        'email_address': (4, None),
        'country_code': (5, numtransform),
        'areacity_code': (6, numtransform),
        'phone_number': (7, numtransform),
        'extension': (8, numtransform),
        'any_text': (9, None),
},
    'OCD': {\
        'occurrence_code': (1, None),
        'occurrence_date': (2, datetransform),
},
    'ELD': {\
        'segment_id': (1, None),
        'sequence': (2, numtransform),
        'field_position': (3, numtransform),
        'code_identifying_error': (4, compositetrans.fieldtransformCE),
},
    'PRL': {\
        'obx_3_observation_identifier_of_parent_result': (1, compositetrans.fieldtransformCE),
        'obx_4_sub_id_of_parent_result': (2, None),
        'part_of_obx_5_observation_result_from_parent': (3, None),
},
    'QSC': {\
        'segment_field_name': (1, None),
        'relational_operator': (2, None),
        'value': (3, None),
        'relational_conjunction': (4, None),
},
    'EIP': {\
        'parents_placer_order_number': (1, compositetrans.fieldtransformEI),
        'parents_filler_order_number': (2, compositetrans.fieldtransformEI),
},
    'CN': {\
        'id_number_st': (1, None),
        'family_name': (2, None),
        'given_name': (3, None),
        'middle_initial_or_name': (4, None),
        'suffix': (5, None),
        'prefix': (6, None),
        'degree': (7, None),
        'source_table': (8, None),
        'assigning_authority': (9, compositetrans.fieldtransformHD),
},
    'CE': {\
        'identifier': (1, None),
        'text': (2, None),
        'name_of_coding_system': (3, None),
        'alternate_identifier': (4, None),
        'alternate_text': (5, None),
        'name_of_alternate_coding_system': (6, None),
},
    'OSD': {\
        'sequenceresults_flag': (1, None),
        'placer_order_number_entity_identifier': (2, None),
        'placer_order_number_namespace_id': (3, None),
        'filler_order_number_entity_identifier': (4, None),
        'filler_order_number_namespace_id': (5, None),
        'sequence_condition_value': (6, None),
        'maximum_number_of_repeats': (7, numtransform),
        'placer_order_number_universal_id': (8, None),
        'placer_order_number_universal_id_type': (9, None),
        'filler_order_number_universal_id': (10, None),
        'filler_order_number_universal_id_type': (11, None),
},
    'CK': {\
        'id_number_nm': (1, numtransform),
        'check_digit': (2, numtransform),
        'code_identifying_the_check_digit_scheme_employed': (3, None),
        'assigning_authority': (4, compositetrans.fieldtransformHD),
},
    'SPD': {\
        'specialty_name': (1, None),
        'governing_board': (2, None),
        'eligible_or_certified': (3, None),
        'date_of_certification': (4, datetransform),
},
    'FN': {\
        'family_name': (1, None),
        'last_name_prefix': (2, None),
},
    'DR': {\
        'range_start_datetime': (1, datetransform),
        'range_end_datetime': (2, datetransform),
},
    'RI': {\
        'repeat_pattern': (1, None),
        'explicit_time_interval': (2, None),
},
    'HD': {\
        'namespace_id': (1, None),
        'universal_id': (2, None),
        'universal_id_type': (3, None),
},
    'LA2': {\
        'point_of_care_is': (1, None),
        'room': (2, None),
        'bed': (3, None),
        'facility_hd': (4, compositetrans.fieldtransformHD),
        'location_status': (5, None),
        'person_location_type': (6, None),
        'building': (7, None),
        'floor': (8, None),
        'street_address': (9, None),
        'other_designation': (10, None),
        'city': (11, None),
        'state_or_province': (12, None),
        'zip_or_postal_code': (13, None),
        'country': (14, None),
        'address_type': (15, None),
        'other_geographic_designation': (16, None),
},
    'PL': {\
        'point_of_care': (1, None),
        'room': (2, None),
        'bed': (3, None),
        'facility_hd': (4, compositetrans.fieldtransformHD),
        'location_status': (5, None),
        'person_location_type': (6, None),
        'building': (7, None),
        'floor': (8, None),
        'location_description': (9, None),
},
    'XPN': {\
        'family_last_name': (1, compositetrans.fieldtransformFN),
        'given_name': (2, None),
        'middle_initial_or_name': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'name_type_code': (7, None),
        'name_representation_code': (8, None),
},
    'IS': {\
        'value': (1, None),
},
    'MO': {\
        'quantity': (1, numtransform),
        'denomination': (2, None),
},
    'CCD': {\
        'when_to_charge_code': (1, None),
        'datetime': (2, datetransform),
},
    'FT': {\
        'value': (1, None),
},
    'FC': {\
        'financial_class': (1, None),
        'effective_date': (2, datetransform),
},
    'PIP': {\
        'privilege': (1, compositetrans.fieldtransformCE),
        'privilege_class': (2, compositetrans.fieldtransformCE),
        'expiration_date': (3, datetransform),
        'activation_date': (4, datetransform),
        'facility_ei': (5, compositetrans.fieldtransformEI),
},
}

