from hl7trans import *
import compositetrans
transforms = {\
    'SI': {\
        'value': (1, None),
},
    'DLN': {\
        'license_number': (1, None),
        'issuing_province_country': (2, None),
        'expiration_date': (3, datetransform),
},
    'ST': {\
        'value': (1, None),
},
    'TM': {\
        'value': (1, None),
},
    'QIP': {\
        'field_name': (1, None),
        'values': (2, compositetrans.fieldtransformQIP_VALUES),
},
    'RP': {\
        'pointer': (1, None),
        'application_id': (2, compositetrans.fieldtransformHD),
        'type_of_data': (3, None),
        'sub_type': (4, None),
},
    'EI': {\
        'entity_identifier': (1, None),
        'namespace_id': (2, None),
        'universal_id': (3, None),
        'universal_id_type': (4, None),
},
    'NM': {\
        'value': (1, numtransform),
},
    'CM_MSH': {\
        'type': (1, None),
        'event': (2, None),
},
    'TN': {\
        'number': (1, None),
},
    'OH': {\
        'office_day': (1, None),
        'office_start_time': (2, datetransform),
        'office_end_time': (3, datetransform),
        'provider_start_time': (4, datetransform),
        'provider_end_time': (5, datetransform),
},
    'VH': {\
        'start_day_range': (1, None),
        'end_day_range': (2, None),
        'start_hour_range': (3, datetransform),
        'end_hour_range': (4, datetransform),
},
    'XCN': {\
        'id_number': (1, None),
        'family_name': (2, None),
        'given_name': (3, None),
        'middle_initial_or_name': (4, None),
        'suffix': (5, None),
        'prefix': (6, None),
        'degree': (7, None),
        'source_table': (8, None),
        'assigning_authority': (9, compositetrans.fieldtransformHD),
        'name_type_code': (10, None),
        'identifier_check_digit': (11, None),
        'code_identifying_the_check_digit_scheme_employed': (12, None),
        'identifier_type_code': (13, None),
        'assigning_facility': (14, compositetrans.fieldtransformHD),
},
    'DT': {\
        'value': (1, None),
},
    'TS': {\
        'value': (1, None),
},
    'TX': {\
        'value': (1, None),
},
    'PPN': {\
        'id_number': (1, None),
        'family_name': (2, None),
        'given_name': (3, None),
        'middle_initial_or_name': (4, None),
        'suffix': (5, None),
        'prefix': (6, None),
        'degree': (7, None),
        'source_table': (8, None),
        'assigning_authority': (9, compositetrans.fieldtransformHD),
        'name_type_code': (10, None),
        'identifier_check_digit': (11, None),
        'code_identifying_check_digit_scheme_employed': (12, None),
        'identifier_type_code': (13, None),
        'assigning_facility': (14, compositetrans.fieldtransformHD),
        'datetime_action_performed': (15, datetransform),
},
    'AD': {\
        'street_address': (1, None),
        'other_designation': (2, None),
        'city': (3, None),
        'state_or_province': (4, None),
        'zip_or_postal_code': (5, None),
        'country': (6, None),
        'address_type': (7, None),
        'other_geographic_designation': (8, None),
},
    'SCV': {\
        'parameter_class': (1, None),
        'parameter_value': (2, None),
},
    'SN': {\
        'comparator': (1, None),
        'num1': (2, numtransform),
        'separatorsuffix': (3, None),
        'num2': (4, numtransform),
},
    'CX': {\
        'id': (1, None),
        'check_digit': (2, None),
        'code_identifying_the_check_digit_scheme_employed': (3, None),
        'assigning_authority': (4, compositetrans.fieldtransformHD),
        'identifier_type_code': (5, None),
        'assigning_facility': (6, compositetrans.fieldtransformHD),
},
    'XAD': {\
        'street_address': (1, None),
        'other_designation': (2, None),
        'city': (3, None),
        'state_or_province': (4, None),
        'zip_or_postal_code': (5, None),
        'country': (6, None),
        'address_type': (7, None),
        'other_geographic_designation': (8, None),
        'countryparish_code': (9, None),
        'census_tract': (10, None),
},
    'CF': {\
        'identifier': (1, None),
        'formatted_text': (2, None),
        'name_of_coding_system': (3, None),
        'alternate_identifier': (4, None),
        'alternate_formatted_text': (5, None),
        'name_of_alternate_coding_system': (6, None),
},
    'JCC': {\
        'job_code': (1, None),
        'job_class': (2, None),
},
    'TQ': {\
        'quantity': (1, compositetrans.fieldtransformCQ),
        'interval': (2, None),
        'duration': (3, None),
        'start_datetime': (4, datetransform),
        'end_datetime': (5, datetransform),
        'priority': (6, None),
        'condition': (7, None),
        'text': (8, None),
        'conjunction': (9, None),
        'order_sequencing': (10, None),
},
    'ID': {\
        'id': (1, None),
},
    'PT': {\
        'processing_type': (1, None),
        'processing_mode': (2, None),
},
    'CP': {\
        'price': (1, compositetrans.fieldtransformMO),
        'price_type': (2, None),
        'from_value': (3, numtransform),
        'to_value': (4, numtransform),
        'range_units': (5, compositetrans.fieldtransformCE),
        'range_type': (6, None),
},
    'PN': {\
        'family_name': (1, None),
        'given_name': (2, None),
        'middle_initial_or_name': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
},
    'MA': {\
        'channel_1_sample': (1, numtransform),
        'channel_2_sample': (2, numtransform),
        'channel_3_sample': (3, numtransform),
},
    'RCD': {\
        'item_number': (1, None),
        'hl7_data_type': (2, None),
        'maximum_column_width': (3, numtransform),
},
    'XON': {\
        'organization_name': (1, None),
        'organization_name_type_code': (2, None),
        'id_number': (3, numtransform),
        'check_digit': (4, numtransform),
        'code_identifying_the_check_digit': (5, None),
        'assigning_authority': (6, compositetrans.fieldtransformHD),
        'identifier_type_code': (7, None),
        'assigned_facility': (8, compositetrans.fieldtransformHD),
},
    'CM': {\
        'field1': (1, None),
        'field2': (2, None),
        'field3': (3, None),
        'field4': (4, None),
        'field5': (5, None),
        'field6': (6, None),
},
    'CD_INFO': {\
        'channel_number': (1, numtransform),
        'channel_name': (2, None),
},
    'CQ': {\
        'quantity': (1, numtransform),
        'units': (2, compositetrans.fieldtransformCE),
},
    'XTN': {\
        'number': (1, None),
        'telecommunications_use_code': (2, None),
        'telecommunications_equipment_type': (3, None),
        'email_address': (4, None),
        'country_code': (5, numtransform),
        'areacity_code': (6, numtransform),
        'phone_number': (7, numtransform),
        'extension': (8, numtransform),
        'any_text': (9, None),
},
    'QSC': {\
        'name_of_field': (1, None),
        'relational_operator': (2, None),
        'value': (3, None),
        'relational_conjunction': (4, None),
},
    'CN': {\
        'id_number': (1, None),
        'family_name': (2, None),
        'given_name': (3, None),
        'middle_initial_or_name': (4, None),
        'suffix': (5, None),
        'prefix': (6, None),
        'degree': (7, None),
        'source_table': (8, None),
        'assigning_authority': (9, compositetrans.fieldtransformHD),
},
    'CE': {\
        'identifier': (1, None),
        'text': (2, None),
        'name_of_coding_system': (3, None),
        'alternate_identifier': (4, None),
        'alternate_text': (5, None),
        'name_of_coding_system': (6, None),
},
    'CK': {\
        'id_number': (1, numtransform),
        'check_digit': (2, numtransform),
        'code_identifying_the_check_digit': (3, None),
        'assigning_authority': (4, compositetrans.fieldtransformHD),
},
    'DR': {\
        'range_start_datetime': (1, datetransform),
        'range_end_datetime': (2, datetransform),
},
    'QIP_VALUES': {\
        'value1': (1, None),
        'value2': (2, None),
        'value3': (3, None),
        'value4': (4, None),
        'value5': (5, None),
},
    'RI': {\
        'repeat_pattern': (1, None),
        'explicit_time_interval': (2, None),
},
    'HD': {\
        'namespace': (1, None),
        'universal_id': (2, None),
        'universal_id': (3, None),
},
    'PL': {\
        'point_of_care': (1, None),
        'room': (2, None),
        'bed': (3, None),
        'facility': (4, compositetrans.fieldtransformHD),
        'location_status': (5, None),
        'person_location_type': (6, None),
        'building': (7, None),
        'floor': (8, None),
        'location_description': (9, None),
},
    'XPN': {\
        'family_name': (1, None),
        'given_name': (2, None),
        'middle_initial_or_name': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'name_type_code': (7, None),
},
    'CD': {\
        'channel_identifier': (1, None),
        'channel_info': (2, compositetrans.fieldtransformCD_INFO),
        'electrode_names': (3, None),
        'channel_sensitivityunits': (4, None),
        'calibration_parameters': (5, None),
        'sampling_frequency': (6, numtransform),
        'minimummaximum_data_values': (7, None),
},
    'IS': {\
        'value': (1, None),
},
    'MO': {\
        'quantity': (1, numtransform),
        'denomination': (2, None),
},
    'FT': {\
        'value': (1, None),
},
    'FC': {\
        'financial_class': (1, None),
        'effective_date': (2, datetransform),
},
    'NA': {\
        'value1': (1, numtransform),
        'value2': (2, numtransform),
        'value3': (3, numtransform),
        'value4': (4, numtransform),
        'value5': (5, numtransform),
        'value6': (6, numtransform),
        'value7': (7, numtransform),
},
}

