from hl7trans import *
import compositetrans
transforms = {\
    'DLT': {\
        'range': (0, compositetrans.fieldtransformNR),
        'numeric_threshold': (1, numtransform),
        'change': (2, None),
        'length_of_time_days': (3, numtransform),
},
    'SI': {\
        'value': (0, None),
},
    'VR': {\
        'first_data_code_value': (0, None),
        'last_data_code_calue': (1, None),
},
    'DLN': {\
        'drivers_license_number': (0, None),
        'issuing_state_province_country': (1, None),
        'expiration_date': (2, datetransform),
},
    'ST': {\
        'value': (0, None),
},
    'TM': {\
        'value': (0, None),
},
    'QIP': {\
        'segment_field_name': (0, None),
        'value1value2value3': (1, None),
},
    'EI': {\
        'entity_identifier': (0, None),
        'namespace_id': (1, None),
        'universal_id': (2, None),
        'universal_id_type': (3, None),
},
    'NM': {\
        'value': (0, numtransform),
},
    'TN': {\
        'value': (0, None),
},
    'VH': {\
        'start_day_range': (0, None),
        'end_day_range': (1, None),
        'start_hour_range': (2, datetransform),
        'end_hour_range': (3, datetransform),
},
    'XCN': {\
        'id_number_st': (0, None),
        'family_name': (1, compositetrans.fieldtransformFN),
        'given_name': (2, None),
        'second_and_further_given_names_or_initials_thereof': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
        'name_type_code': (9, None),
        'identifier_check_digit': (10, None),
        'code_identifying_the_check_digit_scheme_employed': (11, None),
        'identifier_type_code_is': (12, None),
        'assigning_facility': (13, compositetrans.fieldtransformHD),
        'name_representation_code': (14, None),
        'name_context': (15, compositetrans.fieldtransformCE),
        'name_validity_range': (16, compositetrans.fieldtransformDR),
        'name_assembly_order': (17, None),
},
    'DT': {\
        'value': (0, None),
},
    'TS': {\
        'time_of_an_event': (0, None),
        'degree_of_precision': (1, None),
},
    'TX': {\
        'value': (0, None),
},
    'PPN': {\
        'id_number_st': (0, None),
        'family_name': (1, compositetrans.fieldtransformFN),
        'given_name': (2, None),
        'second_and_further_given_names_or_initials_thereof': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
        'name_type_code': (9, None),
        'identifier_check_digit': (10, None),
        'code_identifying_the_check_digit_scheme_employed': (11, None),
        'identifier_type_code_is': (12, None),
        'assigning_facility': (13, compositetrans.fieldtransformHD),
        'datetime_action_performed': (14, datetransform),
        'name_representation_code': (15, None),
        'name_context': (16, compositetrans.fieldtransformCE),
        'name_validity_range': (17, compositetrans.fieldtransformDR),
        'name_assembly_order': (18, None),
},
    'AD': {\
        'street_address_st': (0, None),
        'other_designation': (1, None),
        'city': (2, None),
        'state_or_province': (3, None),
        'zip_or_postal_code': (4, None),
        'country': (5, None),
        'address_type': (6, None),
        'other_geographic_designation': (7, None),
},
    'SCV': {\
        'parameter_class': (0, None),
        'parameter_value': (1, None),
},
    'SN': {\
        'comparator': (0, None),
        'num1': (1, numtransform),
        'separatorsuffix': (2, None),
        'num2': (3, numtransform),
},
    'SRT': {\
        'sort_by_field': (0, None),
        'sequencing': (1, None),
},
    'LA1': {\
        'point_of_care_is': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility_hd': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'person_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'address': (8, compositetrans.fieldtransformAD),
},
    'PEN': {\
        'penalty_type': (0, None),
        'penalty_amount': (1, numtransform),
},
    'CX': {\
        'id': (0, None),
        'check_digit': (1, numtransform),
        'code_identifying_the_check_digit_scheme_employed': (2, None),
        'assigning_authority': (3, compositetrans.fieldtransformHD),
        'identifier_type_code_id': (4, None),
        'assigning_facility': (5, compositetrans.fieldtransformHD),
        'effective_date_dt': (6, datetransform),
        'expiration_date': (7, datetransform),
},
    'XAD': {\
        'street_address_sad': (0, compositetrans.fieldtransformSAD),
        'other_designation': (1, None),
        'city': (2, None),
        'state_or_province': (3, None),
        'zip_or_postal_code': (4, None),
        'country': (5, None),
        'address_type': (6, None),
        'other_geographic_designation': (7, None),
        'countyparish_code': (8, None),
        'census_tract': (9, None),
        'address_representation_code': (10, None),
        'address_validity_range': (11, compositetrans.fieldtransformDR),
},
    'OSP': {\
        'occurrence_span_code': (0, compositetrans.fieldtransformCE),
        'occurrence_span_start_date': (1, datetransform),
        'occurrence_span_stop_date': (2, datetransform),
},
    'DLD': {\
        'discharge_location': (0, None),
        'effective_date': (1, datetransform),
},
    'DIN': {\
        'date': (0, datetransform),
        'institution_name': (1, compositetrans.fieldtransformCE),
},
    'CNE': {\
        'identifier_st': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier_st': (3, None),
        'alternate_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
        'coding_system_version_id': (6, None),
        'alternate_coding_system_version_id': (7, None),
        'original_text': (8, None),
},
    'JCC': {\
        'job_code': (0, None),
        'job_class': (1, None),
},
    'TQ': {\
        'quantity': (0, compositetrans.fieldtransformCQ),
        'interval': (1, compositetrans.fieldtransformRI),
        'duration': (2, None),
        'start_datetime': (3, datetransform),
        'end_datetime': (4, datetransform),
        'priority': (5, None),
        'condition': (6, None),
        'text_tx': (7, None),
        'conjunction_component': (8, None),
        'order_sequencing': (9, compositetrans.fieldtransformOSD),
        'occurrence_duration': (10, compositetrans.fieldtransformCE),
        'total_occurences': (11, numtransform),
},
    'DTN': {\
        'day_type': (0, None),
        'number_of_days': (1, numtransform),
},
    'ID': {\
        'value': (0, None),
},
    'PT': {\
        'processing_id': (0, None),
        'processing_mode': (1, None),
},
    'CP': {\
        'price': (0, compositetrans.fieldtransformMO),
        'price_type': (1, None),
        'from_value': (2, numtransform),
        'to_value': (3, numtransform),
        'range_units': (4, compositetrans.fieldtransformCE),
        'range_type': (5, None),
},
    'MSG': {\
        'message_type': (0, None),
        'trigger_event': (1, None),
        'message_structure': (2, None),
},
    'SPS': {\
        'specimen_source_name_or_code': (0, compositetrans.fieldtransformCE),
        'additives': (1, None),
        'freetext': (2, None),
        'body_site': (3, compositetrans.fieldtransformCE),
        'site_modifier': (4, compositetrans.fieldtransformCE),
        'collection_modifier_method_code': (5, compositetrans.fieldtransformCE),
        'specimen_role': (6, compositetrans.fieldtransformCE),
},
    'MOC': {\
        'dollar_amount': (0, compositetrans.fieldtransformMO),
        'charge_code': (1, compositetrans.fieldtransformCE),
},
    'NR': {\
        'low_value': (0, numtransform),
        'high_value': (1, numtransform),
},
    'PLN': {\
        'id_number_st': (0, None),
        'type_of_id_number_is': (1, None),
        'stateother_qualifying_info': (2, None),
        'expiration_date': (3, datetransform),
},
    'RCD': {\
        'segment_field_name': (0, None),
        'hl7_date_type': (1, None),
        'maximum_column_width': (2, numtransform),
},
    'PI': {\
        'id_number_st': (0, None),
        'type_of_id_number_is': (1, None),
        'other_qualifying_info': (2, None),
},
    'NDL': {\
        'name': (0, compositetrans.fieldtransformCN),
        'start_datetime': (1, datetransform),
        'end_datetime': (2, datetransform),
        'point_of_care_is': (3, None),
        'room': (4, None),
        'bed': (5, None),
        'facility_hd': (6, compositetrans.fieldtransformHD),
        'location_status': (7, None),
        'person_location_type': (8, None),
        'building': (9, None),
        'floor': (10, None),
},
    'RMC': {\
        'room_type': (0, None),
        'amount_type': (1, None),
        'coverage_amount': (2, numtransform),
},
    'XON': {\
        'organization_name': (0, None),
        'organization_name_type_code': (1, None),
        'id_number_nm': (2, numtransform),
        'check_digit': (3, numtransform),
        'code_identifying_the_check_digit_scheme_employed': (4, None),
        'assigning_authority': (5, compositetrans.fieldtransformHD),
        'identifier_type_code_is': (6, None),
        'assigning_facility_id': (7, compositetrans.fieldtransformHD),
        'name_representation_code': (8, None),
},
    'UVC': {\
        'value_code': (0, None),
        'value_amount': (1, numtransform),
},
    'VID': {\
        'version_id': (0, None),
        'internationalization_code': (1, compositetrans.fieldtransformCE),
        'international_version_id': (2, compositetrans.fieldtransformCE),
},
    'AUI': {\
        'authorization_number': (0, None),
        'date': (1, datetransform),
        'source': (2, None),
},
    'RFR': {\
        'reference_range': (0, compositetrans.fieldtransformNR),
        'administrative_sex': (1, None),
        'age_range': (2, compositetrans.fieldtransformNR),
        'gestational_range': (3, compositetrans.fieldtransformNR),
        'species': (4, None),
        'racesubspecies': (5, None),
        'conditions': (6, None),
},
    'DDI': {\
        'delay_days': (0, numtransform),
        'amount': (1, numtransform),
        'number_of_days': (2, numtransform),
},
    'CWE': {\
        'identifier_st': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier_st': (3, None),
        'alternate_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
        'coding_system_version_id': (6, None),
        'alternate_coding_system_version_id': (7, None),
        'original_text': (8, None),
},
    'CQ': {\
        'quantity': (0, numtransform),
        'units': (1, compositetrans.fieldtransformCE),
},
    'PCF': {\
        'pre_certification_patient_type': (0, None),
        'pre_certification_required': (1, None),
        'pre_certification_window': (2, datetransform),
},
    'PTA': {\
        'policy_type': (0, None),
        'amount_class': (1, None),
        'amount': (2, numtransform),
},
    'XTN': {\
        '999_999_9999_x99999c_any_text': (0, None),
        'telecommunication_use_code': (1, None),
        'telecommunication_equipment_type_id': (2, None),
        'email_address': (3, None),
        'country_code': (4, numtransform),
        'areacity_code': (5, numtransform),
        'phone_number': (6, numtransform),
        'extension': (7, numtransform),
        'any_text': (8, None),
},
    'OCD': {\
        'occurrence_code': (0, None),
        'occurrence_date': (1, datetransform),
},
    'ELD': {\
        'segment_id': (0, None),
        'sequence': (1, numtransform),
        'field_position': (2, numtransform),
        'code_identifying_error': (3, compositetrans.fieldtransformCE),
},
    'PRL': {\
        'obx_3_observation_identifier_of_parent_result': (0, compositetrans.fieldtransformCE),
        'obx_4_sub_id_of_parent_result': (1, None),
        'part_of_obx_5_observation_result_from_parent': (2, None),
},
    'SAD': {\
        'street_or_mailing_address': (0, None),
        'street_name': (1, None),
        'dwelling_number': (2, None),
},
    'QSC': {\
        'segment_field_name': (0, None),
        'relational_operator': (1, None),
        'value': (2, None),
        'relational_conjunction': (3, None),
},
    'EIP': {\
        'parents_placer_order_number': (0, compositetrans.fieldtransformEI),
        'parents_filler_order_number': (1, compositetrans.fieldtransformEI),
},
    'CN': {\
        'id_number_st': (0, None),
        'family_name': (1, compositetrans.fieldtransformFN),
        'given_name': (2, None),
        'second_and_further_given_names_or_initials_thereof': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
},
    'CE': {\
        'identifier_st': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier_st': (3, None),
        'alternate_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
},
    'OSD': {\
        'sequenceresults_flag': (0, None),
        'placer_order_number_entity_identifier': (1, None),
        'placer_order_number_namespace_id': (2, None),
        'filler_order_number_entity_identifier': (3, None),
        'filler_order_number_namespace_id': (4, None),
        'sequence_condition_value': (5, None),
        'maximum_number_of_repeats': (6, numtransform),
        'placer_order_number_universal_id': (7, None),
        'placer_order_number_universal_id_type': (8, None),
        'filler_order_number_universal_id': (9, None),
        'filler_order_number_universal_id_type': (10, None),
},
    'CK': {\
        'id_number_nm': (0, numtransform),
        'check_digit': (1, numtransform),
        'code_identifying_the_check_digit_scheme_employed': (2, None),
        'assigning_authority': (3, compositetrans.fieldtransformHD),
},
    'SPD': {\
        'specialty_name': (0, None),
        'governing_board': (1, None),
        'eligible_or_certified': (2, None),
        'date_of_certification': (3, datetransform),
},
    'FN': {\
        'surname': (0, None),
        'own_surname_prefix': (1, None),
        'own_surname': (2, None),
        'surname_prefix_from_partnerspouse': (3, None),
        'surname_from_partnerspouse': (4, None),
},
    'DR': {\
        'range_start_datetime': (0, datetransform),
        'range_end_datetime': (1, datetransform),
},
    'RI': {\
        'repeat_pattern': (0, None),
        'explicit_time_interval': (1, None),
},
    'HD': {\
        'namespace_id': (0, None),
        'universal_id': (1, None),
        'universal_id_type': (2, None),
},
    'LA2': {\
        'point_of_care_is': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility_hd': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'person_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'street_address_st': (8, None),
        'other_designation': (9, None),
        'city': (10, None),
        'state_or_province': (11, None),
        'zip_or_postal_code': (12, None),
        'country': (13, None),
        'address_type': (14, None),
        'other_geographic_designation': (15, None),
},
    'PL': {\
        'point_of_care': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility_hd': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'person_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'location_description': (8, None),
},
    'XPN': {\
        'family_name': (0, compositetrans.fieldtransformFN),
        'given_name': (1, None),
        'second_and_further_given_names_or_initials_thereof': (2, None),
        'suffix': (3, None),
        'prefix': (4, None),
        'degree': (5, None),
        'name_type_code': (6, None),
        'name_representation_code': (7, None),
        'name_context': (8, compositetrans.fieldtransformCE),
        'name_validity_range': (9, compositetrans.fieldtransformDR),
        'name_assembly_order': (10, None),
},
    'IS': {\
        'value': (0, None),
},
    'MO': {\
        'quantity': (0, numtransform),
        'denomination': (1, None),
},
    'CCD': {\
        'when_to_charge_code': (0, None),
        'datetime': (1, datetransform),
},
    'FT': {\
        'value': (0, None),
},
    'FC': {\
        'financial_class': (0, None),
        'effective_date_ts': (1, datetransform),
},
    'PIP': {\
        'privilege': (0, compositetrans.fieldtransformCE),
        'privilege_class': (1, compositetrans.fieldtransformCE),
        'expiration_date': (2, datetransform),
        'activation_date': (3, datetransform),
        'facility_ei': (4, compositetrans.fieldtransformEI),
},
    'NA': {\
        'value1': (0, numtransform),
        'value2': (1, numtransform),
        'value3': (2, numtransform),
        'value4': (3, numtransform),
},
}

