from hl7trans import *
import compositetrans
transforms = {\
    'DLT': {\
        'normal_range': (0, compositetrans.fieldtransformNR),
        'numeric_threshold': (1, numtransform),
        'change_computation': (2, None),
        'days_retained': (3, numtransform),
},
    'SI': {\
        'value': (0, compositetrans.fieldtransformInteger),
},
    'VR': {\
        'first_data_code_value': (0, None),
        'last_data_code_value': (1, None),
},
    'DLN': {\
        'license_number': (0, None),
        'issuing_state_province_country': (1, None),
        'expiration_date': (2, datetransform),
},
    'ST': {\
        'value': (0, None),
},
    'TM': {\
        'value': (0, None),
},
    'QIP': {\
        'segment_field_name': (0, None),
        'values': (1, None),
},
    'EI': {\
        'entity_identifier': (0, None),
        'namespace_id': (1, None),
        'universal_id': (2, None),
        'universal_id_type': (3, None),
},
    'NM': {\
        'value': (0, numtransform),
},
    'ERL': {\
        'segment_id': (0, None),
        'segment_sequence': (1, numtransform),
        'field_position': (2, numtransform),
        'field_repetition': (3, numtransform),
        'component_number': (4, numtransform),
        'sub_component_number': (5, numtransform),
},
    'VH': {\
        'start_day_range': (0, None),
        'end_day_range': (1, None),
        'start_hour_range': (2, datetransform),
        'end_hour_range': (3, datetransform),
},
    'XCN': {\
        'id_number': (0, None),
        'family_name': (1, compositetrans.fieldtransformFN),
        'given_name': (2, None),
        'second_and_further_given_names_or_initials_thereof': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
        'name_type_code': (9, None),
        'identifier_check_digit': (10, None),
        'check_digit_scheme': (11, None),
        'identifier_type_code': (12, None),
        'assigning_facility': (13, compositetrans.fieldtransformHD),
        'name_representation_code': (14, None),
        'name_context': (15, compositetrans.fieldtransformCE),
        'name_validity_range': (16, compositetrans.fieldtransformDR),
        'name_assembly_order': (17, None),
        'effective_date': (18, datetransform),
        'expiration_date': (19, datetransform),
        'professional_suffix': (20, None),
        'assigning_jurisdiction': (21, compositetrans.fieldtransformCWE),
        'assigning_agency_or_department': (22, compositetrans.fieldtransformCWE),
},
    'DT': {\
        'value': (0, None),
},
    'TS': {\
        'time': (0, compositetrans.fieldtransformDTM),
        'degree_of_precision': (1, None),
},
    'TX': {\
        'value': (0, None),
},
    'PPN': {\
        'id_number': (0, None),
        'family_name': (1, compositetrans.fieldtransformFN),
        'given_name': (2, None),
        'second_and_further_given_names_or_initials_thereof': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
        'name_type_code': (9, None),
        'identifier_check_digit': (10, None),
        'check_digit_scheme': (11, None),
        'identifier_type_code': (12, None),
        'assigning_facility': (13, compositetrans.fieldtransformHD),
        'datetime_action_performed': (14, datetransform),
        'name_representation_code': (15, None),
        'name_context': (16, compositetrans.fieldtransformCE),
        'name_validity_range': (17, compositetrans.fieldtransformDR),
        'name_assembly_order': (18, None),
        'effective_date': (19, datetransform),
        'expiration_date': (20, datetransform),
        'professional_suffix': (21, None),
        'assigning_jurisdiction': (22, compositetrans.fieldtransformCWE),
        'assigning_agency_or_department': (23, compositetrans.fieldtransformCWE),
},
    'ICD': {\
        'certification_patient_type': (0, None),
        'certification_required': (1, None),
        'datetime_certification_required': (2, datetransform),
},
    'AD': {\
        'street_address': (0, None),
        'other_designation': (1, None),
        'city': (2, None),
        'state_or_province': (3, None),
        'zip_or_postal_code': (4, None),
        'country': (5, None),
        'address_type': (6, None),
        'other_geographic_designation': (7, None),
},
    'SCV': {\
        'parameter_class': (0, compositetrans.fieldtransformCWE),
        'parameter_value': (1, None),
},
    'SN': {\
        'comparator': (0, None),
        'num1': (1, numtransform),
        'separatorsuffix': (2, None),
        'num2': (3, numtransform),
},
    'SRT': {\
        'sort_by_field': (0, None),
        'sequencing': (1, None),
},
    'LA1': {\
        'point_of_care': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'patient_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'address': (8, compositetrans.fieldtransformAD),
},
    'CX': {\
        'id_number': (0, None),
        'check_digit': (1, None),
        'check_digit_scheme': (2, None),
        'assigning_authority': (3, compositetrans.fieldtransformHD),
        'identifier_type_code': (4, None),
        'assigning_facility': (5, compositetrans.fieldtransformHD),
        'effective_date': (6, datetransform),
        'expiration_date': (7, datetransform),
        'assigning_jurisdiction': (8, compositetrans.fieldtransformCWE),
        'assigning_agency_or_department': (9, compositetrans.fieldtransformCWE),
},
    'XAD': {\
        'street_address': (0, compositetrans.fieldtransformSAD),
        'other_designation': (1, None),
        'city': (2, None),
        'state_or_province': (3, None),
        'zip_or_postal_code': (4, None),
        'country': (5, None),
        'address_type': (6, None),
        'other_geographic_designation': (7, None),
        'countyparish_code': (8, None),
        'census_tract': (9, None),
        'address_representation_code': (10, None),
        'address_validity_range': (11, compositetrans.fieldtransformDR),
        'effective_date': (12, datetransform),
        'expiration_date': (13, datetransform),
},
    'OSP': {\
        'occurrence_span_code': (0, compositetrans.fieldtransformCNE),
        'occurrence_span_start_date': (1, datetransform),
        'occurrence_span_stop_date': (2, datetransform),
},
    'DLD': {\
        'discharge_location': (0, None),
        'effective_date': (1, datetransform),
},
    'DIN': {\
        'date': (0, datetransform),
        'institution_name': (1, compositetrans.fieldtransformCE),
},
    'DTM': {\
        'value': (0, compositetrans.fieldtransformDateTime),
},
    'CNE': {\
        'identifier': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier': (3, None),
        'alternate_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
        'coding_system_version_id': (6, None),
        'alternate_coding_system_version_id': (7, None),
        'original_text': (8, None),
},
    'JCC': {\
        'job_code': (0, None),
        'job_class': (1, None),
        'job_description_text': (2, None),
},
    'TQ': {\
        'quantity': (0, compositetrans.fieldtransformCQ),
        'interval': (1, compositetrans.fieldtransformRI),
        'duration': (2, None),
        'start_datetime': (3, datetransform),
        'end_datetime': (4, datetransform),
        'priority': (5, None),
        'condition': (6, None),
        'text': (7, None),
        'conjunction': (8, None),
        'order_sequencing': (9, compositetrans.fieldtransformOSD),
        'occurrence_duration': (10, compositetrans.fieldtransformCE),
        'total_occurrences': (11, numtransform),
},
    'DTN': {\
        'day_type': (0, None),
        'number_of_days': (1, numtransform),
},
    'CNN': {\
        'id_number': (0, None),
        'family_name': (1, None),
        'given_name': (2, None),
        'second_and_further_given_names_or_initials_thereof': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority_namespace_id': (8, None),
        'assigning_authority_universal_id': (9, None),
        'assigning_authority_universal_id_type': (10, None),
},
    'ID': {\
        'value': (0, None),
},
    'PT': {\
        'processing_id': (0, None),
        'processing_mode': (1, None),
},
    'CP': {\
        'price': (0, compositetrans.fieldtransformMO),
        'price_type': (1, None),
        'from_value': (2, numtransform),
        'to_value': (3, numtransform),
        'range_units': (4, compositetrans.fieldtransformCE),
        'range_type': (5, None),
},
    'MSG': {\
        'message_code': (0, None),
        'trigger_event': (1, None),
        'message_structure': (2, None),
},
    'SPS': {\
        'specimen_source_name_or_code': (0, compositetrans.fieldtransformCWE),
        'additives': (1, compositetrans.fieldtransformCWE),
        'specimen_collection_method': (2, None),
        'body_site': (3, compositetrans.fieldtransformCWE),
        'site_modifier': (4, compositetrans.fieldtransformCWE),
        'collection_method_modifier_code': (5, compositetrans.fieldtransformCWE),
        'specimen_role': (6, compositetrans.fieldtransformCWE),
},
    'MOC': {\
        'monetary_amount': (0, compositetrans.fieldtransformMO),
        'charge_code': (1, compositetrans.fieldtransformCE),
},
    'NR': {\
        'low_value': (0, numtransform),
        'high_value': (1, numtransform),
},
    'PLN': {\
        'id_number': (0, None),
        'type_of_id_number': (1, None),
        'stateother_qualifying_information': (2, None),
        'expiration_date': (3, datetransform),
},
    'RCD': {\
        'segment_field_name': (0, None),
        'hl7_data_type': (1, None),
        'maximum_column_width': (2, numtransform),
},
    'NDL': {\
        'name': (0, compositetrans.fieldtransformCNN),
        'start_datetime': (1, datetransform),
        'end_datetime': (2, datetransform),
        'point_of_care': (3, None),
        'room': (4, None),
        'bed': (5, None),
        'facility': (6, compositetrans.fieldtransformHD),
        'location_status': (7, None),
        'patient_location_type': (8, None),
        'building': (9, None),
        'floor': (10, None),
},
    'RMC': {\
        'room_type': (0, None),
        'amount_type': (1, None),
        'coverage_amount': (2, numtransform),
        'money_or_percentage': (3, compositetrans.fieldtransformMOP),
},
    'XON': {\
        'organization_name': (0, None),
        'organization_name_type_code': (1, None),
        'id_number': (2, numtransform),
        'check_digit': (3, numtransform),
        'check_digit_scheme': (4, None),
        'assigning_authority': (5, compositetrans.fieldtransformHD),
        'identifier_type_code': (6, None),
        'assigning_facility': (7, compositetrans.fieldtransformHD),
        'name_representation_code': (8, None),
        'organization_identifier': (9, None),
},
    'RPT': {\
        'repeat_pattern_code': (0, compositetrans.fieldtransformCWE),
        'calendar_alignment': (1, None),
        'phase_range_begin_value': (2, numtransform),
        'phase_range_end_value': (3, numtransform),
        'period_quantity': (4, numtransform),
        'period_units': (5, None),
        'institution_specified_time': (6, None),
        'event': (7, None),
        'event_offset_quantity': (8, numtransform),
        'event_offset_units': (9, None),
        'general_timing_specification': (10, compositetrans.fieldtransformGTS),
},
    'UVC': {\
        'value_code': (0, compositetrans.fieldtransformCNE),
        'value_amount': (1, compositetrans.fieldtransformMO),
},
    'MOP': {\
        'money_or_percentage_indicator': (0, None),
        'money_or_percentage_quantity': (1, numtransform),
        'currency_denomination': (2, None),
},
    'VID': {\
        'version_id': (0, None),
        'internationalization_code': (1, compositetrans.fieldtransformCE),
        'international_version_id': (2, compositetrans.fieldtransformCE),
},
    'AUI': {\
        'authorization_number': (0, None),
        'date': (1, datetransform),
        'source': (2, None),
},
    'RFR': {\
        'numeric_range': (0, compositetrans.fieldtransformNR),
        'administrative_sex': (1, None),
        'age_range': (2, compositetrans.fieldtransformNR),
        'gestational_age_range': (3, compositetrans.fieldtransformNR),
        'species': (4, None),
        'racesubspecies': (5, None),
        'conditions': (6, None),
},
    'DDI': {\
        'delay_days': (0, numtransform),
        'monetary_amount': (1, compositetrans.fieldtransformMO),
        'number_of_days': (2, numtransform),
},
    'CWE': {\
        'identifier': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier': (3, None),
        'alternate_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
        'coding_system_version_id': (6, None),
        'alternate_coding_system_version_id': (7, None),
        'original_text': (8, None),
},
    'CQ': {\
        'quantity': (0, numtransform),
        'units': (1, compositetrans.fieldtransformCE),
},
    'PTA': {\
        'policy_type': (0, None),
        'amount_class': (1, None),
        'money_or_percentage_quantity': (2, numtransform),
        'money_or_percentage': (3, compositetrans.fieldtransformMOP),
},
    'XTN': {\
        'telephone_number': (0, None),
        'telecommunication_use_code': (1, None),
        'telecommunication_equipment_type': (2, None),
        'email_address': (3, None),
        'country_code': (4, numtransform),
        'areacity_code': (5, numtransform),
        'local_number': (6, numtransform),
        'extension': (7, numtransform),
        'any_text': (8, None),
        'extension_prefix': (9, None),
        'speed_dial_code': (10, None),
        'unformatted_telephone_number': (11, None),
},
    'OCD': {\
        'occurrence_code': (0, compositetrans.fieldtransformCNE),
        'occurrence_date': (1, datetransform),
},
    'ELD': {\
        'segment_id': (0, None),
        'segment_sequence': (1, numtransform),
        'field_position': (2, numtransform),
        'code_identifying_error': (3, compositetrans.fieldtransformCE),
},
    'GTS': {\
        'value': (0, None),
},
    'PRL': {\
        'parent_observation_identifier': (0, compositetrans.fieldtransformCE),
        'parent_observation_sub_identifier': (1, None),
        'parent_observation_value_descriptor': (2, None),
},
    'SAD': {\
        'street_or_mailing_address': (0, None),
        'street_name': (1, None),
        'dwelling_number': (2, None),
},
    'QSC': {\
        'segment_field_name': (0, None),
        'relational_operator': (1, None),
        'value': (2, None),
        'relational_conjunction': (3, None),
},
    'EIP': {\
        'placer_assigned_identifier': (0, compositetrans.fieldtransformEI),
        'filler_assigned_identifier': (1, compositetrans.fieldtransformEI),
},
    'CE': {\
        'identifier': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier': (3, None),
        'alternate_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
},
    'OSD': {\
        'sequenceresults_flag': (0, None),
        'placer_order_number_entity_identifier': (1, None),
        'placer_order_number_namespace_id': (2, None),
        'filler_order_number_entity_identifier': (3, None),
        'filler_order_number_namespace_id': (4, None),
        'sequence_condition_value': (5, None),
        'maximum_number_of_repeats': (6, numtransform),
        'placer_order_number_universal_id': (7, None),
        'placer_order_number_universal_id_type': (8, None),
        'filler_order_number_universal_id': (9, None),
        'filler_order_number_universal_id_type': (10, None),
},
    'SPD': {\
        'specialty_name': (0, None),
        'governing_board': (1, None),
        'eligible_or_certified': (2, None),
        'date_of_certification': (3, datetransform),
},
    'FN': {\
        'surname': (0, None),
        'own_surname_prefix': (1, None),
        'own_surname': (2, None),
        'surname_prefix_from_partnerspouse': (3, None),
        'surname_from_partnerspouse': (4, None),
},
    'DR': {\
        'range_start_datetime': (0, datetransform),
        'range_end_datetime': (1, datetransform),
},
    'RI': {\
        'repeat_pattern': (0, None),
        'explicit_time_interval': (1, None),
},
    'HD': {\
        'namespace_id': (0, None),
        'universal_id': (1, None),
        'universal_id_type': (2, None),
},
    'LA2': {\
        'point_of_care': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'patient_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'street_address': (8, None),
        'other_designation': (9, None),
        'city': (10, None),
        'state_or_province': (11, None),
        'zip_or_postal_code': (12, None),
        'country': (13, None),
        'address_type': (14, None),
        'other_geographic_designation': (15, None),
},
    'PL': {\
        'point_of_care': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'person_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'location_description': (8, None),
        'comprehensive_location_identifier': (9, compositetrans.fieldtransformEI),
        'assigning_authority_for_location': (10, compositetrans.fieldtransformHD),
},
    'XPN': {\
        'family_name': (0, compositetrans.fieldtransformFN),
        'given_name': (1, None),
        'second_and_further_given_names_or_initials_thereof': (2, None),
        'suffix': (3, None),
        'prefix': (4, None),
        'degree': (5, None),
        'name_type_code': (6, None),
        'name_representation_code': (7, None),
        'name_context': (8, compositetrans.fieldtransformCE),
        'name_validity_range': (9, compositetrans.fieldtransformDR),
        'name_assembly_order': (10, None),
        'effective_date': (11, datetransform),
        'expiration_date': (12, datetransform),
        'professional_suffix': (13, None),
},
    'IS': {\
        'value': (0, None),
},
    'MO': {\
        'quantity': (0, numtransform),
        'denomination': (1, None),
},
    'CCD': {\
        'invocation_event': (0, None),
        'datetime': (1, datetransform),
},
    'FT': {\
        'value': (0, None),
},
    'FC': {\
        'financial_class_code': (0, None),
        'effective_date': (1, datetransform),
},
    'PIP': {\
        'privilege': (0, compositetrans.fieldtransformCE),
        'privilege_class': (1, compositetrans.fieldtransformCE),
        'expiration_date': (2, datetransform),
        'activation_date': (3, datetransform),
        'facility': (4, compositetrans.fieldtransformEI),
},
    'ED': {\
        'source_application': (0, compositetrans.fieldtransformHD),
        'type_of_data': (1, None),
        'data_subtype': (2, None),
        'encoding': (3, None),
        'data': (4, None),
},
    'NA': {\
        'value1': (0, numtransform),
        'value2': (1, numtransform),
        'value3': (2, numtransform),
        'value4': (3, numtransform),
},
}

