from hl7trans import *
import compositetrans
transforms = {\
    'SI': {\
        'value': (0, None),
},
    'DLN': {\
        'license_number': (0, None),
        'issuing_province_country': (1, None),
        'expiration_date': (2, datetransform),
},
    'ST': {\
        'value': (0, None),
},
    'TM': {\
        'value': (0, None),
},
    'QIP': {\
        'field_name': (0, None),
        'values': (1, compositetrans.fieldtransformQIP_VALUES),
},
    'RP': {\
        'pointer': (0, None),
        'application_id': (1, compositetrans.fieldtransformHD),
        'type_of_data': (2, None),
        'sub_type': (3, None),
},
    'EI': {\
        'entity_identifier': (0, None),
        'namespace_id': (1, None),
        'universal_id': (2, None),
        'universal_id_type': (3, None),
},
    'NM': {\
        'value': (0, numtransform),
},
    'CM_MSH': {\
        'type': (0, None),
        'event': (1, None),
},
    'TN': {\
        'number': (0, None),
},
    'OH': {\
        'office_day': (0, None),
        'office_start_time': (1, datetransform),
        'office_end_time': (2, datetransform),
        'provider_start_time': (3, datetransform),
        'provider_end_time': (4, datetransform),
},
    'VH': {\
        'start_day_range': (0, None),
        'end_day_range': (1, None),
        'start_hour_range': (2, datetransform),
        'end_hour_range': (3, datetransform),
},
    'XCN': {\
        'id_number': (0, None),
        'family_name': (1, None),
        'given_name': (2, None),
        'middle_initial_or_name': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
        'name_type_code': (9, None),
        'identifier_check_digit': (10, None),
        'code_identifying_the_check_digit_scheme_employed': (11, None),
        'identifier_type_code': (12, None),
        'assigning_facility': (13, compositetrans.fieldtransformHD),
},
    'DT': {\
        'value': (0, None),
},
    'TS': {\
        'value': (0, None),
},
    'TX': {\
        'value': (0, None),
},
    'PPN': {\
        'id_number': (0, None),
        'family_name': (1, None),
        'given_name': (2, None),
        'middle_initial_or_name': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
        'name_type_code': (9, None),
        'identifier_check_digit': (10, None),
        'code_identifying_check_digit_scheme_employed': (11, None),
        'identifier_type_code': (12, None),
        'assigning_facility': (13, compositetrans.fieldtransformHD),
        'datetime_action_performed': (14, datetransform),
},
    'AD': {\
        'street_address': (0, None),
        'other_designation': (1, None),
        'city': (2, None),
        'state_or_province': (3, None),
        'zip_or_postal_code': (4, None),
        'country': (5, None),
        'address_type': (6, None),
        'other_geographic_designation': (7, None),
},
    'SCV': {\
        'parameter_class': (0, None),
        'parameter_value': (1, None),
},
    'SN': {\
        'comparator': (0, None),
        'num1': (1, numtransform),
        'separatorsuffix': (2, None),
        'num2': (3, numtransform),
},
    'CX': {\
        'id': (0, None),
        'check_digit': (1, None),
        'code_identifying_the_check_digit_scheme_employed': (2, None),
        'assigning_authority': (3, compositetrans.fieldtransformHD),
        'identifier_type_code': (4, None),
        'assigning_facility': (5, compositetrans.fieldtransformHD),
},
    'XAD': {\
        'street_address': (0, None),
        'other_designation': (1, None),
        'city': (2, None),
        'state_or_province': (3, None),
        'zip_or_postal_code': (4, None),
        'country': (5, None),
        'address_type': (6, None),
        'other_geographic_designation': (7, None),
        'countryparish_code': (8, None),
        'census_tract': (9, None),
},
    'CF': {\
        'identifier': (0, None),
        'formatted_text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier': (3, None),
        'alternate_formatted_text': (4, None),
        'name_of_alternate_coding_system': (5, None),
},
    'JCC': {\
        'job_code': (0, None),
        'job_class': (1, None),
},
    'TQ': {\
        'quantity': (0, compositetrans.fieldtransformCQ),
        'interval': (1, None),
        'duration': (2, None),
        'start_datetime': (3, datetransform),
        'end_datetime': (4, datetransform),
        'priority': (5, None),
        'condition': (6, None),
        'text': (7, None),
        'conjunction': (8, None),
        'order_sequencing': (9, None),
},
    'ID': {\
        'id': (0, None),
},
    'PT': {\
        'processing_type': (0, None),
        'processing_mode': (1, None),
},
    'CP': {\
        'price': (0, compositetrans.fieldtransformMO),
        'price_type': (1, None),
        'from_value': (2, numtransform),
        'to_value': (3, numtransform),
        'range_units': (4, compositetrans.fieldtransformCE),
        'range_type': (5, None),
},
    'PN': {\
        'family_name': (0, None),
        'given_name': (1, None),
        'middle_initial_or_name': (2, None),
        'suffix': (3, None),
        'prefix': (4, None),
        'degree': (5, None),
},
    'MA': {\
        'channel_1_sample': (0, numtransform),
        'channel_2_sample': (1, numtransform),
        'channel_3_sample': (2, numtransform),
},
    'RCD': {\
        'item_number': (0, None),
        'hl7_data_type': (1, None),
        'maximum_column_width': (2, numtransform),
},
    'XON': {\
        'organization_name': (0, None),
        'organization_name_type_code': (1, None),
        'id_number': (2, numtransform),
        'check_digit': (3, numtransform),
        'code_identifying_the_check_digit': (4, None),
        'assigning_authority': (5, compositetrans.fieldtransformHD),
        'identifier_type_code': (6, None),
        'assigned_facility': (7, compositetrans.fieldtransformHD),
},
    'CM': {\
        'field1': (0, None),
        'field2': (1, None),
        'field3': (2, None),
        'field4': (3, None),
        'field5': (4, None),
        'field6': (5, None),
},
    'CD_INFO': {\
        'channel_number': (0, numtransform),
        'channel_name': (1, None),
},
    'CQ': {\
        'quantity': (0, numtransform),
        'units': (1, compositetrans.fieldtransformCE),
},
    'XTN': {\
        'number': (0, None),
        'telecommunications_use_code': (1, None),
        'telecommunications_equipment_type': (2, None),
        'email_address': (3, None),
        'country_code': (4, numtransform),
        'areacity_code': (5, numtransform),
        'phone_number': (6, numtransform),
        'extension': (7, numtransform),
        'any_text': (8, None),
},
    'QSC': {\
        'name_of_field': (0, None),
        'relational_operator': (1, None),
        'value': (2, None),
        'relational_conjunction': (3, None),
},
    'CN': {\
        'id_number': (0, None),
        'family_name': (1, None),
        'given_name': (2, None),
        'middle_initial_or_name': (3, None),
        'suffix': (4, None),
        'prefix': (5, None),
        'degree': (6, None),
        'source_table': (7, None),
        'assigning_authority': (8, compositetrans.fieldtransformHD),
},
    'CE': {\
        'identifier': (0, None),
        'text': (1, None),
        'name_of_coding_system': (2, None),
        'alternate_identifier': (3, None),
        'alternate_text': (4, None),
        'name_of_coding_system': (5, None),
},
    'CK': {\
        'id_number': (0, numtransform),
        'check_digit': (1, numtransform),
        'code_identifying_the_check_digit': (2, None),
        'assigning_authority': (3, compositetrans.fieldtransformHD),
},
    'DR': {\
        'range_start_datetime': (0, datetransform),
        'range_end_datetime': (1, datetransform),
},
    'QIP_VALUES': {\
        'value1': (0, None),
        'value2': (1, None),
        'value3': (2, None),
        'value4': (3, None),
        'value5': (4, None),
},
    'RI': {\
        'repeat_pattern': (0, None),
        'explicit_time_interval': (1, None),
},
    'HD': {\
        'namespace': (0, None),
        'universal_id': (1, None),
        'universal_id': (2, None),
},
    'PL': {\
        'point_of_care': (0, None),
        'room': (1, None),
        'bed': (2, None),
        'facility': (3, compositetrans.fieldtransformHD),
        'location_status': (4, None),
        'person_location_type': (5, None),
        'building': (6, None),
        'floor': (7, None),
        'location_description': (8, None),
},
    'XPN': {\
        'family_name': (0, None),
        'given_name': (1, None),
        'middle_initial_or_name': (2, None),
        'suffix': (3, None),
        'prefix': (4, None),
        'degree': (5, None),
        'name_type_code': (6, None),
},
    'CD': {\
        'channel_identifier': (0, None),
        'channel_info': (1, compositetrans.fieldtransformCD_INFO),
        'electrode_names': (2, None),
        'channel_sensitivityunits': (3, None),
        'calibration_parameters': (4, None),
        'sampling_frequency': (5, numtransform),
        'minimummaximum_data_values': (6, None),
},
    'IS': {\
        'value': (0, None),
},
    'MO': {\
        'quantity': (0, numtransform),
        'denomination': (1, None),
},
    'FT': {\
        'value': (0, None),
},
    'FC': {\
        'financial_class': (0, None),
        'effective_date': (1, datetransform),
},
    'NA': {\
        'value1': (0, numtransform),
        'value2': (1, numtransform),
        'value3': (2, numtransform),
        'value4': (3, numtransform),
        'value5': (4, numtransform),
        'value6': (5, numtransform),
        'value7': (6, numtransform),
},
}

