from hl7util import *
transforms = {\
    'EQU': {\
        'equipment_instance_identifier': (1, None),
        'event_datetime': (2, datetransform),
        'equipment_state': (3, None),
        'localremote_control_state': (4, None),
        'alert_level': (5, None),
},
    'CTD': {\
        'contact_role': (1, None),
        'contact_name': (2, None),
        'contact_address': (3, None),
        'contact_location': (4, None),
        'contact_communication_information': (5, None),
        'preferred_method_of_contact': (6, None),
        'contact_identifiers': (7, None),
},
    'AIL': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'location_resource_id': (3, None),
        'location_type': (4, None),
        'location_group': (5, None),
        'start_datetime': (6, datetransform),
        'start_datetime_offset': (7, None),
        'start_datetime_offset_units': (8, None),
        'duration': (9, None),
        'duration_units': (10, None),
        'allow_substitution_code': (11, None),
        'filler_status_code': (12, None),
},
    'RDF': {\
        'number_of_columns_per_row': (1, None),
        'column_description': (2, None),
},
    'CSS': {\
        'study_scheduled_time_point': (1, None),
        'study_scheduled_patient_time_point': (2, datetransform),
        'study_quality_control_codes': (3, None),
},
    'PSH': {\
        'report_type': (1, None),
        'report_form_identifier': (2, None),
        'report_date': (3, datetransform),
        'report_interval_start_date': (4, datetransform),
        'report_interval_end_date': (5, datetransform),
        'quantity_manufactured': (6, None),
        'quantity_distributed': (7, None),
        'quantity_distributed_method': (8, None),
        'quantity_distributed_comment': (9, None),
        'quantity_in_use': (10, None),
        'quantity_in_use_method': (11, None),
        'quantity_in_use_comment': (12, None),
        'number_of_product_experience_reports_filed_by_facility': (13, None),
        'number_of_product_experience_reports_filed_by_distributor': (14, None),
},
    'QPD': {\
        'message_query_name': (1, None),
        'query_tag': (2, None),
        'user_parameters_in_successive_fields': (3, None),
},
    'GT1': {\
        'set_id': (1, None),
        'guarantor_number': (2, None),
        'guarantor_name': (3, None),
        'guarantor_spouse_name': (4, None),
        'guarantor_address': (5, None),
        'guarantor_ph_num_home': (6, None),
        'guarantor_ph_num_business': (7, None),
        'guarantor_datetime_of_birth': (8, datetransform),
        'guarantor_administrative_sex': (9, None),
        'guarantor_type': (10, None),
        'guarantor_relationship': (11, None),
        'guarantor_ssn': (12, None),
        'guarantor_date_begin': (13, datetransform),
        'guarantor_date_end': (14, datetransform),
        'guarantor_priority': (15, None),
        'guarantor_employer_name': (16, None),
        'guarantor_employer_address': (17, None),
        'guarantor_employer_phone_number': (18, None),
        'guarantor_employee_id_number': (19, None),
        'guarantor_employment_status': (20, None),
        'guarantor_organization_name': (21, None),
        'guarantor_billing_hold_flag': (22, None),
        'guarantor_credit_rating_code': (23, None),
        'guarantor_death_date_and_time': (24, datetransform),
        'guarantor_death_flag': (25, None),
        'guarantor_charge_adjustment_code': (26, None),
        'guarantor_household_annual_income': (27, None),
        'guarantor_household_size': (28, None),
        'guarantor_employer_id_number': (29, None),
        'guarantor_marital_status_code': (30, None),
        'guarantor_hire_effective_date': (31, datetransform),
        'employment_stop_date': (32, datetransform),
        'living_dependency': (33, None),
        'ambulatory_status': (34, None),
        'citizenship': (35, None),
        'primary_language': (36, None),
        'living_arrangement': (37, None),
        'publicity_code': (38, None),
        'protection_indicator': (39, None),
        'student_indicator': (40, None),
        'religion': (41, None),
        'mothers_maiden_name': (42, None),
        'nationality': (43, None),
        'ethnic_group': (44, None),
        'contact_persons_name': (45, None),
        'contact_persons_telephone_number': (46, None),
        'contact_reason': (47, None),
        'contact_relationship': (48, None),
        'job_title': (49, None),
        'job_codeclass': (50, None),
        'guarantor_employers_organization_name': (51, None),
        'handicap': (52, None),
        'job_status': (53, None),
        'guarantor_financial_class': (54, None),
        'guarantor_race': (55, None),
},
    'FHS': {\
        'file_field_separator': (1, None),
        'file_encoding_characters': (2, None),
        'file_sending_application': (3, None),
        'file_sending_facility': (4, None),
        'file_receiving_application': (5, None),
        'file_receiving_facility': (6, None),
        'file_creation_datetime': (7, datetransform),
        'file_security': (8, None),
        'file_nameid': (9, None),
        'file_header_comment': (10, None),
        'file_control_id': (11, None),
        'reference_file_control_id': (12, None),
},
    'PV2': {\
        'prior_pending_location': (1, None),
        'accommodation_code': (2, None),
        'admit_reason': (3, None),
        'transfer_reason': (4, None),
        'patient_valuables': (5, None),
        'patient_valuables_location': (6, None),
        'visit_user_code': (7, None),
        'expected_admit_datetime': (8, datetransform),
        'expected_discharge_datetime': (9, datetransform),
        'estimated_length_of_inpatient_stay': (10, None),
        'actual_length_of_inpatient_stay': (11, None),
        'visit_description': (12, None),
        'referral_source_code': (13, None),
        'previous_service_date': (14, datetransform),
        'employment_illness_related_indicator': (15, None),
        'purge_status_code': (16, None),
        'purge_status_date': (17, datetransform),
        'special_program_code': (18, None),
        'retention_indicator': (19, None),
        'expected_number_of_insurance_plans': (20, None),
        'visit_publicity_code': (21, None),
        'visit_protection_indicator': (22, None),
        'clinic_organization_name': (23, None),
        'patient_status_code': (24, None),
        'visit_priority_code': (25, None),
        'previous_treatment_date': (26, datetransform),
        'expected_discharge_disposition': (27, None),
        'signature_on_file_date': (28, datetransform),
        'first_similar_illness_date': (29, datetransform),
        'patient_charge_adjustment_code': (30, None),
        'recurring_service_code': (31, None),
        'billing_media_code': (32, None),
        'expected_surgery_date_and_time': (33, datetransform),
        'military_partnership_code': (34, None),
        'military_non_availability_code': (35, None),
        'newborn_baby_indicator': (36, None),
        'baby_detained_indicator': (37, None),
        'mode_of_arrival_code': (38, None),
        'recreational_drug_use_code': (39, None),
        'admission_level_of_care_code': (40, None),
        'precaution_code': (41, None),
        'patient_condition_code': (42, None),
        'living_will_code': (43, None),
        'organ_donor_code': (44, None),
        'advance_directive_code': (45, None),
        'patient_status_effective_date': (46, datetransform),
        'expected_loa_return_datetime': (47, datetransform),
},
    'OBX': {\
        'set_id': (1, None),
        'value_type': (2, None),
        'observation_identifier': (3, None),
        'observation_sub_id': (4, None),
        'observation_value': (5, None),
        'units': (6, None),
        'references_range': (7, None),
        'abnormal_flags': (8, None),
        'probability': (9, None),
        'nature_of_abnormal_test': (10, None),
        'observation_result_status': (11, None),
        'date_last_observation_normal_value': (12, datetransform),
        'user_defined_access_checks': (13, None),
        'datetime_of_the_observation': (14, datetransform),
        'producers_id': (15, None),
        'responsible_observer': (16, None),
        'observation_method': (17, None),
        'equipment_instance_identifier': (18, None),
        'datetime_of_the_analysis': (19, datetransform),
},
    'DRG': {\
        'diagnostic_related_group': (1, None),
        'drg_assigned_datetime': (2, datetransform),
        'drg_approval_indicator': (3, None),
        'drg_grouper_review_code': (4, None),
        'outlier_type': (5, None),
        'outlier_days': (6, None),
        'outlier_cost': (7, None),
        'drg_payor': (8, None),
        'outlier_reimbursement': (9, None),
        'confidential_indicator': (10, None),
        'drg_transfer_type': (11, None),
},
    'QRF': {\
        'where_subject_filter': (1, None),
        'when_data_start_datetime': (2, datetransform),
        'when_data_end_datetime': (3, datetransform),
        'what_user_qualifier': (4, None),
        'other_qry_subject_filter': (5, None),
        'which_datetime_qualifier': (6, None),
        'which_datetime_status_qualifier': (7, None),
        'datetime_selection_qualifier': (8, None),
        'when_quantitytiming_qualifier': (9, None),
        'search_confidence_threshold': (10, None),
},
    'MFA': {\
        'record_level_event_code': (1, None),
        'mfn_control_id': (2, None),
        'event_completion_datetime': (3, datetransform),
        'mfn_record_level_error_return': (4, None),
        'primary_key_value': (5, None),
        'primary_key_value_type': (6, None),
},
    'OM5': {\
        'sequence_number_test_observation_master_file': (1, None),
        'testobservations_included_within_an_ordered_test_battery': (2, None),
        'observation_id_suffixes': (3, None),
},
    'DSC': {\
        'continuation_pointer': (1, None),
        'continuation_style': (2, None),
},
    'PID': {\
        'set_id': (1, None),
        'patient_id': (2, None),
        'patient_identifier_list': (3, None),
        'alternate_patient_id': (4, None),
        'patient_name': (5, None),
        'mothers_maiden_name': (6, None),
        'datetime_of_birth': (7, datetransform),
        'administrative_sex': (8, None),
        'patient_alias': (9, None),
        'race': (10, None),
        'patient_address': (11, None),
        'county_code': (12, None),
        'phone_number_home': (13, None),
        'phone_number_business': (14, None),
        'primary_language': (15, None),
        'marital_status': (16, None),
        'religion': (17, None),
        'patient_account_number': (18, None),
        'ssn_number_patient': (19, None),
        'drivers_license_number_patient': (20, None),
        'mothers_identifier': (21, None),
        'ethnic_group': (22, None),
        'birth_place': (23, None),
        'multiple_birth_indicator': (24, None),
        'birth_order': (25, None),
        'citizenship': (26, None),
        'veterans_military_status': (27, None),
        'nationality': (28, None),
        'patient_death_date_and_time': (29, datetransform),
        'patient_death_indicator': (30, None),
        'identity_unknown_indicator': (31, None),
        'identity_reliability_code': (32, None),
        'last_update_datetime': (33, datetransform),
        'last_update_facility': (34, None),
        'species_code': (35, None),
        'breed_code': (36, None),
        'strain': (37, None),
        'production_class_code': (38, None),
},
    'PEO': {\
        'event_identifiers_used': (1, None),
        'event_symptomdiagnosis_code': (2, None),
        'event_onset_datetime': (3, datetransform),
        'event_exacerbation_datetime': (4, datetransform),
        'event_improved_datetime': (5, datetransform),
        'event_ended_datatime': (6, datetransform),
        'event_location_occurred_address': (7, None),
        'event_qualification': (8, None),
        'event_serious': (9, None),
        'event_expected': (10, None),
        'event_outcome': (11, None),
        'patient_outcome': (12, None),
        'event_description_from_others': (13, None),
        'event_from_original_reporter': (14, None),
        'event_description_from_patient': (15, None),
        'event_description_from_practitioner': (16, None),
        'event_description_from_autopsy': (17, None),
        'cause_of_death': (18, None),
        'primary_observer_name': (19, None),
        'primary_observer_address': (20, None),
        'primary_observer_telephone': (21, None),
        'primary_observers_qualification': (22, None),
        'confirmation_provided_by': (23, None),
        'primary_observer_aware_datetime': (24, datetransform),
        'primary_observers_identity_may_be_divulged': (25, None),
},
    'TCD': {\
        'universal_service_identifier': (1, None),
        'auto_dilution_factor': (2, None),
        'rerun_dilution_factor': (3, None),
        'pre_dilution_factor': (4, None),
        'endogenous_content_of_pre_dilution_diluent': (5, None),
        'automatic_repeat_allowed': (6, None),
        'reflex_allowed': (7, None),
        'analyte_repeat_status': (8, None),
},
    'LAN': {\
        'set_id': (1, None),
        'language_code': (2, None),
        'language_ability_code': (3, None),
        'language_proficiency_code': (4, None),
},
    'OM7': {\
        'sequence_number_test_observation_master_file': (1, None),
        'universal_service_identifier': (2, None),
        'category_identifier': (3, None),
        'category_description': (4, None),
        'category_synonym': (5, None),
        'effective_testservice_start_datetime': (6, datetransform),
        'effective_testservice_end_datetime': (7, datetransform),
        'testservice_default_duration_quantity': (8, None),
        'testservice_default_duration_units': (9, None),
        'testservice_default_frequency': (10, None),
        'consent_indicator': (11, None),
        'consent_identifier': (12, None),
        'consent_effective_start_datetime': (13, datetransform),
        'consent_effective_end_datetime': (14, datetransform),
        'consent_interval_quantity': (15, None),
        'consent_interval_units': (16, None),
        'consent_waiting_period_quantity': (17, None),
        'consent_waiting_period_units': (18, None),
        'effective_datetime_of_change': (19, datetransform),
        'entered_by': (20, None),
        'orderable_at_location': (21, None),
        'formulary_status': (22, None),
        'special_order_indicator': (23, None),
        'primary_key_value': (24, None),
},
    'DB1': {\
        'set_id': (1, None),
        'disabled_person_code': (2, None),
        'disabled_person_identifier': (3, None),
        'disability_indicator': (4, None),
        'disability_start_date': (5, datetransform),
        'disability_end_date': (6, datetransform),
        'disability_return_to_work_date': (7, datetransform),
        'disability_unable_to_work_date': (8, datetransform),
},
    'NDS': {\
        'notification_reference_number': (1, None),
        'notification_datetime': (2, datetransform),
        'notification_alert_severity': (3, None),
        'notification_code': (4, None),
},
    'ACC': {\
        'accident_datetime': (1, datetransform),
        'accident_code': (2, None),
        'accident_location': (3, None),
        'auto_accident_state': (4, None),
        'accident_job_related_indicator': (5, None),
        'accident_death_indicator': (6, None),
        'entered_by': (7, None),
        'accident_description': (8, None),
        'brought_in_by': (9, None),
        'police_notified_indicator': (10, None),
},
    'SID': {\
        'applicationmethod_identifier': (1, None),
        'substance_lot_number': (2, None),
        'substance_container_identifier': (3, None),
        'substance_manufacturer_identifier': (4, None),
},
    'RF1': {\
        'referral_status': (1, None),
        'referral_priority': (2, None),
        'referral_type': (3, None),
        'referral_disposition': (4, None),
        'referral_category': (5, None),
        'originating_referral_identifier': (6, None),
        'effective_date': (7, datetransform),
        'expiration_date': (8, datetransform),
        'process_date': (9, datetransform),
        'referral_reason': (10, None),
        'external_referral_identifier': (11, None),
},
    'NCK': {\
        'system_datetime': (1, datetransform),
},
    'EVN': {\
        'event_type_code': (1, None),
        'recorded_datetime': (2, datetransform),
        'datetime_planned_event': (3, datetransform),
        'event_reason_code': (4, None),
        'operator_id': (5, None),
        'event_occurred': (6, datetransform),
        'event_facility': (7, None),
},
    'OM4': {\
        'sequence_number_test_observation_master_file': (1, None),
        'derived_specimen': (2, None),
        'container_description': (3, None),
        'container_volume': (4, None),
        'container_units': (5, None),
        'specimen': (6, None),
        'additive': (7, None),
        'preparation': (8, None),
        'special_handling_requirements': (9, None),
        'normal_collection_volume': (10, None),
        'minimum_collection_volume': (11, None),
        'specimen_requirements': (12, None),
        'specimen_priorities': (13, None),
        'specimen_retention_time': (14, None),
},
    'NTE': {\
        'set_id': (1, None),
        'source_of_comment': (2, None),
        'comment': (3, None),
        'comment_type': (4, None),
},
    'AIS': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'universal_service_identifier': (3, None),
        'start_datetime': (4, datetransform),
        'start_datetime_offset': (5, None),
        'start_datetime_offset_units': (6, None),
        'duration': (7, None),
        'duration_units': (8, None),
        'allow_substitution_code': (9, None),
        'filler_status_code': (10, None),
        'placer_supplemental_service_information': (11, None),
        'filler_supplemental_service_information': (12, None),
},
    'SAC': {\
        'external_accession_identifier': (1, None),
        'accession_identifier': (2, None),
        'container_identifier': (3, None),
        'primary_parent_container_identifier': (4, None),
        'equipment_container_identifier': (5, None),
        'specimen_source': (6, None),
        'registration_datetime': (7, datetransform),
        'container_status': (8, None),
        'carrier_type': (9, None),
        'carrier_identifier': (10, None),
        'position_in_carrier': (11, None),
        'tray_type': (12, None),
        'tray_identifier': (13, None),
        'position_in_tray': (14, None),
        'location': (15, None),
        'container_height': (16, None),
        'container_diameter': (17, None),
        'barrier_delta': (18, None),
        'bottom_delta': (19, None),
        'container_heightdiameterdelta_units': (20, None),
        'container_volume': (21, None),
        'available_volume': (22, None),
        'initial_specimen_volume': (23, None),
        'volume_units': (24, None),
        'separator_type': (25, None),
        'cap_type': (26, None),
        'additive': (27, None),
        'specimen_component': (28, None),
        'dilution_factor': (29, None),
        'treatment': (30, None),
        'temperature': (31, None),
        'hemolysis_index': (32, None),
        'hemolysis_index_units': (33, None),
        'lipemia_index': (34, None),
        'lipemia_index_units': (35, None),
        'icterus_index': (36, None),
        'icterus_index_units': (37, None),
        'fibrin_index': (38, None),
        'fibrin_index_units': (39, None),
        'system_induced_contaminants': (40, None),
        'drug_interference': (41, None),
        'artificial_blood': (42, None),
        'special_handling_considerations': (43, None),
        'other_environmental_factors': (44, None),
},
    'PRA': {\
        'primary_key_value': (1, None),
        'practitioner_group': (2, None),
        'practitioner_category': (3, None),
        'provider_billing': (4, None),
        'specialty': (5, None),
        'practitioner_id_numbers': (6, None),
        'privileges': (7, None),
        'date_entered_practice': (8, datetransform),
        'institution': (9, None),
        'date_left_practice': (10, datetransform),
        'government_reimbursement_billing_eligibility': (11, None),
        'set_id': (12, None),
},
    'RXG': {\
        'give_sub_id_counter': (1, None),
        'dispense_sub_id_counter': (2, None),
        'quantitytiming': (3, None),
        'give_code': (4, None),
        'give_amount_minimum': (5, None),
        'give_amount_maximum': (6, None),
        'give_units': (7, None),
        'give_dosage_form': (8, None),
        'administration_notes': (9, None),
        'substitution_status': (10, None),
        'dispense_to_location': (11, None),
        'needs_human_review': (12, None),
        'pharmacytreatment_suppliers_special_administration_instructions': (13, None),
        'give_per_time_unit': (14, None),
        'give_rate_amount': (15, None),
        'give_rate_units': (16, None),
        'give_strength': (17, None),
        'give_strength_units': (18, None),
        'substance_lot_number': (19, None),
        'substance_expiration_date': (20, datetransform),
        'substance_manufacturer_name': (21, None),
        'indication': (22, None),
},
    'MRG': {\
        'prior_patient_identifier_list': (1, None),
        'prior_alternate_patient_id': (2, None),
        'prior_patient_account_number': (3, None),
        'prior_patient_id': (4, None),
        'prior_visit_number': (5, None),
        'prior_alternate_visit_id': (6, None),
        'prior_patient_name': (7, None),
},
    'IAM': {\
        'set_id': (1, None),
        'allergen_type_code': (2, None),
        'allergen_codemnemonicdescription': (3, None),
        'allergy_severity_code': (4, None),
        'allergy_reaction_code': (5, None),
        'allergy_action_code': (6, None),
        'allergy_unique_identifier': (7, None),
        'action_reason': (8, None),
        'sensitivity_to_causative_agent_code': (9, None),
        'allergen_group_codemnemonicdescription': (10, None),
        'onset_date': (11, datetransform),
        'onset_date_text': (12, None),
        'reported_datetime': (13, datetransform),
        'reported_by': (14, None),
        'relationship_to_patient_code': (15, None),
        'alert_device_code': (16, None),
        'allergy_clinical_status_code': (17, None),
        'statused_by_person': (18, None),
        'statused_by_organization': (19, None),
        'statused_at_datetime': (20, datetransform),
},
    'VAR': {\
        'variance_instance_id': (1, None),
        'documented_datetime': (2, datetransform),
        'stated_variance_datetime': (3, datetransform),
        'variance_originator': (4, None),
        'variance_classification': (5, None),
        'variance_description': (6, None),
},
    'RXC': {\
        'rx_component_type': (1, None),
        'component_code': (2, None),
        'component_amount': (3, None),
        'component_units': (4, None),
        'component_strength': (5, None),
        'component_strength_units': (6, None),
        'supplementary_code': (7, None),
},
    'ODT': {\
        'tray_type': (1, None),
        'service_period': (2, None),
        'text_instruction': (3, None),
},
    'CM2': {\
        'set_id_cm2': (1, None),
        'scheduled_time_point': (2, None),
        'description_of_time_point': (3, None),
        'events_scheduled_this_time_point': (4, None),
},
    'CSR': {\
        'sponsor_study_id': (1, None),
        'alternate_study_id': (2, None),
        'institution_registering_the_patient': (3, None),
        'sponsor_patient_id': (4, None),
        'alternate_patient_id': (5, None),
        'datetime_of_patient_study_registration': (6, datetransform),
        'person_performing_study_registration': (7, None),
        'study_authorizing_provider': (8, None),
        'datetime_patient_study_consent_signed': (9, datetransform),
        'patient_study_eligibility_status': (10, None),
        'study_randomization_datetime': (11, datetransform),
        'randomized_study_arm': (12, None),
        'stratum_for_study_randomization': (13, None),
        'patient_evaluability_status': (14, None),
        'datetime_ended_study': (15, datetransform),
        'reason_ended_study': (16, None),
},
    'TCC': {\
        'universal_service_identifier': (1, None),
        'test_application_identifier': (2, None),
        'specimen_source': (3, None),
        'auto_dilution_factor_default': (4, None),
        'rerun_dilution_factor_default': (5, None),
        'pre_dilution_factor_default': (6, None),
        'endogenous_content_of_pre_dilution_diluent': (7, None),
        'inventory_limits_warning_level': (8, None),
        'automatic_rerun_allowed': (9, None),
        'automatic_repeat_allowed': (10, None),
        'automatic_reflex_allowed': (11, None),
        'equipment_dynamic_range': (12, None),
        'units': (13, None),
        'processing_type': (14, None),
},
    'PES': {\
        'sender_organization_name': (1, None),
        'sender_individual_name': (2, None),
        'sender_address': (3, None),
        'sender_telephone': (4, None),
        'sender_event_identifier': (5, None),
        'sender_sequence_number': (6, None),
        'sender_event_description': (7, None),
        'sender_comment': (8, None),
        'sender_aware_datetime': (9, datetransform),
        'event_report_date': (10, datetransform),
        'event_report_timingtype': (11, None),
        'event_report_source': (12, None),
        'event_reported_to': (13, None),
},
    'LCC': {\
        'primary_key_value': (1, None),
        'location_department': (2, None),
        'accommodation_type': (3, None),
        'charge_code': (4, None),
},
    'ISD': {\
        'reference_interaction_number_unique_identifier': (1, None),
        'interaction_type_identifier': (2, None),
        'interaction_active_state': (3, None),
},
    'QAK': {\
        'query_tag': (1, None),
        'query_response_status': (2, None),
        'message_query_name': (3, None),
        'hit_count_total': (4, None),
        'this_payload': (5, None),
        'hits_remaining': (6, None),
},
    'SCH': {\
        'placer_appointment_id': (1, None),
        'filler_appointment_id': (2, None),
        'occurrence_number': (3, None),
        'placer_group_number': (4, None),
        'schedule_id': (5, None),
        'event_reason': (6, None),
        'appointment_reason': (7, None),
        'appointment_type': (8, None),
        'appointment_duration': (9, None),
        'appointment_duration_units': (10, None),
        'appointment_timing_quantity': (11, None),
        'placer_contact_person': (12, None),
        'placer_contact_phone_number': (13, None),
        'placer_contact_address': (14, None),
        'placer_contact_location': (15, None),
        'filler_contact_person': (16, None),
        'filler_contact_phone_number': (17, None),
        'filler_contact_address': (18, None),
        'filler_contact_location': (19, None),
        'entered_by_person': (20, None),
        'entered_by_phone_number': (21, None),
        'entered_by_location': (22, None),
        'parent_placer_appointment_id': (23, None),
        'parent_filler_appointment_id': (24, None),
        'filler_status_code': (25, None),
        'placer_order_number': (26, None),
        'filler_order_number': (27, None),
},
    'MFE': {\
        'record_level_event_code': (1, None),
        'mfn_control_id': (2, None),
        'effective_datetime': (3, datetransform),
        'primary_key_value': (4, None),
        'primary_key_value_type': (5, None),
},
    'ERQ': {\
        'query_tag': (1, None),
        'event_identifier': (2, None),
        'input_parameter_list': (3, None),
},
    'CDM': {\
        'primary_key_value': (1, None),
        'charge_code_alias': (2, None),
        'charge_description_short': (3, None),
        'charge_description_long': (4, None),
        'description_override_indicator': (5, None),
        'exploding_charges': (6, None),
        'procedure_code': (7, None),
        'activeinactive_flag': (8, None),
        'inventory_number': (9, None),
        'resource_load': (10, None),
        'contract_number': (11, None),
        'contract_organization': (12, None),
        'room_fee_indicator': (13, None),
},
    'QID': {\
        'query_tag': (1, None),
        'message_query_name': (2, None),
},
    'RCP': {\
        'query_priority': (1, None),
        'quantity_limited_request': (2, None),
        'response_modality': (3, None),
        'execution_and_delivery_time': (4, datetransform),
        'modify_indicator': (5, None),
        'sort_by_field': (6, None),
        'segment_group_inclusion': (7, None),
},
    'RXA': {\
        'give_sub_id_counter': (1, None),
        'administration_sub_id_counter': (2, None),
        'datetime_start_of_administration': (3, datetransform),
        'datetime_end_of_administration': (4, datetransform),
        'administered_code': (5, None),
        'administered_amount': (6, None),
        'administered_units': (7, None),
        'administered_dosage_form': (8, None),
        'administration_notes': (9, None),
        'administering_provider': (10, None),
        'administered_at_location': (11, None),
        'administered_per_time_unit': (12, None),
        'administered_strength': (13, None),
        'administered_strength_units': (14, None),
        'substance_lot_number': (15, None),
        'substance_expiration_date': (16, datetransform),
        'substance_manufacturer_name': (17, None),
        'substancetreatment_refusal_reason': (18, None),
        'indication': (19, None),
        'completion_status': (20, None),
        'action_code': (21, None),
        'system_entry_datetime': (22, datetransform),
},
    'DSP': {\
        'set_id': (1, None),
        'display_level': (2, None),
        'data_line': (3, None),
        'logical_break_point': (4, None),
        'result_id': (5, None),
},
    'AIP': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'personnel_resource_id': (3, None),
        'resource_role': (4, None),
        'resource_group': (5, None),
        'start_datetime': (6, datetransform),
        'start_datetime_offset': (7, None),
        'start_datetime_offset_units': (8, None),
        'duration': (9, None),
        'duration_units': (10, None),
        'allow_substitution_code': (11, None),
        'filler_status_code': (12, None),
},
    'ARQ': {\
        'placer_appointment_id': (1, None),
        'filler_appointment_id': (2, None),
        'occurrence_number': (3, None),
        'placer_group_number': (4, None),
        'schedule_id': (5, None),
        'request_event_reason': (6, None),
        'appointment_reason': (7, None),
        'appointment_type': (8, None),
        'appointment_duration': (9, None),
        'appointment_duration_units': (10, None),
        'requested_start_datetime_range': (11, None),
        'priority': (12, None),
        'repeating_interval': (13, None),
        'repeating_interval_duration': (14, None),
        'placer_contact_person': (15, None),
        'placer_contact_phone_number': (16, None),
        'placer_contact_address': (17, None),
        'placer_contact_location': (18, None),
        'entered_by_person': (19, None),
        'entered_by_phone_number': (20, None),
        'entered_by_location': (21, None),
        'parent_placer_appointment_id': (22, None),
        'parent_filler_appointment_id': (23, None),
        'placer_order_number': (24, None),
        'filler_order_number': (25, None),
},
    'UB1': {\
        'set_id': (1, None),
        'blood_deductible_43': (2, None),
        'blood_furnished_pints_of_40': (3, None),
        'blood_replaced_pints_41': (4, None),
        'blood_not_replaced_pints42': (5, None),
        'co_insurance_days_25': (6, None),
        'condition_code_35_39': (7, None),
        'covered_days_23': (8, None),
        'non_covered_days_24': (9, None),
        'value_amount_code_46_49': (10, None),
        'number_of_grace_days_90': (11, None),
        'special_program_indicator_44': (12, None),
        'psrour_approval_indicator_87': (13, None),
        'psrour_approved_stay_fm_88': (14, datetransform),
        'psrour_approved_stay_to_89': (15, datetransform),
        'occurrence_28_32': (16, None),
        'occurrence_span_33': (17, None),
        'occur_span_start_date33': (18, datetransform),
        'occur_span_end_date_33': (19, datetransform),
        'ub_82_locator_2': (20, None),
        'ub_82_locator_9': (21, None),
        'ub_82_locator_27': (22, None),
        'ub_82_locator_45': (23, None),
},
    'MSH': {\
        'field_separator': (0, None),
        'encoding_characters': (1, None),
        'sending_application': (2, None),
        'sending_facility': (3, None),
        'receiving_application': (4, None),
        'receiving_facility': (5, None),
        'datetime_of_message': (6, datetransform),
        'security': (7, None),
        'message_type': (8, None),
        'message_control_id': (9, None),
        'processing_id': (10, None),
        'version_id': (11, None),
        'sequence_number': (12, None),
        'continuation_pointer': (13, None),
        'accept_acknowledgment_type': (14, None),
        'application_acknowledgment_type': (15, None),
        'country_code': (16, None),
        'character_set': (17, None),
        'principal_language_of_message': (18, None),
        'alternate_character_set_handling_scheme': (19, None),
        'conformance_statement_id': (20, None),
},
    'RQ1': {\
        'anticipated_price': (1, None),
        'manufacturer_identifier': (2, None),
        'manufacturers_catalog': (3, None),
        'vendor_id': (4, None),
        'vendor_catalog': (5, None),
        'taxable': (6, None),
        'substitute_allowed': (7, None),
},
    'QRI': {\
        'candidate_confidence': (1, None),
        'match_reason_code': (2, None),
        'algorithm_descriptor': (3, None),
},
    'RMI': {\
        'risk_management_incident_code': (1, None),
        'datetime_incident': (2, datetransform),
        'incident_type_code': (3, None),
},
    'ECD': {\
        'reference_command_number': (1, None),
        'remote_control_command': (2, None),
        'response_required': (3, None),
        'requested_completion_time': (4, None),
        'parameters': (5, None),
},
    'BHS': {\
        'batch_field_separator': (1, None),
        'batch_encoding_characters': (2, None),
        'batch_sending_application': (3, None),
        'batch_sending_facility': (4, None),
        'batch_receiving_application': (5, None),
        'batch_receiving_facility': (6, None),
        'batch_creation_datetime': (7, datetransform),
        'batch_security': (8, None),
        'batch_nameidtype': (9, None),
        'batch_comment': (10, None),
        'batch_control_id': (11, None),
        'reference_batch_control_id': (12, None),
},
    'AFF': {\
        'set_id': (1, None),
        'professional_organization': (2, None),
        'professional_organization_address': (3, None),
        'professional_organization_affiliation_date_range': (4, None),
        'professional_affiliation_additional_information': (5, None),
},
    'PV1': {\
        'set_id': (1, None),
        'patient_class': (2, None),
        'assigned_patient_location': (3, None),
        'admission_type': (4, None),
        'preadmit_number': (5, None),
        'prior_patient_location': (6, None),
        'attending_doctor': (7, None),
        'referring_doctor': (8, None),
        'consulting_doctor': (9, None),
        'hospital_service': (10, None),
        'temporary_location': (11, None),
        'preadmit_test_indicator': (12, None),
        're_admission_indicator': (13, None),
        'admit_source': (14, None),
        'ambulatory_status': (15, None),
        'vip_indicator': (16, None),
        'admitting_doctor': (17, None),
        'patient_type': (18, None),
        'visit_number': (19, None),
        'financial_class': (20, None),
        'charge_price_indicator': (21, None),
        'courtesy_code': (22, None),
        'credit_rating': (23, None),
        'contract_code': (24, None),
        'contract_effective_date': (25, datetransform),
        'contract_amount': (26, None),
        'contract_period': (27, None),
        'interest_code': (28, None),
        'transfer_to_bad_debt_code': (29, None),
        'transfer_to_bad_debt_date': (30, datetransform),
        'bad_debt_agency_code': (31, None),
        'bad_debt_transfer_amount': (32, None),
        'bad_debt_recovery_amount': (33, None),
        'delete_account_indicator': (34, None),
        'delete_account_date': (35, datetransform),
        'discharge_disposition': (36, None),
        'discharged_to_location': (37, None),
        'diet_type': (38, None),
        'servicing_facility': (39, None),
        'bed_status': (40, None),
        'account_status': (41, None),
        'pending_location': (42, None),
        'prior_temporary_location': (43, None),
        'admit_datetime': (44, datetransform),
        'discharge_datetime': (45, datetransform),
        'current_patient_balance': (46, None),
        'total_charges': (47, None),
        'total_adjustments': (48, None),
        'total_payments': (49, None),
        'alternate_visit_id': (50, None),
        'visit_indicator': (51, None),
        'other_healthcare_provider': (52, None),
},
    'RQD': {\
        'requisition_line_number': (1, None),
        'item_code_internal': (2, None),
        'item_code_external': (3, None),
        'hospital_item_code': (4, None),
        'requisition_quantity': (5, None),
        'requisition_unit_of_measure': (6, None),
        'dept_cost_center': (7, None),
        'item_natural_account_code': (8, None),
        'deliver_to_id': (9, None),
        'date_needed': (10, datetransform),
},
    'EDU': {\
        'set_id': (1, None),
        'academic_degree': (2, None),
        'academic_degree_program_date_range': (3, None),
        'academic_degree_program_participation_date_range': (4, None),
        'academic_degree_granted_date': (5, datetransform),
        'school': (6, None),
        'school_type_code': (7, None),
        'school_address': (8, None),
},
    'NPU': {\
        'bed_location': (1, None),
        'bed_status': (2, None),
},
    'PCR': {\
        'implicated_product': (1, None),
        'generic_product': (2, None),
        'product_class': (3, None),
        'total_duration_of_therapy': (4, None),
        'product_manufacture_date': (5, datetransform),
        'product_expiration_date': (6, datetransform),
        'product_implantation_date': (7, datetransform),
        'product_explantation_date': (8, datetransform),
        'single_use_device': (9, None),
        'indication_for_product_use': (10, None),
        'product_problem': (11, None),
        'product_seriallot_number': (12, None),
        'product_available_for_inspection': (13, None),
        'product_evaluation_performed': (14, None),
        'product_evaluation_status': (15, None),
        'product_evaluation_results': (16, None),
        'evaluated_product_source': (17, None),
        'date_product_returned_to_manufacturer': (18, datetransform),
        'device_operator_qualifications': (19, None),
        'relatedness_assessment': (20, None),
        'action_taken_in_response_to_the_event': (21, None),
        'event_causality_observations': (22, None),
        'indirect_exposure_mechanism': (23, None),
},
    'CM0': {\
        'set_id': (1, None),
        'sponsor_study_id': (2, None),
        'alternate_study_id': (3, None),
        'title_of_study': (4, None),
        'chairman_of_study': (5, None),
        'last_irb_approval_date': (6, datetransform),
        'total_accrual_to_date': (7, None),
        'last_accrual_date': (8, datetransform),
        'contact_for_study': (9, None),
        'contacts_telephone_number': (10, None),
        'contacts_address': (11, None),
},
    'PRC': {\
        'primary_key_value': (1, None),
        'facility_id': (2, None),
        'department': (3, None),
        'valid_patient_classes': (4, None),
        'price': (5, None),
        'formula': (6, None),
        'minimum_quantity': (7, None),
        'maximum_quantity': (8, None),
        'minimum_price': (9, None),
        'maximum_price': (10, None),
        'effective_start_date': (11, datetransform),
        'effective_end_date': (12, datetransform),
        'price_override_flag': (13, None),
        'billing_category': (14, None),
        'chargeable_flag': (15, None),
        'activeinactive_flag': (16, None),
        'cost': (17, None),
        'charge_on_indicator': (18, None),
},
    'IN3': {\
        'set_id': (1, None),
        'certification_number': (2, None),
        'certified_by': (3, None),
        'certification_required': (4, None),
        'penalty': (5, None),
        'certification_datetime': (6, datetransform),
        'certification_modify_datetime': (7, datetransform),
        'operator': (8, None),
        'certification_begin_date': (9, datetransform),
        'certification_end_date': (10, datetransform),
        'days': (11, None),
        'non_concur_codedescription': (12, None),
        'non_concur_effective_datetime': (13, datetransform),
        'physician_reviewer': (14, None),
        'certification_contact': (15, None),
        'certification_contact_phone_number': (16, None),
        'appeal_reason': (17, None),
        'certification_agency': (18, None),
        'certification_agency_phone_number': (19, None),
        'pre_certification_reqwindow': (20, None),
        'case_manager': (21, None),
        'second_opinion_date': (22, datetransform),
        'second_opinion_status': (23, None),
        'second_opinion_documentation_received': (24, None),
        'second_opinion_physician': (25, None),
},
    'BTS': {\
        'batch_message_count': (1, None),
        'batch_comment': (2, None),
        'batch_totals': (3, None),
},
    'GP1': {\
        'type_of_bill_code': (1, None),
        'revenue_code': (2, None),
        'overall_claim_disposition_code': (3, None),
        'oce_edits_per_visit_code': (4, None),
        'outlier_cost': (5, None),
},
    'RGS': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'resource_group_id': (3, None),
},
    'OBR': {\
        'set_id': (1, None),
        'placer_order_number': (2, None),
        'filler_order_number': (3, None),
        'universal_service_identifier': (4, None),
        'priority': (5, None),
        'requested_datetime': (6, datetransform),
        'observation_datetime_num': (7, datetransform),
        'observation_end_datetime_num': (8, datetransform),
        'collection_volume_': (9, None),
        'collector_identifier_': (10, None),
        'specimen_action_code_': (11, None),
        'danger_code': (12, None),
        'relevant_clinical_info': (13, None),
        'specimen_received_datetime_': (14, datetransform),
        'specimen_source': (15, None),
        'ordering_provider': (16, None),
        'order_callback_phone_number': (17, None),
        'placer_field_1': (18, None),
        'placer_field_2': (19, None),
        'filler_field_1_': (20, None),
        'filler_field_2_': (21, None),
        'results_rptstatus_chng_datetime_': (22, datetransform),
        'charge_to_practice_': (23, None),
        'diagnostic_serv_sect_id': (24, None),
        'result_status_': (25, None),
        'parent_result_': (26, None),
        'quantitytiming': (27, None),
        'result_copies_to': (28, None),
        'parent': (29, None),
        'transportation_mode': (30, None),
        'reason_for_study': (31, None),
        'principal_result_interpreter_': (32, None),
        'assistant_result_interpreter_': (33, None),
        'technician_': (34, None),
        'transcriptionist_': (35, None),
        'scheduled_datetime_': (36, datetransform),
        'number_of_sample_containers_': (37, None),
        'transport_logistics_of_collected_sample_': (38, None),
        'collectors_comment_': (39, None),
        'transport_arrangement_responsibility': (40, None),
        'transport_arranged': (41, None),
        'escort_required': (42, None),
        'planned_patient_transport_comment': (43, None),
        'procedure_code': (44, None),
        'procedure_code_modifier': (45, None),
        'placer_supplemental_service_information': (46, None),
        'filler_supplemental_service_information': (47, None),
},
    'ABS': {\
        'discharge_care_provider': (1, None),
        'transfer_medical_service_code': (2, None),
        'severity_of_illness_code': (3, None),
        'datetime_of_attestation': (4, datetransform),
        'attested_by': (5, None),
        'triage_code': (6, None),
        'abstract_completion_datetime': (7, datetransform),
        'abstracted_by': (8, None),
        'case_category_code': (9, None),
        'caesarian_section_indicator': (10, None),
        'gestation_category_code': (11, None),
        'gestation_period_weeks': (12, None),
        'newborn_code': (13, None),
        'stillborn_indicator': (14, None),
},
    'PR1': {\
        'set_id': (1, None),
        'procedure_coding_method': (2, None),
        'procedure_code': (3, None),
        'procedure_description': (4, None),
        'procedure_datetime': (5, datetransform),
        'procedure_functional_type': (6, None),
        'procedure_minutes': (7, None),
        'anesthesiologist': (8, None),
        'anesthesia_code': (9, None),
        'anesthesia_minutes': (10, None),
        'surgeon': (11, None),
        'procedure_practitioner': (12, None),
        'consent_code': (13, None),
        'procedure_priority': (14, None),
        'associated_diagnosis_code': (15, None),
        'procedure_code_modifier': (16, None),
        'procedure_drg_type': (17, None),
        'tissue_type_code': (18, None),
},
    'AIG': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'resource_id': (3, None),
        'resource_type': (4, None),
        'resource_group': (5, None),
        'resource_quantity': (6, None),
        'resource_quantity_units': (7, None),
        'start_datetime': (8, datetransform),
        'start_datetime_offset': (9, None),
        'start_datetime_offset_units': (10, None),
        'duration': (11, None),
        'duration_units': (12, None),
        'allow_substitution_code': (13, None),
        'filler_status_code': (14, None),
},
    'FTS': {\
        'file_batch_count': (1, None),
        'file_trailer_comment': (2, None),
},
    'STF': {\
        'primary_key_value': (1, None),
        'staff_id_code': (2, None),
        'staff_name': (3, None),
        'staff_type': (4, None),
        'administrative_sex': (5, None),
        'datetime_of_birth': (6, datetransform),
        'activeinactive_flag': (7, None),
        'department': (8, None),
        'hospital_service': (9, None),
        'phone': (10, None),
        'officehome_address': (11, None),
        'institution_activation_date': (12, None),
        'institution_inactivation_date': (13, None),
        'backup_person_id': (14, None),
        'e_mail_address': (15, None),
        'preferred_method_of_contact': (16, None),
        'marital_status': (17, None),
        'job_title': (18, None),
        'job_codeclass': (19, None),
        'employment_status_code': (20, None),
        'additional_insured_on_auto': (21, None),
        'drivers_license_number_staff': (22, None),
        'copy_auto_ins': (23, None),
        'auto_ins_expires': (24, datetransform),
        'date_last_dmv_review': (25, datetransform),
        'date_next_dmv_review': (26, datetransform),
        'race': (27, None),
        'ethnic_group': (28, None),
        're_activation_approval_indicator': (29, None),
},
    'RXE': {\
        'quantitytiming': (1, None),
        'give_code': (2, None),
        'give_amount_minimum': (3, None),
        'give_amount_maximum': (4, None),
        'give_units': (5, None),
        'give_dosage_form': (6, None),
        'providers_administration_instructions': (7, None),
        'deliver_to_location': (8, None),
        'substitution_status': (9, None),
        'dispense_amount': (10, None),
        'dispense_units': (11, None),
        'number_of_refills': (12, None),
        'ordering_providers_dea_number': (13, None),
        'pharmacisttreatment_suppliers_verifier_id': (14, None),
        'prescription_number': (15, None),
        'number_of_refills_remaining': (16, None),
        'number_of_refillsdoses_dispensed': (17, None),
        'dt_of_most_recent_refill_or_dose_dispensed': (18, datetransform),
        'total_daily_dose': (19, None),
        'needs_human_review': (20, None),
        'pharmacytreatment_suppliers_special_dispensing_instructions': (21, None),
        'give_per_time_unit': (22, None),
        'give_rate_amount': (23, None),
        'give_rate_units': (24, None),
        'give_strength': (25, None),
        'give_strength_units': (26, None),
        'give_indication': (27, None),
        'dispense_package_size': (28, None),
        'dispense_package_size_unit': (29, None),
        'dispense_package_method': (30, None),
        'supplementary_code': (31, None),
},
    'VTQ': {\
        'query_tag': (1, None),
        'queryresponse_format_code': (2, None),
        'vt_query_name': (3, None),
        'virtual_table_name': (4, None),
        'selection_criteria': (5, None),
},
    'OM6': {\
        'sequence_number_test_observation_master_file': (1, None),
        'derivation_rule': (2, None),
},
    'URD': {\
        'ru_datetime': (1, datetransform),
        'report_priority': (2, None),
        'ru_who_subject_definition': (3, None),
        'ru_what_subject_definition': (4, None),
        'ru_what_department_code': (5, None),
        'ru_displayprint_locations': (6, None),
        'ru_results_level': (7, None),
},
    'FAC': {\
        'facility_id': (1, None),
        'facility_type': (2, None),
        'facility_address': (3, None),
        'facility_telecommunication': (4, None),
        'contact_person': (5, None),
        'contact_title': (6, None),
        'contact_address': (7, None),
        'contact_telecommunication': (8, None),
        'signature_authority': (9, None),
        'signature_authority_title': (10, None),
        'signature_authority_address': (11, None),
        'signature_authority_telecommunication': (12, None),
},
    'URS': {\
        'ru_where_subject_definition': (1, None),
        'ru_when_data_start_datetime': (2, datetransform),
        'ru_when_data_end_datetime': (3, datetransform),
        'ru_what_user_qualifier': (4, None),
        'ru_other_results_subject_definition': (5, None),
        'ru_which_datetime_qualifier': (6, None),
        'ru_which_datetime_status_qualifier': (7, None),
        'ru_datetime_selection_qualifier': (8, None),
        'ru_quantitytiming_qualifier': (9, None),
},
    'GOL': {\
        'action_code': (1, None),
        'action_datetime': (2, datetransform),
        'goal_id': (3, None),
        'goal_instance_id': (4, None),
        'episode_of_care_id': (5, None),
        'goal_list_priority': (6, None),
        'goal_established_datetime': (7, datetransform),
        'expected_goal_achieve_datetime': (8, datetransform),
        'goal_classification': (9, None),
        'goal_management_discipline': (10, None),
        'current_goal_review_status': (11, None),
        'current_goal_review_datetime': (12, datetransform),
        'next_goal_review_datetime': (13, datetransform),
        'previous_goal_review_datetime': (14, datetransform),
        'goal_review_interval': (15, None),
        'goal_evaluation': (16, None),
        'goal_evaluation_comment': (17, None),
        'goal_life_cycle_status': (18, None),
        'goal_life_cycle_status_datetime': (19, datetransform),
        'goal_target_type': (20, None),
        'goal_target_name': (21, None),
},
    'LRL': {\
        'primary_key_value': (1, None),
        'segment_action_code': (2, None),
        'segment_unique_key': (3, None),
        'location_relationship_id': (4, None),
        'organizational_location_relationship_value': (5, None),
        'patient_location_relationship_value': (6, None),
},
    'IN2': {\
        'insureds_employee_id': (1, None),
        'insureds_social_security_number': (2, None),
        'insureds_employers_name_and_id': (3, None),
        'employer_information_data': (4, None),
        'mail_claim_party': (5, None),
        'medicare_health_ins_card_number': (6, None),
        'medicaid_case_name': (7, None),
        'medicaid_case_number': (8, None),
        'military_sponsor_name': (9, None),
        'military_id_number': (10, None),
        'dependent_of_military_recipient': (11, None),
        'military_organization': (12, None),
        'military_station': (13, None),
        'military_service': (14, None),
        'military_rankgrade': (15, None),
        'military_status': (16, None),
        'military_retire_date': (17, datetransform),
        'military_non_avail_cert_on_file': (18, None),
        'baby_coverage': (19, None),
        'combine_baby_bill': (20, None),
        'blood_deductible': (21, None),
        'special_coverage_approval_name': (22, None),
        'special_coverage_approval_title': (23, None),
        'non_covered_insurance_code': (24, None),
        'payor_id': (25, None),
        'payor_subscriber_id': (26, None),
        'eligibility_source': (27, None),
        'room_coverage_typeamount': (28, None),
        'policy_typeamount': (29, None),
        'daily_deductible': (30, None),
        'living_dependency': (31, None),
        'ambulatory_status': (32, None),
        'citizenship': (33, None),
        'primary_language': (34, None),
        'living_arrangement': (35, None),
        'publicity_code': (36, None),
        'protection_indicator': (37, None),
        'student_indicator': (38, None),
        'religion': (39, None),
        'mothers_maiden_name': (40, None),
        'nationality': (41, None),
        'ethnic_group': (42, None),
        'marital_status': (43, None),
        'insureds_employment_start_date': (44, datetransform),
        'employment_stop_date': (45, datetransform),
        'job_title': (46, None),
        'job_codeclass': (47, None),
        'job_status': (48, None),
        'employer_contact_person_name': (49, None),
        'employer_contact_person_phone_number': (50, None),
        'employer_contact_reason': (51, None),
        'insureds_contact_persons_name': (52, None),
        'insureds_contact_person_phone_number': (53, None),
        'insureds_contact_person_reason': (54, None),
        'relationship_to_the_patient_start_date': (55, datetransform),
        'relationship_to_the_patient_stop_date': (56, datetransform),
        'insurance_co_contact_reason': (57, None),
        'insurance_co_contact_phone_number': (58, None),
        'policy_scope': (59, None),
        'policy_source': (60, None),
        'patient_member_number': (61, None),
        'guarantors_relationship_to_insured': (62, None),
        'insureds_phone_number_home': (63, None),
        'insureds_employer_phone_number': (64, None),
        'military_handicapped_program': (65, None),
        'suspend_flag': (66, None),
        'copay_limit_flag': (67, None),
        'stoploss_limit_flag': (68, None),
        'insured_organization_name_and_id': (69, None),
        'insured_employer_organization_name_and_id': (70, None),
        'race': (71, None),
        'hcfa_patients_relationship_to_insured': (72, None),
},
    'BLG': {\
        'when_to_charge': (1, None),
        'charge_type': (2, None),
        'account_id': (3, None),
},
    'NSC': {\
        'application_change_type': (1, None),
        'current_cpu': (2, None),
        'current_fileserver': (3, None),
        'current_application': (4, None),
        'current_facility': (5, None),
        'new_cpu': (6, None),
        'new_fileserver': (7, None),
        'new_application': (8, None),
        'new_facility': (9, None),
},
    'EQL': {\
        'query_tag': (1, None),
        'queryresponse_format_code': (2, None),
        'eql_query_name': (3, None),
        'eql_query_statement': (4, None),
},
    'NST': {\
        'statistics_available': (1, None),
        'source_identifier': (2, None),
        'source_type': (3, None),
        'statistics_start': (4, datetransform),
        'statistics_end': (5, datetransform),
        'receive_character_count': (6, None),
        'send_character_count': (7, None),
        'messages_received': (8, None),
        'messages_sent': (9, None),
        'checksum_errors_received': (10, None),
        'length_errors_received': (11, None),
        'other_errors_received': (12, None),
        'connect_timeouts': (13, None),
        'receive_timeouts': (14, None),
        'application_control_level_errors': (15, None),
},
    'ORG': {\
        'set_id': (1, None),
        'organization_unit_code': (2, None),
        'organization_unit_type_code': (3, None),
        'primary_org_unit_indicator': (4, None),
        'practitioner_org_unit_identifier': (5, None),
        'health_care_provider_type_code': (6, None),
        'health_care_provider_classification_code': (7, None),
        'health_care_provider_area_of_specialization_code': (8, None),
        'effective_date_range': (9, None),
        'employment_status_code': (10, None),
        'board_approval_indicator': (11, None),
        'primary_care_physician_indicator': (12, None),
},
    'MFI': {\
        'master_file_identifier': (1, None),
        'master_file_application_identifier': (2, None),
        'file_level_event_code': (3, None),
        'entered_datetime': (4, datetransform),
        'effective_datetime': (5, datetransform),
        'response_level_code': (6, None),
},
    'LOC': {\
        'primary_key_value': (1, None),
        'location_description': (2, None),
        'location_type': (3, None),
        'organization_name': (4, None),
        'location_address': (5, None),
        'location_phone': (6, None),
        'license_number': (7, None),
        'location_equipment': (8, None),
        'location_service_code': (9, None),
},
    'UB2': {\
        'set_id': (1, None),
        'co_insurance_days_9': (2, None),
        'condition_code_24_30': (3, None),
        'covered_days_7': (4, None),
        'non_covered_days_8': (5, None),
        'value_amount_code': (6, None),
        'occurrence_code_date_32_35': (7, None),
        'occurrence_span_codedates_36': (8, None),
        'ub92_locator_2_state': (9, None),
        'ub92_locator_11_state': (10, None),
        'ub92_locator_31_national': (11, None),
        'document_control_number': (12, None),
        'ub92_locator_49_national': (13, None),
        'ub92_locator_56_state': (14, None),
        'ub92_locator_57_national': (15, None),
        'ub92_locator_78_state': (16, None),
        'special_visit_count': (17, None),
},
    'RXD': {\
        'dispense_sub_id_counter': (1, None),
        'dispensegive_code': (2, None),
        'datetime_dispensed': (3, datetransform),
        'actual_dispense_amount': (4, None),
        'actual_dispense_units': (5, None),
        'actual_dosage_form': (6, None),
        'prescription_number': (7, None),
        'number_of_refills_remaining': (8, None),
        'dispense_notes': (9, None),
        'dispensing_provider': (10, None),
        'substitution_status': (11, None),
        'total_daily_dose': (12, None),
        'dispense_to_location': (13, None),
        'needs_human_review': (14, None),
        'pharmacytreatment_suppliers_special_dispensing_instructions': (15, None),
        'actual_strength': (16, None),
        'actual_strength_unit': (17, None),
        'substance_lot_number': (18, None),
        'substance_expiration_date': (19, datetransform),
        'substance_manufacturer_name': (20, None),
        'indication': (21, None),
        'dispense_package_size': (22, None),
        'dispense_package_size_unit': (23, None),
        'dispense_package_method': (24, None),
        'supplementary_code': (25, None),
        'initiating_location': (26, None),
        'packagingassembly_location': (27, None),
},
    'APR': {\
        'time_selection_criteria': (1, None),
        'resource_selection_criteria': (2, None),
        'location_selection_criteria': (3, None),
        'slot_spacing_criteria': (4, None),
        'filler_override_criteria': (5, None),
},
    'RDT': {\
        'column_value': (1, None),
},
    'OM3': {\
        'sequence_number_test_observation_master_file': (1, None),
        'preferred_coding_system': (2, None),
        'valid_coded_answers': (3, None),
        'normal_textcodes_for_categorical_observations': (4, None),
        'abnormal_textcodes_for_categorical_observations': (5, None),
        'critical_textcodes_for_categorical_observations': (6, None),
        'value_type': (7, None),
},
    'SPR': {\
        'query_tag': (1, None),
        'queryresponse_format_code': (2, None),
        'stored_procedure_name': (3, None),
        'input_parameter_list': (4, None),
},
    'OM1': {\
        'sequence_number_test_observation_master_file': (1, None),
        'producers_servicetestobservation_id': (2, None),
        'permitted_data_types': (3, None),
        'specimen_required': (4, None),
        'producer_id': (5, None),
        'observation_description': (6, None),
        'other_servicetestobservation_ids_for_the_observation': (7, None),
        'other_names': (8, None),
        'preferred_report_name_for_the_observation': (9, None),
        'preferred_short_name_or_mnemonic_for_observation': (10, None),
        'preferred_long_name_for_the_observation': (11, None),
        'orderability': (12, None),
        'identity_of_instrument_used_to_perform_this_study': (13, None),
        'coded_representation_of_method': (14, None),
        'portable_device_indicator': (15, None),
        'observation_producing_departmentsection': (16, None),
        'telephone_number_of_section': (17, None),
        'nature_of_servicetestobservation': (18, None),
        'report_subheader': (19, None),
        'report_display_order': (20, None),
        'datetime_stamp_for_any_change_in_definition_for_the_observation': (21, datetransform),
        'effective_datetime_of_change': (22, datetransform),
        'typical_turn_around_time': (23, None),
        'processing_time': (24, None),
        'processing_priority': (25, None),
        'reporting_priority': (26, None),
        'outside_sites_where_observation_may_be_performed': (27, None),
        'address_of_outside_sites': (28, None),
        'phone_number_of_outside_site': (29, None),
        'confidentiality_code': (30, None),
        'observations_required_to_interpret_the_observation': (31, None),
        'interpretation_of_observations': (32, None),
        'contraindications_to_observations': (33, None),
        'reflex_testsobservations': (34, None),
        'rules_that_trigger_reflex_testing': (35, None),
        'fixed_canned_message': (36, None),
        'patient_preparation': (37, None),
        'procedure_medication': (38, None),
        'factors_that_may_affect_affect_the_observation': (39, None),
        'servicetestobservation_performance_schedule': (40, None),
        'description_of_test_methods': (41, None),
        'kind_of_quantity_observed': (42, None),
        'point_versus_interval': (43, None),
        'challenge_information': (44, None),
        'relationship_modifier': (45, None),
        'target_anatomic_site_of_test': (46, None),
        'modality_of_imaging_measurement': (47, None),
},
    'LDP': {\
        'primary_key_value': (1, None),
        'location_department': (2, None),
        'location_service': (3, None),
        'specialty_type': (4, None),
        'valid_patient_classes': (5, None),
        'activeinactive_flag': (6, None),
        'activation_date_ldp': (7, datetransform),
        'inactivation_date': (8, datetransform),
        'inactivated_reason': (9, None),
        'visiting_hours': (10, None),
        'contact_phone': (11, None),
        'location_cost_center': (12, None),
},
    'PDC': {\
        'manufacturerdistributor': (1, None),
        'country': (2, None),
        'brand_name': (3, None),
        'device_family_name': (4, None),
        'generic_name': (5, None),
        'model_identifier': (6, None),
        'catalogue_identifier': (7, None),
        'other_identifier': (8, None),
        'product_code': (9, None),
        'marketing_basis': (10, None),
        'marketing_approval_id': (11, None),
        'labeled_shelf_life': (12, None),
        'expected_shelf_life': (13, None),
        'date_first_marketed': (14, datetransform),
        'date_last_marketed': (15, datetransform),
},
    'CNS': {\
        'starting_notification_reference_number': (1, None),
        'ending_notification_reference_number': (2, None),
        'starting_notification_datetime': (3, datetransform),
        'ending_notification_datetime': (4, datetransform),
        'starting_notification_code': (5, None),
        'ending_notification_code': (6, None),
},
    'GP2': {\
        'revenue_code': (1, None),
        'number_of_service_units': (2, None),
        'charge': (3, None),
        'reimbursement_action_code': (4, None),
        'denial_or_rejection_code': (5, None),
        'oce_edit_code': (6, None),
        'ambulatory_payment_classification_code': (7, None),
        'modifier_edit_code': (8, None),
        'payment_adjustment_code': (9, None),
        'packaging_status_code': (10, None),
        'expected_hcfa_payment_amount': (11, None),
        'reimbursement_type_code': (12, None),
        'co_pay_amount': (13, None),
        'pay_rate_per_unit': (14, None),
},
    'BLC': {\
        'blood_product_code': (1, None),
        'blood_amount': (2, None),
},
    'RXO': {\
        'requested_give_code': (1, None),
        'requested_give_amount_minimum': (2, None),
        'requested_give_amount_maximum': (3, None),
        'requested_give_units': (4, None),
        'requested_dosage_form': (5, None),
        'providers_pharmacytreatment_instructions': (6, None),
        'providers_administration_instructions': (7, None),
        'deliver_to_location': (8, None),
        'allow_substitutions': (9, None),
        'requested_dispense_code': (10, None),
        'requested_dispense_amount': (11, None),
        'requested_dispense_units': (12, None),
        'number_of_refills': (13, None),
        'ordering_providers_dea_number': (14, None),
        'pharmacisttreatment_suppliers_verifier_id': (15, None),
        'needs_human_review': (16, None),
        'requested_give_per_time_unit': (17, None),
        'requested_give_strength': (18, None),
        'requested_give_strength_units': (19, None),
        'indication': (20, None),
        'requested_give_rate_amount': (21, None),
        'requested_give_rate_units': (22, None),
        'total_daily_dose': (23, None),
        'supplementary_code': (24, None),
},
    'PRD': {\
        'provider_role': (1, None),
        'provider_name': (2, None),
        'provider_address': (3, None),
        'provider_location': (4, None),
        'provider_communication_information': (5, None),
        'preferred_method_of_contact': (6, None),
        'provider_identifiers': (7, None),
        'effective_start_date_of_provider_role': (8, datetransform),
        'effective_end_date_of_provider_role': (9, datetransform),
},
    'ORC': {\
        'order_control': (1, None),
        'placer_order_number': (2, None),
        'filler_order_number': (3, None),
        'placer_group_number': (4, None),
        'order_status': (5, None),
        'response_flag': (6, None),
        'quantitytiming': (7, None),
        'parent': (8, None),
        'datetime_of_transaction': (9, datetransform),
        'entered_by': (10, None),
        'verified_by': (11, None),
        'ordering_provider': (12, None),
        'enterers_location': (13, None),
        'call_back_phone_number': (14, None),
        'order_effective_datetime': (15, datetransform),
        'order_control_code_reason': (16, None),
        'entering_organization': (17, None),
        'entering_device': (18, None),
        'action_by': (19, None),
        'advanced_beneficiary_notice_code': (20, None),
        'ordering_facility_name': (21, None),
        'ordering_facility_address': (22, None),
        'ordering_facility_phone_number': (23, None),
        'ordering_provider_address': (24, None),
        'order_status_modifier': (25, None),
},
    'AL1': {\
        'set_id': (1, None),
        'allergen_type_code': (2, None),
        'allergen_codemnemonicdescription': (3, None),
        'allergy_severity_code': (4, None),
        'allergy_reaction_code': (5, None),
        'identification_date': (6, datetransform),
},
    'FT1': {\
        'set_id': (1, None),
        'transaction_id': (2, None),
        'transaction_batch_id': (3, None),
        'transaction_date': (4, datetransform),
        'transaction_posting_date': (5, datetransform),
        'transaction_type': (6, None),
        'transaction_code': (7, None),
        'transaction_description': (8, None),
        'transaction_description_alternative': (9, None),
        'transaction_quantity': (10, None),
        'transaction_amount_extended': (11, None),
        'transaction_amount_unit': (12, None),
        'department_code': (13, None),
        'insurance_plan_id': (14, None),
        'insurance_amount': (15, None),
        'assigned_patient_location': (16, None),
        'fee_schedule': (17, None),
        'patient_type': (18, None),
        'diagnosis_code': (19, None),
        'performed_by_code': (20, None),
        'ordered_by_code': (21, None),
        'unit_cost': (22, None),
        'filler_order_number': (23, None),
        'entered_by_code': (24, None),
        'procedure_code': (25, None),
        'procedure_code_modifier': (26, None),
},
    'INV': {\
        'substance_identifier': (1, None),
        'substance_status': (2, None),
        'substance_type': (3, None),
        'inventory_container_identifier': (4, None),
        'container_carrier_identifier': (5, None),
        'position_on_carrier': (6, None),
        'initial_quantity': (7, None),
        'current_quantity': (8, None),
        'available_quantity': (9, None),
        'consumption_quantity': (10, None),
        'quantity_units': (11, None),
        'expiration_datetime': (12, datetransform),
        'first_used_datetime': (13, datetransform),
        'on_board_stability_duration': (14, None),
        'testfluid_identifiers': (15, None),
        'manufacturer_lot_number': (16, None),
        'manufacturer_identifier': (17, None),
        'supplier_identifier': (18, None),
},
    'EQP': {\
        'event_type': (1, None),
        'file_name': (2, None),
        'start_datetime': (3, datetransform),
        'end_datetime': (4, datetransform),
        'transaction_data': (5, None),
},
    'ROL': {\
        'role_instance_id': (1, None),
        'action_code': (2, None),
        'role': (3, None),
        'role_person': (4, None),
        'role_begin_datetime': (5, datetransform),
        'role_end_datetime': (6, datetransform),
        'role_duration': (7, None),
        'role_action_reason': (8, None),
        'provider_type': (9, None),
        'organization_unit_type': (10, None),
        'officehome_address': (11, None),
        'phone': (12, None),
},
    'NK1': {\
        'set_id': (1, None),
        'name': (2, None),
        'relationship': (3, None),
        'address': (4, None),
        'phone_number': (5, None),
        'business_phone_number': (6, None),
        'contact_role': (7, None),
        'start_date': (8, datetransform),
        'end_date': (9, datetransform),
        'next_of_kinassociated_parties_job_title': (10, None),
        'next_of_kinassociated_parties_job_codeclass': (11, None),
        'next_of_kinassociated_parties_employee_number': (12, None),
        'organization_name': (13, None),
        'marital_status': (14, None),
        'administrative_sex': (15, None),
        'datetime_of_birth': (16, datetransform),
        'living_dependency': (17, None),
        'ambulatory_status': (18, None),
        'citizenship': (19, None),
        'primary_language': (20, None),
        'living_arrangement': (21, None),
        'publicity_code': (22, None),
        'protection_indicator': (23, None),
        'student_indicator': (24, None),
        'religion': (25, None),
        'mothers_maiden_name': (26, None),
        'nationality': (27, None),
        'ethnic_group': (28, None),
        'contact_reason': (29, None),
        'contact_persons_name': (30, None),
        'contact_persons_telephone_number': (31, None),
        'contact_persons_address': (32, None),
        'next_of_kinassociated_partys_identifiers': (33, None),
        'job_status': (34, None),
        'race': (35, None),
        'handicap': (36, None),
        'contact_person_social_security_number': (37, None),
},
    'DG1': {\
        'set_id': (1, None),
        'diagnosis_coding_method': (2, None),
        'diagnosis_code': (3, None),
        'diagnosis_description': (4, None),
        'diagnosis_datetime': (5, datetransform),
        'diagnosis_type': (6, None),
        'major_diagnostic_category': (7, None),
        'diagnostic_related_group': (8, None),
        'drg_approval_indicator': (9, None),
        'drg_grouper_review_code': (10, None),
        'outlier_type': (11, None),
        'outlier_days': (12, None),
        'outlier_cost': (13, None),
        'grouper_version_and_type': (14, None),
        'diagnosis_priority': (15, None),
        'diagnosing_clinician': (16, None),
        'diagnosis_classification': (17, None),
        'confidential_indicator': (18, None),
        'attestation_datetime': (19, datetransform),
},
    'ECR': {\
        'command_response': (1, None),
        'datetime_completed': (2, datetransform),
        'command_response_parameters': (3, None),
},
    'ERR': {\
        'error_code_and_location': (1, None),
},
    'ODS': {\
        'type': (1, None),
        'service_period': (2, None),
        'diet_supplement_or_preference_code': (3, None),
        'text_instruction': (4, None),
},
    'PD1': {\
        'living_dependency': (1, None),
        'living_arrangement': (2, None),
        'patient_primary_facility': (3, None),
        'patient_primary_care_provider_name_id_no': (4, None),
        'student_indicator': (5, None),
        'handicap': (6, None),
        'living_will_code': (7, None),
        'organ_donor_code': (8, None),
        'separate_bill': (9, None),
        'duplicate_patient': (10, None),
        'publicity_code': (11, None),
        'protection_indicator': (12, None),
        'protection_indicator_effective_date': (13, datetransform),
        'place_of_worship': (14, None),
        'advance_directive_code': (15, None),
        'immunization_registry_status': (16, None),
        'immunization_registry_status_effective_date': (17, datetransform),
        'publicity_code_effective_date': (18, datetransform),
        'military_branch': (19, None),
        'military_rankgrade': (20, None),
        'military_status': (21, None),
},
    'RXR': {\
        'route': (1, None),
        'administration_site': (2, None),
        'administration_device': (3, None),
        'administration_method': (4, None),
        'routing_instruction': (5, None),
},
    'OM2': {\
        'sequence_number_test_observation_master_file': (1, None),
        'units_of_measure': (2, None),
        'range_of_decimal_precision': (3, None),
        'corresponding_si_units_of_measure': (4, None),
        'si_conversion_factor': (5, None),
        'reference_normal_range_ordinal_and_continuous_observations': (6, None),
        'critical_range_for_ordinal_and_continuous_observations': (7, None),
        'absolute_range_for_ordinal_and_continuous_observations': (8, None),
        'delta_check_criteria': (9, None),
        'minimum_meaningful_increments': (10, None),
},
    'CTI': {\
        'sponsor_study_id': (1, None),
        'study_phase_identifier': (2, None),
        'study_scheduled_time_point': (3, None),
},
    'PRB': {\
        'action_code': (1, None),
        'action_datetime': (2, datetransform),
        'problem_id': (3, None),
        'problem_instance_id': (4, None),
        'episode_of_care_id': (5, None),
        'problem_list_priority': (6, None),
        'problem_established_datetime': (7, datetransform),
        'anticipated_problem_resolution_datetime': (8, datetransform),
        'actual_problem_resolution_datetime': (9, datetransform),
        'problem_classification': (10, None),
        'problem_management_discipline': (11, None),
        'problem_persistence': (12, None),
        'problem_confirmation_status': (13, None),
        'problem_life_cycle_status': (14, None),
        'problem_life_cycle_status_datetime': (15, datetransform),
        'problem_date_of_onset': (16, datetransform),
        'problem_onset_text': (17, None),
        'problem_ranking': (18, None),
        'certainty_of_problem': (19, None),
        'probability_of_problem_0_1': (20, None),
        'individual_awareness_of_problem': (21, None),
        'problem_prognosis': (22, None),
        'individual_awareness_of_prognosis': (23, None),
        'familysignificant_other_awareness_of_problemprognosis': (24, None),
        'securitysensitivity': (25, None),
},
    'CM1': {\
        'set_id': (1, None),
        'study_phase_identifier': (2, None),
        'description_of_study_phase': (3, None),
},
    'CSP': {\
        'study_phase_identifier': (1, None),
        'datetime_study_phase_began': (2, datetransform),
        'datetime_study_phase_ended': (3, datetransform),
        'study_phase_evaluability': (4, None),
},
    'QRD': {\
        'query_datetime': (1, datetransform),
        'query_format_code': (2, None),
        'query_priority': (3, None),
        'query_id': (4, None),
        'deferred_response_type': (5, None),
        'deferred_response_datetime': (6, datetransform),
        'quantity_limited_request': (7, None),
        'who_subject_filter': (8, None),
        'what_subject_filter': (9, None),
        'what_department_data_code': (10, None),
        'what_data_code_value_qual': (11, None),
        'query_results_level': (12, None),
},
    'TXA': {\
        'set_id_txa': (1, None),
        'document_type': (2, None),
        'document_content_presentation': (3, None),
        'activity_datetime': (4, datetransform),
        'primary_activity_provider_codename': (5, None),
        'origination_datetime': (6, datetransform),
        'transcription_datetime': (7, datetransform),
        'edit_datetime': (8, datetransform),
        'originator_codename': (9, None),
        'assigned_document_authenticator': (10, None),
        'transcriptionist_codename': (11, None),
        'unique_document_number': (12, None),
        'parent_document_number': (13, None),
        'placer_order_number': (14, None),
        'filler_order_number': (15, None),
        'unique_document_file_name': (16, None),
        'document_completion_status': (17, None),
        'document_confidentiality_status': (18, None),
        'document_availability_status': (19, None),
        'document_storage_status': (20, None),
        'document_change_reason': (21, None),
        'authentication_person_time_stamp': (22, None),
        'distributed_copies_code_and_name_of_recipients': (23, None),
},
    'PDA': {\
        'death_cause_code': (1, None),
        'death_location': (2, None),
        'death_certified_indicator': (3, None),
        'death_certificate_signed_datetime': (4, datetransform),
        'death_certified_by': (5, None),
        'autopsy_indicator': (6, None),
        'autopsy_start_and_end_datetime': (7, None),
        'autopsy_performed_by': (8, None),
        'coroner_indicator': (9, None),
},
    'LCH': {\
        'primary_key_value': (1, None),
        'segment_action_code': (2, None),
        'segment_unique_key': (3, None),
        'location_characteristic_id': (4, None),
        'location_characteristic_value': (5, None),
},
    'ADD': {\
        'addendum_continuation_pointer': (1, None),
},
    'IN1': {\
        'set_id': (1, None),
        'insurance_plan_id': (2, None),
        'insurance_company_id': (3, None),
        'insurance_company_name': (4, None),
        'insurance_company_address': (5, None),
        'insurance_co_contact_person': (6, None),
        'insurance_co_phone_number': (7, None),
        'group_number': (8, None),
        'group_name': (9, None),
        'insureds_group_emp_id': (10, None),
        'insureds_group_emp_name': (11, None),
        'plan_effective_date': (12, datetransform),
        'plan_expiration_date': (13, datetransform),
        'authorization_information': (14, None),
        'plan_type': (15, None),
        'name_of_insured': (16, None),
        'insureds_relationship_to_patient': (17, None),
        'insureds_date_of_birth': (18, datetransform),
        'insureds_address': (19, None),
        'assignment_of_benefits': (20, None),
        'coordination_of_benefits': (21, None),
        'coord_of_ben_priority': (22, None),
        'notice_of_admission_flag': (23, None),
        'notice_of_admission_date': (24, datetransform),
        'report_of_eligibility_flag': (25, None),
        'report_of_eligibility_date': (26, datetransform),
        'release_information_code': (27, None),
        'pre_admit_cert_pac': (28, None),
        'verification_datetime': (29, datetransform),
        'verification_by': (30, None),
        'type_of_agreement_code': (31, None),
        'billing_status': (32, None),
        'lifetime_reserve_days': (33, None),
        'delay_before_lr_day': (34, None),
        'company_plan_code': (35, None),
        'policy_number': (36, None),
        'policy_deductible': (37, None),
        'policy_limit_amount': (38, None),
        'policy_limit_days': (39, None),
        'room_rate_semi_private': (40, None),
        'room_rate_private': (41, None),
        'insureds_employment_status': (42, None),
        'insureds_administrative_sex': (43, None),
        'insureds_employers_address': (44, None),
        'verification_status': (45, None),
        'prior_insurance_plan_id': (46, None),
        'coverage_type': (47, None),
        'handicap': (48, None),
        'insureds_id_number': (49, None),
},
    'MSA': {\
        'acknowledgment_code': (1, None),
        'message_control_id': (2, None),
        'text_message': (3, None),
        'expected_sequence_number': (4, None),
        'delayed_acknowledgment_type': (5, None),
        'error_condition': (6, None),
},
    'PTH': {\
        'action_code': (1, None),
        'pathway_id': (2, None),
        'pathway_instance_id': (3, None),
        'pathway_established_datetime': (4, datetransform),
        'pathway_life_cycle_status': (5, None),
        'change_pathway_life_cycle_status_datetime': (6, datetransform),
},
    'AUT': {\
        'authorizing_payor_plan_id': (1, None),
        'authorizing_payor_company_id': (2, None),
        'authorizing_payor_company_name': (3, None),
        'authorization_effective_date': (4, datetransform),
        'authorization_expiration_date': (5, datetransform),
        'authorization_identifier': (6, None),
        'reimbursement_limit': (7, None),
        'requested_number_of_treatments': (8, None),
        'authorized_number_of_treatments': (9, None),
        'process_date': (10, datetransform),
},
}
