from hl7trans import *
import compositetrans
transforms = {\
    'CTD': {\
        'role': (1, compositetrans.fieldtransformCE),
        'contact_name': (2, compositetrans.fieldtransformXPN),
        'contact_address': (3, compositetrans.fieldtransformXAD),
        'contact_location': (4, compositetrans.fieldtransformPL),
        'contact_communication_information': (5, compositetrans.fieldtransformXTN),
        'preferred_method_of_contact': (6, compositetrans.fieldtransformCE),
        'contact_identifiers': (7, compositetrans.fieldtransformCM),
},
    'PCO': {\
        'office_id_internal': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'classification_id': (3, None),
        'office_manager': (4, compositetrans.fieldtransformXPN),
        'clia_certification_number': (5, None),
        'clia_expiration_date': (6, datetransform),
        'office_review_date': (7, datetransform),
        'is_clia_wavier': (8, None),
        'is_solo': (9, None),
        'is_primary': (10, None),
        'has_handicap_access': (11, None),
        'is_phone_24_hours': (12, None),
        'date_joined': (13, datetransform),
        'address': (14, compositetrans.fieldtransformXAD),
        'phone': (15, compositetrans.fieldtransformXTN),
        'fax': (16, compositetrans.fieldtransformXTN),
        'comment': (17, None),
        'standing_id': (18, None),
        'practicing_specialties': (19, None),
        'office_hours': (20, compositetrans.fieldtransformOH),
        'provider_type': (21, None),
        'line_of_business': (22, None),
        'revised_by': (23, compositetrans.fieldtransformPPN),
        'electronic_claims': (24, None),
        'accepting_patients': (25, None),
        'assistant_present': (26, None),
        'surgery': (27, None),
        'anesthesia_class': (28, None),
        'office_languages': (29, None),
        'agelimitation': (30, None),
        'agecomment': (31, None),
        'confidentialfax': (32, None),
        'billingaddress': (33, compositetrans.fieldtransformXAD),
        'billingphone': (34, compositetrans.fieldtransformXTN),
        'billingfax': (35, compositetrans.fieldtransformXTN),
        'correspondenceaddress': (36, compositetrans.fieldtransformXAD),
        'correspondencephone': (37, compositetrans.fieldtransformXTN),
        'correspondencefax': (38, compositetrans.fieldtransformXTN),
},
    'PCQ': {\
        'question_description': (1, None),
        'response': (2, None),
        'have_documentation': (3, None),
        'comment': (4, None),
        'standing': (5, None),
        'revised_by': (6, compositetrans.fieldtransformPPN),
},
    'AIL': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'location_resource_id': (3, compositetrans.fieldtransformPL),
        'location_type': (4, compositetrans.fieldtransformCE),
        'location_group': (5, compositetrans.fieldtransformCE),
        'start_datetime': (6, datetransform),
        'start_datetime_offset': (7, numtransform),
        'start_datetime_offset_units': (8, compositetrans.fieldtransformCE),
        'duration': (9, numtransform),
        'duration_units': (10, compositetrans.fieldtransformCE),
        'allow_substitution_code': (11, None),
        'filler_status_code': (12, compositetrans.fieldtransformCE),
},
    'RDF': {\
        'number_of_columns_per_row': (1, numtransform),
        'column_description': (2, compositetrans.fieldtransformRCD),
},
    'CSS': {\
        'study_scheduled_time_point': (1, compositetrans.fieldtransformCE),
        'study_scheduled_patient_time_point': (2, datetransform),
        'study_quality_control_codes': (3, compositetrans.fieldtransformCE),
},
    'PSH': {\
        'report_type': (1, None),
        'report_form_identifier': (2, None),
        'report_date': (3, datetransform),
        'report_interval_start_date': (4, datetransform),
        'report_interval_end_date': (5, datetransform),
        'quantity_manufactured': (6, compositetrans.fieldtransformCQ),
        'quantity_distributed': (7, compositetrans.fieldtransformCQ),
        'quantity_distributed_method': (8, None),
        'quantity_distributed_comment': (9, None),
        'quantity_in_use': (10, compositetrans.fieldtransformCQ),
        'quantity_in_use_method': (11, None),
        'quantity_in_use_comment': (12, None),
        'number_of_product_experience_reports_filed_by_facility': (13, numtransform),
        'number_of_product_experience_reports_filed_by_distributor': (14, numtransform),
},
    'GT1': {\
        'set_id': (1, None),
        'guarantor_number': (2, compositetrans.fieldtransformCX),
        'guarantor_name': (3, compositetrans.fieldtransformXPN),
        'guarantor_spouse_name': (4, compositetrans.fieldtransformXPN),
        'guarantor_address': (5, compositetrans.fieldtransformXAD),
        'guarantor_ph_num_home': (6, compositetrans.fieldtransformXTN),
        'guarantor_ph_num_business': (7, compositetrans.fieldtransformXTN),
        'guarantor_datetime_of_birth': (8, datetransform),
        'guarantor_sex': (9, None),
        'guarantor_type': (10, None),
        'guarantor_relationship': (11, None),
        'guarantor_ssn': (12, None),
        'guarantor_date_begin': (13, datetransform),
        'guarantor_date_end': (14, datetransform),
        'guarantor_priority': (15, numtransform),
        'guarantor_employer_name': (16, compositetrans.fieldtransformXPN),
        'guarantor_employer_address': (17, compositetrans.fieldtransformXAD),
        'guarantor_employer_phone_number': (18, compositetrans.fieldtransformXTN),
        'guarantor_employee_id_number': (19, compositetrans.fieldtransformCX),
        'guarantor_employment_status': (20, None),
        'guarantor_organization_name': (21, compositetrans.fieldtransformXON),
        'guarantor_billing_hold_flag': (22, None),
        'guarantor_credit_rating_code': (23, compositetrans.fieldtransformCE),
        'guarantor_death_date_and_time': (24, datetransform),
        'guarantor_death_flag': (25, None),
        'guarantor_charge_adjustment_code': (26, compositetrans.fieldtransformCE),
        'guarantor_household_annual_income': (27, compositetrans.fieldtransformCP),
        'guarantor_household_size': (28, numtransform),
        'guarantor_employer_id_number': (29, compositetrans.fieldtransformCX),
        'guarantor_marital_status_code': (30, None),
        'guarantor_hire_effective_date': (31, datetransform),
        'guarantor_employment_stop_date': (32, datetransform),
        'living_dependency': (33, None),
        'ambulatory_status': (34, None),
        'citizenship': (35, None),
        'primary_language': (36, compositetrans.fieldtransformCE),
        'living_arrangement': (37, None),
        'publicity_indicator': (38, compositetrans.fieldtransformCE),
        'protection_indicator': (39, None),
        'student_indicator': (40, None),
        'religion': (41, None),
        'mothers_maiden_name': (42, compositetrans.fieldtransformXPN),
        'nationality': (43, compositetrans.fieldtransformCE),
        'ethnic_group': (44, None),
        'contact_persons_name': (45, compositetrans.fieldtransformXPN),
        'contact_persons_telephone_number': (46, compositetrans.fieldtransformXTN),
        'contact_reason': (47, compositetrans.fieldtransformCE),
        'contact_relationship': (48, None),
        'job_title': (49, None),
        'job_codeclass': (50, compositetrans.fieldtransformJCC),
        'guarantor_employers_organization_name': (51, compositetrans.fieldtransformXON),
        'handicap': (52, None),
        'job_status': (53, None),
        'guarantor_financial_class': (54, compositetrans.fieldtransformFC),
        'guarantor_race': (55, None),
},
    'FHS': {\
        'file_field_separator': (1, None),
        'file_encoding_characters': (2, None),
        'file_sending_application': (3, None),
        'file_sending_facility': (4, None),
        'file_receiving_application': (5, None),
        'file_receiving_facility': (6, None),
        'file_creation_datetime': (7, datetransform),
        'file_security': (8, None),
        'file_nameid': (9, None),
        'file_header_comment': (10, None),
        'file_control_id': (11, None),
        'reference_file_control_id': (12, None),
},
    'PV2': {\
        'prior_pending_location': (1, compositetrans.fieldtransformPL),
        'accommodation_code': (2, compositetrans.fieldtransformCE),
        'admit_reason': (3, compositetrans.fieldtransformCE),
        'transfer_reason': (4, compositetrans.fieldtransformCE),
        'patient_valuables': (5, None),
        'patient_valuables_location': (6, None),
        'visit_user_code': (7, None),
        'expected_admit_datetime': (8, datetransform),
        'expected_discharge_datetime': (9, datetransform),
        'estimated_length_of_inpatient_stay': (10, numtransform),
        'actual_length_of_inpatient_stay': (11, numtransform),
        'visit_description': (12, None),
        'referral_source_code': (13, compositetrans.fieldtransformXCN),
        'previous_service_date': (14, datetransform),
        'employment_illness_related_indicator': (15, None),
        'purge_status_code': (16, None),
        'purge_status_date': (17, datetransform),
        'special_program_code': (18, None),
        'retention_indicator': (19, None),
        'expected_number_of_insurance_plans': (20, numtransform),
        'visit_publicity_code': (21, None),
        'visit_protection_indicator': (22, None),
        'clinic_organization_name': (23, compositetrans.fieldtransformXON),
        'patient_status_code': (24, None),
        'visit_priority_code': (25, None),
        'previous_treatment_date': (26, datetransform),
        'expected_discharge_disposition': (27, None),
        'signature_on_file_date': (28, datetransform),
        'first_similar_illness_date': (29, datetransform),
        'patient_charge_adjustment_code': (30, None),
        'recurring_service_code': (31, None),
        'billing_media_code': (32, None),
        'expected_surgery_date_time': (33, datetransform),
        'military_partnership_code': (34, None),
        'military_non_availabiltiy_code': (35, None),
        'newborn_baby_indicator': (36, None),
        'baby_detained_indicator': (37, None),
},
    'OBX': {\
        'set_id': (1, None),
        'value_type': (2, None),
        'observation_identifier': (3, compositetrans.fieldtransformCE),
        'observation_sub_id': (4, None),
        'observation_value': (5, None),
        'units': (6, compositetrans.fieldtransformCE),
        'references_range': (7, None),
        'abnormal_flags': (8, None),
        'probability': (9, numtransform),
        'nature_of_abnormal_test': (10, None),
        'observ_result_status': (11, None),
        'date_last_observed_normal_values': (12, datetransform),
        'user_defined_access_checks': (13, None),
        'datetime_of_the_observation': (14, datetransform),
        'producers_id': (15, compositetrans.fieldtransformCE),
        'responsible_observer': (16, compositetrans.fieldtransformXCN),
        'observation_method': (17, compositetrans.fieldtransformCE),
},
    'DRG': {\
        'diagnostic_related_group': (1, compositetrans.fieldtransformCE),
        'drg_assigned_datetime': (2, datetransform),
        'drg_approval_indicator': (3, None),
        'drg_grouper_review_code': (4, None),
        'outlier_type': (5, compositetrans.fieldtransformCE),
        'outlier_days': (6, numtransform),
        'outlier_cost': (7, compositetrans.fieldtransformCP),
        'drg_payor': (8, None),
        'outlier_reimbursement': (9, compositetrans.fieldtransformCP),
        'confidential_indicator': (10, None),
},
    'QRF': {\
        'where_subject_filter': (1, None),
        'when_data_start_datetime': (2, datetransform),
        'when_data_end_datetime': (3, datetransform),
        'what_user_qualifier': (4, None),
        'other_qry_subject_filter': (5, None),
        'which_datetime_qualifier': (6, None),
        'which_datetime_status_qualifier': (7, None),
        'datetime_selection_qualifier': (8, None),
        'when_quantitytiming_qualifier': (9, compositetrans.fieldtransformTQ),
},
    'MFA': {\
        'record_level_event_code': (1, None),
        'mfn_control_id': (2, None),
        'event_completion_datetime': (3, datetransform),
        'error_return_code_andor_text': (4, compositetrans.fieldtransformCE),
        'primary_key_value': (5, compositetrans.fieldtransformCE),
},
    'PCD': {\
        'date_type': (1, None),
        'when': (2, datetransform),
        'comment': (3, None),
        'standing': (4, None),
        'revised_by': (5, compositetrans.fieldtransformPPN),
        'date_reason_code': (6, None),
},
    'OM5': {\
        'sequence_number_test_observation_master_file': (1, numtransform),
        'testobservations_included_wan_ordered_test_battery': (2, compositetrans.fieldtransformCE),
        'observation_id_suffixes': (3, None),
},
    'DSC': {\
        'continuation_pointer': (1, None),
},
    'PID': {\
        'set_id': (1, None),
        'patient_id_external_id': (2, compositetrans.fieldtransformCX),
        'patient_id_internal_id': (3, compositetrans.fieldtransformCX),
        'alternate_patient_id': (4, compositetrans.fieldtransformCX),
        'patient_name': (5, compositetrans.fieldtransformXPN),
        'mothers_maiden_name': (6, compositetrans.fieldtransformXPN),
        'datetime_of_birth': (7, datetransform),
        'sex': (8, None),
        'patient_alias': (9, compositetrans.fieldtransformXPN),
        'race': (10, None),
        'patient_address': (11, compositetrans.fieldtransformXAD),
        'county_code': (12, None),
        'phone_number_home': (13, compositetrans.fieldtransformXTN),
        'phone_number_business': (14, compositetrans.fieldtransformXTN),
        'primary_language': (15, compositetrans.fieldtransformCE),
        'marital_status': (16, None),
        'religion': (17, None),
        'patient_account_number': (18, compositetrans.fieldtransformCX),
        'ssn_number_patient': (19, None),
        'drivers_licence_number_patient': (20, compositetrans.fieldtransformDLN),
        'mothers_identifier': (21, compositetrans.fieldtransformCX),
        'ethnic_group': (22, None),
        'birth_place': (23, None),
        'multiple_birth_indicator': (24, None),
        'birth_order': (25, numtransform),
        'citizenship': (26, None),
        'veterans_military_status': (27, compositetrans.fieldtransformCE),
        'nationalty': (28, compositetrans.fieldtransformCE),
        'patient_death_date_and_time': (29, datetransform),
        'patient_death_indicator': (30, None),
},
    'PEO': {\
        'event_identifiers_used': (1, compositetrans.fieldtransformCE),
        'event_symptomdiagnosis_code': (2, compositetrans.fieldtransformCE),
        'event_onset_datetime': (3, datetransform),
        'event_exacerbation_datetime': (4, datetransform),
        'event_improved_datetime': (5, datetransform),
        'event_ended_datatime': (6, datetransform),
        'event_location_occurred_address': (7, compositetrans.fieldtransformXAD),
        'event_qualification': (8, None),
        'event_serious': (9, None),
        'event_expected': (10, None),
        'event_outcome': (11, None),
        'patient_outcome': (12, None),
        'event_description_from_others': (13, None),
        'event_from_original_reporter': (14, None),
        'event_description_from_patient': (15, None),
        'event_description_from_practitioner': (16, None),
        'event_description_from_autopsy': (17, None),
        'cause_of_death': (18, compositetrans.fieldtransformCE),
        'primary_observer_name': (19, compositetrans.fieldtransformXPN),
        'primary_observer_address': (20, compositetrans.fieldtransformXAD),
        'primary_observer_telephone': (21, compositetrans.fieldtransformXTN),
        'primary_observers_qualification': (22, None),
        'confirmation_provided_by': (23, None),
        'primary_observer_aware_datetime': (24, datetransform),
        'primary_observers_iidentity_may_be_divulged': (25, None),
},
    'PCA': {\
        'affiliation': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'address': (3, compositetrans.fieldtransformXAD),
        'phone': (4, compositetrans.fieldtransformXTN),
        'fax': (5, compositetrans.fieldtransformXTN),
        'revised_by': (6, compositetrans.fieldtransformPPN),
        'comment': (7, None),
        'standing': (8, None),
        'date_joined': (9, datetransform),
},
    'PCB': {\
        'issuer': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'board_certification': (3, None),
        'certificate_number': (4, None),
        'original_effective_date': (5, datetransform),
        'expiration_date': (6, datetransform),
        'last_re_certification_date': (7, datetransform),
        'is_not_specialty': (8, None),
        'is_eligible': (9, None),
        'is_certified': (10, None),
        'board_taken_date': (11, datetransform),
        'board_scheduled_date': (12, datetransform),
        'comment': (13, None),
        'revised_by': (14, compositetrans.fieldtransformPPN),
        'standing': (15, None),
},
    'DB1': {\
        'set_id': (1, None),
        'disabled_person_code': (2, None),
        'disabled_person_identifier': (3, compositetrans.fieldtransformCX),
        'disabled_indicator': (4, None),
        'disability_start_date': (5, datetransform),
        'disability_end_date': (6, datetransform),
        'disability_return_to_work_date': (7, datetransform),
        'disability_unable_to_work_date': (8, datetransform),
},
    'ACC': {\
        'accident_datetime': (1, datetransform),
        'accident_code': (2, compositetrans.fieldtransformCE),
        'accident_location': (3, None),
        'auto_accident_state': (4, compositetrans.fieldtransformCE),
        'accident_job_related_indicator': (5, None),
        'accident_death_indicator': (6, None),
},
    'RF1': {\
        'referral_status': (1, compositetrans.fieldtransformCE),
        'referral_priority': (2, compositetrans.fieldtransformCE),
        'referral_type': (3, compositetrans.fieldtransformCE),
        'referral_disposition': (4, compositetrans.fieldtransformCE),
        'referral_category': (5, compositetrans.fieldtransformCE),
        'originating_referral_identifier': (6, compositetrans.fieldtransformEI),
        'effective_date': (7, datetransform),
        'expiration_date': (8, datetransform),
        'process_date': (9, datetransform),
        'referral_reason': (10, compositetrans.fieldtransformCE),
        'external_referral_identifier': (11, compositetrans.fieldtransformEI),
},
    'NCK': {\
        'system_datetime': (1, datetransform),
},
    'EVN': {\
        'event_type_code': (1, None),
        'recorded_datetime': (2, datetransform),
        'datetime_planned_event': (3, datetransform),
        'event_reason_code': (4, None),
        'operator_id': (5, compositetrans.fieldtransformXCN),
        'event_occurred': (6, datetransform),
},
    'OM4': {\
        'sequence_number_test_observation_master_file': (1, numtransform),
        'derived_specimen': (2, None),
        'container_description': (3, None),
        'container_volume': (4, numtransform),
        'container_units': (5, compositetrans.fieldtransformCE),
        'specimen': (6, compositetrans.fieldtransformCE),
        'additive': (7, compositetrans.fieldtransformCE),
        'preparation': (8, None),
        'special_handling_requirements': (9, None),
        'normal_collection_volume': (10, compositetrans.fieldtransformCQ),
        'minimum_collection_volume': (11, compositetrans.fieldtransformCQ),
        'specimen_requirements': (12, None),
        'specimen_priorities': (13, None),
        'specimen_retention_time': (14, compositetrans.fieldtransformCQ),
},
    'PCS': {\
        'informant': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'sanction_type': (3, None),
        'dates': (4, compositetrans.fieldtransformDR),
        'license_number': (5, None),
        'license_type': (6, None),
        'state': (7, None),
        'detail_holder': (8, compositetrans.fieldtransformXON),
        'comment': (9, None),
        'standing': (10, None),
        'revised_by': (11, compositetrans.fieldtransformPPN),
},
    'NTE': {\
        'set_id': (1, None),
        'source_of_comment': (2, None),
        'comment': (3, None),
},
    'AIS': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'universal_service_id': (3, compositetrans.fieldtransformCE),
        'start_datetime': (4, datetransform),
        'start_datetime_offset': (5, numtransform),
        'start_datetime_offset_units': (6, compositetrans.fieldtransformCE),
        'duration': (7, numtransform),
        'duration_units': (8, compositetrans.fieldtransformCE),
        'allow_substitution_code': (9, None),
        'filler_status_code': (10, compositetrans.fieldtransformCE),
},
    'PRA': {\
        'primary_key_value': (1, None),
        'practioner_group': (2, compositetrans.fieldtransformCE),
        'practioner_category': (3, None),
        'provider_billing': (4, None),
        'specialty': (5, compositetrans.fieldtransformCM),
        'practitioner_id_numbers': (6, compositetrans.fieldtransformCM),
        'privileges': (7, compositetrans.fieldtransformCM),
        'date_entered_practice': (8, datetransform),
},
    'RXG': {\
        'give_sub_id_counter': (1, numtransform),
        'dispense_sub_id': (2, numtransform),
        'quantitytiming': (3, compositetrans.fieldtransformTQ),
        'give_code': (4, compositetrans.fieldtransformCE),
        'give_amount_minimum': (5, numtransform),
        'give_amount_maximum': (6, numtransform),
        'give_units': (7, compositetrans.fieldtransformCE),
        'give_dosage_form': (8, compositetrans.fieldtransformCE),
        'administration_notes': (9, compositetrans.fieldtransformCE),
        'substitution_status': (10, None),
        'dispense_to_location': (11, compositetrans.fieldtransformCM),
        'needs_human_review': (12, None),
        'pharmacytreatment_suppliers_special_administration_instructions': (13, compositetrans.fieldtransformCE),
        'give_per_time_unit': (14, None),
        'give_rate_amount': (15, None),
        'give_rate_units': (16, compositetrans.fieldtransformCE),
        'give_strength': (17, numtransform),
        'give_strength_units': (18, compositetrans.fieldtransformCE),
        'substance_lot_number': (19, None),
        'substance_expiration_date': (20, datetransform),
        'substance_manufacturer_name': (21, compositetrans.fieldtransformCE),
        'indication': (22, compositetrans.fieldtransformCE),
},
    'PCV': {\
        'verified_date': (1, datetransform),
        'verified_by': (2, None),
        'expiration_date': (3, datetransform),
        'verification_medium': (4, None),
        'comment': (5, None),
        'verification_standing': (6, None),
        'revised_by': (7, compositetrans.fieldtransformPPN),
},
    'MRG': {\
        'prior_patient_id_internal': (1, compositetrans.fieldtransformCX),
        'prior_alternate_patient_id': (2, compositetrans.fieldtransformCX),
        'prior_patient_account_number': (3, compositetrans.fieldtransformCX),
        'prior_patient_id_external': (4, compositetrans.fieldtransformCX),
        'prior_visit_number': (5, compositetrans.fieldtransformCX),
        'prior_alternate_visit_id': (6, compositetrans.fieldtransformCX),
        'prior_patient_name': (7, compositetrans.fieldtransformXPN),
},
    'VAR': {\
        'variance_instance_id': (1, compositetrans.fieldtransformEI),
        'documented_datetime': (2, datetransform),
        'stated_variance_datetime': (3, datetransform),
        'variance_originator': (4, compositetrans.fieldtransformXCN),
        'variance_classification': (5, compositetrans.fieldtransformCE),
        'variance_description': (6, None),
},
    'RXC': {\
        'rx_component_type': (1, None),
        'component_code': (2, compositetrans.fieldtransformCE),
        'component_amount': (3, numtransform),
        'component_units': (4, compositetrans.fieldtransformCE),
        'component_strength': (5, numtransform),
        'component_strength_units': (6, compositetrans.fieldtransformCE),
},
    'ODT': {\
        'tray_type': (1, compositetrans.fieldtransformCE),
        'service_period': (2, compositetrans.fieldtransformCE),
        'text_instruction': (3, None),
},
    'CM2': {\
        'set_id': (1, None),
        'scheduled_time_point': (2, compositetrans.fieldtransformCE),
        'description_of_time_point': (3, None),
        'events_scheduled_this_time_point': (4, compositetrans.fieldtransformCE),
},
    'CSR': {\
        'sponsor_study_id': (1, compositetrans.fieldtransformEI),
        'alternate_study_id': (2, compositetrans.fieldtransformEI),
        'institution_registering_the_patient': (3, compositetrans.fieldtransformCE),
        'sponsor_patient_id': (4, compositetrans.fieldtransformCX),
        'alternate_patient_id': (5, compositetrans.fieldtransformCX),
        'datetime_of_patient_study_registration': (6, datetransform),
        'person_performing_study_registration': (7, compositetrans.fieldtransformXCN),
        'study_authorizing_provider': (8, compositetrans.fieldtransformXCN),
        'datetime_patient_study_consent_signed': (9, datetransform),
        'patient_study_eligibility_status': (10, compositetrans.fieldtransformCE),
        'study_randomization_datetime': (11, datetransform),
        'randomized_study_arm': (12, compositetrans.fieldtransformCE),
        'stratum_for_study_randomization': (13, compositetrans.fieldtransformCE),
        'patient_evaluability_status': (14, compositetrans.fieldtransformCE),
        'datetime_ended_study': (15, datetransform),
        'reason_ended_study': (16, compositetrans.fieldtransformCE),
},
    'PES': {\
        'sender_organization_name': (1, compositetrans.fieldtransformXON),
        'sender_individual_name': (2, compositetrans.fieldtransformXCN),
        'sender_address': (3, compositetrans.fieldtransformXAD),
        'sender_telephone': (4, compositetrans.fieldtransformXTN),
        'sender_event_identifier': (5, compositetrans.fieldtransformEI),
        'sender_sequence_number': (6, numtransform),
        'sender_event_description': (7, None),
        'sender_comment': (8, None),
        'sender_aware_datetme': (9, datetransform),
        'event_report_date': (10, datetransform),
        'event_report_timingtype': (11, None),
        'event_report_source': (12, None),
        'event_reported_to': (13, None),
},
    'LCC': {\
        'primary_key_value': (1, compositetrans.fieldtransformPL),
        'location_department': (2, None),
        'accommodation_type': (3, compositetrans.fieldtransformCE),
        'charge_code': (4, compositetrans.fieldtransformCE),
},
    'QAK': {\
        'query_tag': (1, None),
        'query_response_status': (2, None),
},
    'SCH': {\
        'placer_appointment_id': (1, compositetrans.fieldtransformEI),
        'filler_appointment_id': (2, compositetrans.fieldtransformEI),
        'occurrence_number': (3, numtransform),
        'placer_group_number': (4, compositetrans.fieldtransformEI),
        'schedule_id': (5, compositetrans.fieldtransformCE),
        'event_reason': (6, compositetrans.fieldtransformCE),
        'appointment_reason': (7, compositetrans.fieldtransformCE),
        'appointment_type': (8, compositetrans.fieldtransformCE),
        'appointment_duration': (9, numtransform),
        'appointment_duration_units': (10, compositetrans.fieldtransformCE),
        'appointment_timing_quantity': (11, compositetrans.fieldtransformTQ),
        'placer_contact_person': (12, compositetrans.fieldtransformXCN),
        'placer_contact_phone_number': (13, compositetrans.fieldtransformXTN),
        'placer_contact_address': (14, compositetrans.fieldtransformXAD),
        'placer_contact_location': (15, compositetrans.fieldtransformPL),
        'filler_contact_person': (16, compositetrans.fieldtransformXCN),
        'filler_contact_phone_number': (17, compositetrans.fieldtransformXTN),
        'filler_contact_address': (18, compositetrans.fieldtransformXAD),
        'filler_contact_location': (19, compositetrans.fieldtransformPL),
        'entered_by_person': (20, compositetrans.fieldtransformXCN),
        'entered_by_phone_number': (21, compositetrans.fieldtransformXTN),
        'entered_by_location': (22, compositetrans.fieldtransformPL),
        'parent_placer_appointment_id': (23, compositetrans.fieldtransformEI),
        'parent_filler_appointment_id': (24, compositetrans.fieldtransformEI),
        'filler_status_code': (25, compositetrans.fieldtransformCE),
},
    'STA': {\
        'question_id': (1, compositetrans.fieldtransformCX),
        'response': (2, None),
        'have_documentation': (3, None),
        'comment': (4, None),
        'standing': (5, None),
        'revised_by': (6, compositetrans.fieldtransformPPN),
},
    'MFE': {\
        'record_level_event_code': (1, None),
        'mfn_control_id': (2, None),
        'effective_datetime': (3, datetransform),
        'primary_key_value': (4, None),
},
    'PCM': {\
        'issuer': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'insuree': (3, compositetrans.fieldtransformXON),
        'policy_number': (4, None),
        'insurance_type': (5, None),
        'effective_dates': (6, compositetrans.fieldtransformDR),
        'retroactive_date': (7, datetransform),
        'aggregate_limit': (8, compositetrans.fieldtransformMO),
        'claim_limit': (9, compositetrans.fieldtransformMO),
        'umbrella_limit': (10, compositetrans.fieldtransformMO),
        'is_certificate_holder': (11, None),
        'year_with': (12, datetransform),
        'address': (13, compositetrans.fieldtransformXAD),
        'phone': (14, compositetrans.fieldtransformXTN),
        'revised_by': (15, compositetrans.fieldtransformPPN),
        'comment': (16, None),
        'standing': (17, None),
},
    'ERQ': {\
        'query_tag': (1, None),
        'event_identifier': (2, compositetrans.fieldtransformCE),
        'input_parameter_list': (3, compositetrans.fieldtransformQIP),
},
    'CDM': {\
        'primary_key_value': (1, compositetrans.fieldtransformCE),
        'charge_code_alias': (2, compositetrans.fieldtransformCE),
        'charge_description_short': (3, None),
        'charge_description_long': (4, None),
        'description_override_indicator': (5, None),
        'exploding_charges': (6, compositetrans.fieldtransformCE),
        'procedure_code': (7, compositetrans.fieldtransformCE),
        'activeinactive_indicator': (8, None),
        'inventory_number': (9, compositetrans.fieldtransformCE),
        'resource_load': (10, numtransform),
        'contract_number': (11, compositetrans.fieldtransformCK),
        'contract_organization': (12, compositetrans.fieldtransformXON),
        'room_fee_indicator': (13, None),
},
    'RXA': {\
        'give_sub_id_counter': (1, numtransform),
        'administration_sub_id_counter': (2, numtransform),
        'datetime_start_of_administration': (3, datetransform),
        'datetime_end_of_administration': (4, datetransform),
        'administered_code': (5, compositetrans.fieldtransformCE),
        'administered_amount': (6, numtransform),
        'administered_units': (7, compositetrans.fieldtransformCE),
        'administered_dosage_form': (8, compositetrans.fieldtransformCE),
        'administration_notes': (9, compositetrans.fieldtransformCE),
        'administering_provider': (10, compositetrans.fieldtransformXCN),
        'administered_at_location': (11, compositetrans.fieldtransformCM),
        'administered_per_time_unit': (12, None),
        'administered_strength': (13, numtransform),
        'administered_strength_units': (14, compositetrans.fieldtransformCE),
        'substance_lot_number': (15, None),
        'substance_expiration_date': (16, datetransform),
        'substance_manufacturer_name': (17, compositetrans.fieldtransformCE),
        'substance_refusal_reason': (18, compositetrans.fieldtransformCE),
        'indication': (19, compositetrans.fieldtransformCE),
        'completion_status': (20, None),
        'action_code': (21, None),
        'system_entry_datetime': (22, datetransform),
},
    'DSP': {\
        'set_id': (1, None),
        'display_level': (2, None),
        'data_line': (3, None),
        'logical_break_point': (4, None),
        'result_id': (5, None),
},
    'AIP': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'personnel_resource_id': (3, compositetrans.fieldtransformXCN),
        'resource_role': (4, compositetrans.fieldtransformCE),
        'resource_group': (5, compositetrans.fieldtransformCE),
        'start_datetime': (6, datetransform),
        'start_datetime_offset': (7, numtransform),
        'start_datetime_offset_units': (8, compositetrans.fieldtransformCE),
        'duration': (9, numtransform),
        'duration_units': (10, compositetrans.fieldtransformCE),
        'allow_substitution_code': (11, None),
        'filler_status_code': (12, compositetrans.fieldtransformCE),
},
    'ARQ': {\
        'placer_appointment_id': (1, compositetrans.fieldtransformEI),
        'filler_appointment_id': (2, compositetrans.fieldtransformEI),
        'occurrence_number': (3, numtransform),
        'placer_group_number': (4, compositetrans.fieldtransformEI),
        'schedule_id': (5, compositetrans.fieldtransformCE),
        'request_event_reason': (6, compositetrans.fieldtransformCE),
        'appointment_reason': (7, compositetrans.fieldtransformCE),
        'appointment_type': (8, compositetrans.fieldtransformCE),
        'appointment_duration': (9, numtransform),
        'appointment_duration_units': (10, compositetrans.fieldtransformCE),
        'requested_start_datetime_range': (11, compositetrans.fieldtransformDR),
        'priority': (12, None),
        'repeating_interval': (13, compositetrans.fieldtransformRI),
        'repeating_interval_duration': (14, None),
        'placer_contact_person': (15, compositetrans.fieldtransformXCN),
        'placer_contact_phone_number': (16, compositetrans.fieldtransformXTN),
        'placer_contact_address': (17, compositetrans.fieldtransformXAD),
        'placer_contact_location': (18, compositetrans.fieldtransformPL),
        'entered_by_person': (19, compositetrans.fieldtransformXCN),
        'entered_by_phone_number': (20, compositetrans.fieldtransformXTN),
        'entered_by_location': (21, compositetrans.fieldtransformPL),
        'parent_placer_appointment_id': (22, compositetrans.fieldtransformEI),
        'parent_filler_appointment_id': (23, compositetrans.fieldtransformEI),
},
    'STI': {\
        'subject_id_internal': (1, compositetrans.fieldtransformXON),
        'definition_id_internal': (2, compositetrans.fieldtransformCX),
        'location_id_internal': (3, compositetrans.fieldtransformXON),
        'dates': (4, compositetrans.fieldtransformDR),
        'address': (5, compositetrans.fieldtransformXAD),
        'phone': (6, compositetrans.fieldtransformXTN),
        'fax': (7, compositetrans.fieldtransformXTN),
        'email': (8, compositetrans.fieldtransformXTN),
        'comment': (9, None),
        'standing_id': (10, None),
        'complete_id': (11, None),
        'revised_by': (12, compositetrans.fieldtransformPPN),
        'transcode': (13, None),
        'performed_by': (14, None),
},
    'UB1': {\
        'set_id': (1, None),
        'blood_deductible_43': (2, numtransform),
        'blood_furnished_pints_of_40': (3, numtransform),
        'blood_replaced_pints_41': (4, numtransform),
        'blood_not_replaced_pints42': (5, numtransform),
        'co_insurance_days_25': (6, numtransform),
        'condition_code_35_39': (7, None),
        'covered_days_23': (8, numtransform),
        'non_covered_days_24': (9, numtransform),
        'value_amount_code_46_49': (10, compositetrans.fieldtransformCM),
        'number_of_grace_days_90': (11, numtransform),
        'spec_program_indicator_44': (12, compositetrans.fieldtransformCE),
        'psrour_approval_indicator_87': (13, compositetrans.fieldtransformCE),
        'psrour_approved_stay_fm_88': (14, datetransform),
        'psrour_approved_stay_to_89': (15, datetransform),
        'occurrence_28_32': (16, compositetrans.fieldtransformCM),
        'occurrence_span_33': (17, compositetrans.fieldtransformCE),
        'occur_span_start_date33': (18, datetransform),
        'occur_span_end_date_33': (19, datetransform),
        'ub_82_locator_2': (20, None),
        'ub_82_locator_9': (21, None),
        'ub_82_locator_27': (22, None),
        'ub_82_locator_45': (23, None),
},
    'MSH': {\
        'field_separator': (0, None),
        'encoding_characters': (1, None),
        'sending_application': (2, compositetrans.fieldtransformEI),
        'sending_facility': (3, compositetrans.fieldtransformEI),
        'receiving_application': (4, compositetrans.fieldtransformEI),
        'receiving_facility': (5, compositetrans.fieldtransformEI),
        'datetime_of_message': (6, datetransform),
        'security': (7, None),
        'message_type': (8, compositetrans.fieldtransformCM_MSH),
        'message_control_id': (9, None),
        'processing_id': (10, compositetrans.fieldtransformPT),
        'version_id': (11, None),
        'sequence_number': (12, numtransform),
        'continuation_pointer': (13, None),
        'accept_acknowledgement_type': (14, None),
        'application_acknowledgement_type': (15, None),
        'country_code': (16, None),
        'character_set': (17, None),
        'principal_language_of_message': (18, compositetrans.fieldtransformCE),
},
    'RQ1': {\
        'anticipated_price': (1, None),
        'manufacturer_id': (2, compositetrans.fieldtransformCE),
        'manufacturers_catalog': (3, None),
        'vendor_id': (4, compositetrans.fieldtransformCE),
        'vendor_catalog': (5, None),
        'taxable': (6, None),
        'substitute_allowed': (7, None),
},
    'SDD': {\
        'designid': (1, compositetrans.fieldtransformCX),
        'definitionid': (2, compositetrans.fieldtransformCX),
        'studytypeid': (3, compositetrans.fieldtransformCX),
        'questionid': (4, compositetrans.fieldtransformCX),
        'categoryid': (5, compositetrans.fieldtransformCX),
        'parent': (6, compositetrans.fieldtransformCX),
        'sequence': (7, numtransform),
        'revisedby': (8, compositetrans.fieldtransformPPN),
},
    'BHS': {\
        'batch_field_separator': (1, None),
        'batch_encoding_characters': (2, None),
        'batch_sending_application': (3, None),
        'batch_sending_facility': (4, None),
        'batch_receiving_application': (5, None),
        'batch_receiving_facility': (6, None),
        'batch_creation_datetime': (7, datetransform),
        'batch_security': (8, None),
        'batch_nameidtype': (9, None),
        'batch_comment': (10, None),
        'batch_control_id': (11, None),
        'reference_batch_control_id': (12, None),
},
    'PV1': {\
        'set_id': (1, None),
        'patient_class': (2, None),
        'assigned_patient_location': (3, compositetrans.fieldtransformPL),
        'admission_type': (4, None),
        'preadmit_number': (5, compositetrans.fieldtransformCX),
        'prior_patient_location': (6, compositetrans.fieldtransformPL),
        'attending_doctor': (7, compositetrans.fieldtransformXCN),
        'referring_doctor': (8, compositetrans.fieldtransformXCN),
        'consulting_doctor': (9, compositetrans.fieldtransformXCN),
        'hospital_service': (10, None),
        'temporary_location': (11, compositetrans.fieldtransformPL),
        'preadmit_test_indicator': (12, None),
        'readmission_indicator': (13, None),
        'admit_source': (14, None),
        'ambulatory_status': (15, None),
        'vip_indicator': (16, None),
        'admitting_doctor': (17, compositetrans.fieldtransformXCN),
        'patient_type': (18, None),
        'visit_number': (19, compositetrans.fieldtransformCX),
        'financial_class': (20, compositetrans.fieldtransformFC),
        'charge_price_indicator': (21, None),
        'courtesy_code': (22, None),
        'credit_rating': (23, None),
        'contract_code': (24, None),
        'contract_effective_date': (25, datetransform),
        'contract_amount': (26, numtransform),
        'contract_period': (27, numtransform),
        'interest_code': (28, None),
        'transfer_to_bad_debt_code': (29, None),
        'transfer_to_bad_debt_date': (30, datetransform),
        'bad_debt_agency_code': (31, None),
        'bad_debt_transfer_amount': (32, numtransform),
        'bad_debt_recovery_amount': (33, numtransform),
        'delete_account_indicator': (34, None),
        'delete_account_date': (35, datetransform),
        'discharge_disposition': (36, None),
        'discharged_to_location': (37, compositetrans.fieldtransformCM),
        'diet_type': (38, None),
        'servicing_facility': (39, None),
        'bed_status': (40, None),
        'account_status': (41, None),
        'pending_location': (42, compositetrans.fieldtransformPL),
        'prior_temporary_location': (43, compositetrans.fieldtransformPL),
        'admit_datetime': (44, datetransform),
        'discharge_datetime': (45, datetransform),
        'current_patient_balance': (46, numtransform),
        'total_charges': (47, numtransform),
        'total_adjustments': (48, numtransform),
        'total_payments': (49, numtransform),
        'alternate_visit_id': (50, compositetrans.fieldtransformCX),
        'visit_indicator': (51, None),
        'other_healthcare_provider': (52, compositetrans.fieldtransformXCN),
},
    'RQD': {\
        'requisition_line_number': (1, None),
        'item_code_internal': (2, compositetrans.fieldtransformCE),
        'item_code_external': (3, compositetrans.fieldtransformCE),
        'hospital_item_code': (4, compositetrans.fieldtransformCE),
        'requisition_quantity': (5, numtransform),
        'requisition_unit_of_measure': (6, compositetrans.fieldtransformCE),
        'dept_cost_center': (7, None),
        'item_natural_account_code': (8, None),
        'deliver_to_id': (9, compositetrans.fieldtransformCE),
        'date_needed': (10, datetransform),
},
    'NPU': {\
        'bed_location': (1, compositetrans.fieldtransformPL),
        'bed_status': (2, None),
},
    'PCR': {\
        'reference': (1, compositetrans.fieldtransformXCN),
        'external_id': (2, compositetrans.fieldtransformCX),
        'position': (3, None),
        'description': (4, None),
        'is_board_certified': (5, None),
        'address': (6, compositetrans.fieldtransformXAD),
        'phone': (7, compositetrans.fieldtransformXTN),
        'specialty': (8, None),
        'revised_by': (9, compositetrans.fieldtransformPPN),
        'comment': (10, None),
        'standing': (11, None),
},
    'CM0': {\
        'set_id': (1, None),
        'sponsor_study_id': (2, compositetrans.fieldtransformEI),
        'alternate_study_id': (3, compositetrans.fieldtransformEI),
        'title_of_study': (4, None),
        'chairman_of_study': (5, compositetrans.fieldtransformXCN),
        'last_irb_approval_date': (6, datetransform),
        'total_accrual_to_date': (7, numtransform),
        'last_accrual_date': (8, datetransform),
        'contact_for_study': (9, compositetrans.fieldtransformXCN),
        'contacts_tel_number': (10, compositetrans.fieldtransformXTN),
        'contacts_address': (11, compositetrans.fieldtransformXAD),
},
    'PRC': {\
        'primary_key_value': (1, compositetrans.fieldtransformCE),
        'facility_id': (2, compositetrans.fieldtransformCE),
        'department': (3, compositetrans.fieldtransformCE),
        'valid_patient_classes': (4, None),
        'price': (5, compositetrans.fieldtransformCP),
        'formula': (6, None),
        'minimum_quantity': (7, numtransform),
        'maximum_quantity': (8, numtransform),
        'minimum_price': (9, compositetrans.fieldtransformMO),
        'maximum_price': (10, compositetrans.fieldtransformMO),
        'effective_start_date': (11, datetransform),
        'effective_end_date': (12, datetransform),
        'price_override_flag': (13, None),
        'billing_category': (14, compositetrans.fieldtransformCE),
        'chargeable_flag': (15, None),
        'activeinactive_flag': (16, None),
        'cost': (17, compositetrans.fieldtransformMO),
        'charge_on_indicator': (18, None),
},
    'IN3': {\
        'set_id': (1, None),
        'certification_number': (2, compositetrans.fieldtransformCX),
        'certified_by': (3, compositetrans.fieldtransformXCN),
        'certification_required': (4, None),
        'penalty': (5, compositetrans.fieldtransformCM),
        'certification_datetime': (6, datetransform),
        'certification_modify_datetime': (7, datetransform),
        'operator': (8, compositetrans.fieldtransformXCN),
        'certification_begin_date': (9, datetransform),
        'certification_end_date': (10, datetransform),
        'days': (11, compositetrans.fieldtransformCM),
        'non_concur_codedescription': (12, compositetrans.fieldtransformCE),
        'non_concur_effective_datetime': (13, datetransform),
        'physician_reviewer': (14, compositetrans.fieldtransformXCN),
        'certification_contact': (15, None),
        'certification_contact_phone_number': (16, compositetrans.fieldtransformXTN),
        'appeal_reason': (17, compositetrans.fieldtransformCE),
        'certification_agency': (18, compositetrans.fieldtransformCE),
        'certification_agency_phone_number': (19, compositetrans.fieldtransformXTN),
        'pre_certification_reqwindow': (20, compositetrans.fieldtransformCM),
        'case_manager': (21, None),
        'second_opinion_date': (22, datetransform),
        'second_opinion_status': (23, None),
        'second_opinion_documentation_received': (24, None),
        'second_opinion_physician': (25, compositetrans.fieldtransformXCN),
},
    'BTS': {\
        'batch_message_count': (1, None),
        'batch_comment': (2, None),
        'batch_totals': (3, numtransform),
},
    'RGS': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'resource_group_id': (3, compositetrans.fieldtransformCE),
},
    'OBR': {\
        'set_id': (1, None),
        'placer_order_number': (2, compositetrans.fieldtransformEI),
        'filler_order_number': (3, compositetrans.fieldtransformEI),
        'universal_service_id': (4, compositetrans.fieldtransformCE),
        'priority': (5, None),
        'requested_datetime': (6, datetransform),
        'observation_datetime': (7, datetransform),
        'observation_end_datetime': (8, datetransform),
        'collection_volume': (9, compositetrans.fieldtransformCQ),
        'collector_identifier': (10, compositetrans.fieldtransformXCN),
        'specimen_action_code': (11, None),
        'danger_code': (12, compositetrans.fieldtransformCE),
        'relevant_clinical_info': (13, None),
        'specimen_received_datetime': (14, datetransform),
        'specimen_source': (15, compositetrans.fieldtransformCM),
        'ordering_provider': (16, compositetrans.fieldtransformXCN),
        'order_callback_phone_number': (17, compositetrans.fieldtransformXTN),
        'placer_field_1': (18, None),
        'placer_field_2': (19, None),
        'filler_field_1': (20, None),
        'filler_field_2': (21, None),
        'results_rptstatus_chng_datetime': (22, datetransform),
        'charge_to_practice': (23, compositetrans.fieldtransformCM),
        'diagnostic_serv_sect_id': (24, None),
        'result_status': (25, None),
        'parent_result': (26, compositetrans.fieldtransformCM),
        'quantitytiming': (27, compositetrans.fieldtransformTQ),
        'result_copies_to': (28, compositetrans.fieldtransformXCN),
        'parent_number': (29, compositetrans.fieldtransformCM),
        'transportation_mode': (30, None),
        'reason_for_study': (31, compositetrans.fieldtransformCE),
        'principal_result_interpreter': (32, compositetrans.fieldtransformCM),
        'assistant_result_interpreter': (33, compositetrans.fieldtransformCM),
        'technician': (34, compositetrans.fieldtransformCM),
        'transcriptionist': (35, compositetrans.fieldtransformCM),
        'scheduled_datetime': (36, datetransform),
        'number_of_sample_containers': (37, numtransform),
        'transport_logistics_of_collected_sample': (38, compositetrans.fieldtransformCE),
        'collectors_comment': (39, compositetrans.fieldtransformCE),
        'transport_arrangement_responsibility': (40, compositetrans.fieldtransformCE),
        'transport_arranged': (41, None),
        'escort_required': (42, None),
        'planned_patient_transport_comment': (43, compositetrans.fieldtransformCE),
},
    'PR1': {\
        'set_id': (1, None),
        'procedure_coding_method': (2, None),
        'procedure_code': (3, compositetrans.fieldtransformCE),
        'procedure_description': (4, None),
        'procedure_datetime': (5, datetransform),
        'procedure_functional_type': (6, None),
        'procedure_minutes': (7, numtransform),
        'anesthesiologist': (8, compositetrans.fieldtransformXCN),
        'anesthesia_code': (9, None),
        'anesthesia_minutes': (10, numtransform),
        'surgeon': (11, compositetrans.fieldtransformXCN),
        'procedure_practitioner': (12, compositetrans.fieldtransformXCN),
        'consent_code': (13, compositetrans.fieldtransformCE),
        'procedure_priority': (14, numtransform),
        'associated_diagnosis_code': (15, compositetrans.fieldtransformCE),
},
    'AIG': {\
        'set_id': (1, None),
        'segment_action_code': (2, None),
        'resource_id': (3, compositetrans.fieldtransformCE),
        'resource_type': (4, compositetrans.fieldtransformCE),
        'resource_group': (5, compositetrans.fieldtransformCE),
        'resource_quantity': (6, numtransform),
        'resource_quantity_units': (7, compositetrans.fieldtransformCE),
        'start_datetime': (8, datetransform),
        'start_datetime_offset': (9, numtransform),
        'start_datetime_offset_units': (10, compositetrans.fieldtransformCE),
        'duration': (11, numtransform),
        'duration_units': (12, compositetrans.fieldtransformCE),
        'allow_substitution_code': (13, None),
        'filler_status_code': (14, compositetrans.fieldtransformCE),
},
    'PCC': {\
        'party': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'description': (3, None),
        'nature': (4, None),
        'size': (5, None),
        'conflict': (6, None),
        'address': (7, compositetrans.fieldtransformXAD),
        'phone': (8, compositetrans.fieldtransformXTN),
        'comment': (9, None),
        'standing': (10, None),
        'revised_by': (11, compositetrans.fieldtransformPPN),
},
    'FTS': {\
        'file_batch_count': (1, numtransform),
        'file_trailer_comment': (2, None),
},
    'STF': {\
        'primary_key_value': (1, compositetrans.fieldtransformCE),
        'staff_id_code': (2, compositetrans.fieldtransformCX),
        'staff_name': (3, compositetrans.fieldtransformXPN),
        'staff_type': (4, None),
        'sex': (5, None),
        'datetime_of_birth': (6, datetransform),
        'activeinactive_flag': (7, None),
        'department': (8, compositetrans.fieldtransformCE),
        'service': (9, compositetrans.fieldtransformCE),
        'phone': (10, compositetrans.fieldtransformXTN),
        'officehome_address': (11, compositetrans.fieldtransformXAD),
        'activation_date': (12, compositetrans.fieldtransformCM),
        'inactivation_date': (13, compositetrans.fieldtransformCM),
        'backup_person_id': (14, compositetrans.fieldtransformCE),
        'e_mail_address': (15, None),
        'preferred_method_of_contact': (16, compositetrans.fieldtransformCE),
        'marital_status': (17, None),
        'job_title': (18, None),
        'job_codeclass': (19, compositetrans.fieldtransformJCC),
        'employment_status': (20, None),
        'additional_insured_on_auto': (21, None),
        'drivers_license_number_staff': (22, compositetrans.fieldtransformDLN),
        'copy_auto_ins': (23, None),
        'auto_ins_expires': (24, datetransform),
        'date_last_dmv_review': (25, datetransform),
        'date_next_dmv_review': (26, datetransform),
},
    'RXE': {\
        'quantitytiming': (1, compositetrans.fieldtransformTQ),
        'give_code': (2, compositetrans.fieldtransformCE),
        'give_amount_minimum': (3, numtransform),
        'give_amount_maximum': (4, numtransform),
        'give_units': (5, compositetrans.fieldtransformCE),
        'give_dosage_form': (6, compositetrans.fieldtransformCE),
        'providers_administration_instructions': (7, compositetrans.fieldtransformCE),
        'deliver_to_location': (8, compositetrans.fieldtransformCM),
        'substitution_status': (9, None),
        'dispense_amount': (10, numtransform),
        'dispense_units': (11, compositetrans.fieldtransformCE),
        'number_of_refills': (12, numtransform),
        'ordering_providers_dea_number': (13, compositetrans.fieldtransformXCN),
        'pharmacisttreatment_suppliers_verifier_id': (14, compositetrans.fieldtransformXCN),
        'prescription_number': (15, None),
        'number_of_refills_remaining': (16, numtransform),
        'number_of_refillsdoses_dispensed': (17, numtransform),
        'dt_of_most_recent_refill_or_dose_dispensed': (18, datetransform),
        'total_daily_dose': (19, compositetrans.fieldtransformCQ),
        'needs_human_review': (20, None),
        'pharmacytreatment_suppliers_special_dispensing_instructions': (21, compositetrans.fieldtransformCE),
        'give_per_time_unit': (22, None),
        'give_rate_amount': (23, None),
        'give_rate_units': (24, compositetrans.fieldtransformCE),
        'give_strength': (25, numtransform),
        'give_strength_units': (26, compositetrans.fieldtransformCE),
        'give_indication': (27, compositetrans.fieldtransformCE),
        'dispense_package_size': (28, numtransform),
        'dispense_package_size_unit': (29, compositetrans.fieldtransformCE),
        'dispense_package_method': (30, None),
},
    'PCL': {\
        'license_issuer': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'license_number': (3, None),
        'license_type': (4, None),
        'state': (5, None),
        'expiration_date': (6, datetransform),
        'in_force': (7, None),
        'is_original': (8, None),
        'supervision_required': (9, None),
        'practice_under_other_provider': (10, None),
        'initial_license_date': (11, datetransform),
        'current_license_date': (12, datetransform),
        'is_restricted': (13, None),
        'drug_schedule': (14, None),
        'upin': (15, None),
        'revised_by': (16, compositetrans.fieldtransformPPN),
        'comment': (17, None),
        'standing': (18, None),
},
    'VTQ': {\
        'query_tag': (1, None),
        'query_response_format_code': (2, None),
        'vt_query_name': (3, compositetrans.fieldtransformCE),
        'virtual_table_name': (4, compositetrans.fieldtransformCE),
        'selection_criteria': (5, compositetrans.fieldtransformQSC),
},
    'PCT': {\
        'school': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'address': (3, compositetrans.fieldtransformXAD),
        'phone': (4, compositetrans.fieldtransformXTN),
        'fax': (5, compositetrans.fieldtransformXTN),
        'contact': (6, None),
        'ama_school_code': (7, None),
        'education_type': (8, None),
        'education_category': (9, None),
        'enter_date': (10, datetransform),
        'graduation_date': (11, datetransform),
        'ecfmg_code': (12, None),
        'ecfmg_effective_date': (13, datetransform),
        'ecfmg_expiration_date': (14, datetransform),
        'revised_by': (15, compositetrans.fieldtransformPPN),
        'comment': (16, None),
        'standing': (17, None),
        'completed': (18, numtransform),
},
    'OM6': {\
        'sequence_number_test_observation_master_file': (1, numtransform),
        'derivation_rule': (2, None),
},
    'URD': {\
        'ru_datetime': (1, datetransform),
        'report_priority': (2, None),
        'ru_who_subject_definition': (3, compositetrans.fieldtransformXCN),
        'ru_what_subject_definition': (4, compositetrans.fieldtransformCE),
        'ru_what_department_code': (5, compositetrans.fieldtransformCE),
        'ru_displayprint_locations': (6, None),
        'ru_results_level': (7, None),
},
    'FAC': {\
        'facility_id': (1, compositetrans.fieldtransformEI),
        'facility_type': (2, None),
        'facility_address': (3, compositetrans.fieldtransformXAD),
        'facility_telecommunication': (4, compositetrans.fieldtransformXTN),
        'contact_person': (5, compositetrans.fieldtransformXCN),
        'contact_title': (6, None),
        'contact_address': (7, compositetrans.fieldtransformXAD),
        'contact_telecommunication': (8, compositetrans.fieldtransformXTN),
        'signature_authority': (9, compositetrans.fieldtransformXCN),
        'signature_authority_title': (10, None),
        'signature_authority_address': (11, compositetrans.fieldtransformXAD),
        'signature_authority_telecommunication': (12, compositetrans.fieldtransformXTN),
},
    'URS': {\
        'ru_where_subject_definition': (1, None),
        'ru_when_data_start_datetime': (2, datetransform),
        'ru_when_data_end_datetime': (3, datetransform),
        'ru_what_user_qualifier': (4, None),
        'ru_other_results_subject_definition': (5, None),
        'ru_which_datetime_qualifier': (6, None),
        'ru_which_datetime_status_qualifier': (7, None),
        'ru_datetime_selection_qualifier': (8, None),
        'ru_quantitytiming_qualifier': (9, compositetrans.fieldtransformTQ),
},
    'PCH': {\
        'hospital': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'privilege': (3, None),
        'is_restricted': (4, None),
        'department': (5, None),
        'is_primary': (6, None),
        'appointment_date': (7, datetransform),
        'reappointment_date': (8, datetransform),
        'is_outside_service': (9, None),
        'address': (10, compositetrans.fieldtransformXAD),
        'phone': (11, compositetrans.fieldtransformXTN),
        'admitter': (12, compositetrans.fieldtransformXON),
        'specialty': (13, None),
        'comment': (14, None),
        'standing': (15, None),
        'revised_by': (16, compositetrans.fieldtransformPPN),
        'percent_admit': (17, None),
        'contact_person': (18, compositetrans.fieldtransformXPN),
},
    'GOL': {\
        'action_code': (1, None),
        'action_datetime': (2, datetransform),
        'goal_id': (3, compositetrans.fieldtransformCE),
        'goal_instance_id': (4, compositetrans.fieldtransformEI),
        'episode_of_care_id': (5, compositetrans.fieldtransformEI),
        'goal_list_priority': (6, numtransform),
        'goal_established_datetime': (7, datetransform),
        'expected_goal_achievement_datetime': (8, datetransform),
        'goal_classification': (9, compositetrans.fieldtransformCE),
        'goal_management_discipline': (10, compositetrans.fieldtransformCE),
        'current_goal_review_status': (11, compositetrans.fieldtransformCE),
        'current_goal_review_datetime': (12, datetransform),
        'next_goal_review_datetime': (13, datetransform),
        'previous_goal_review_datetime': (14, datetransform),
        'goal_review_interval': (15, compositetrans.fieldtransformTQ),
        'goal_evaluation': (16, compositetrans.fieldtransformCE),
        'goal_evaluation_comment': (17, None),
        'goal_life_cycle_status': (18, compositetrans.fieldtransformCE),
        'goal_life_cycle_status_datetime': (19, datetransform),
        'goal_target_type': (20, compositetrans.fieldtransformCE),
        'goal_target_name': (21, compositetrans.fieldtransformXPN),
},
    'LRL': {\
        'primary_key_value': (1, compositetrans.fieldtransformPL),
        'segment_action_code': (2, None),
        'segment_unique_key': (3, compositetrans.fieldtransformEI),
        'location_relationship_id': (4, compositetrans.fieldtransformCE),
        'organization_location_relationship_value': (5, compositetrans.fieldtransformXON),
        'patient_location_relationship_value': (6, compositetrans.fieldtransformPL),
},
    'IN2': {\
        'insureds_employee_id': (1, compositetrans.fieldtransformCX),
        'insureds_social_security_number': (2, None),
        'insureds_employer_name': (3, compositetrans.fieldtransformXCN),
        'employer_information_data': (4, None),
        'mail_claim_party': (5, None),
        'medicare_health_ins_card_number': (6, None),
        'medicaid_case_name': (7, compositetrans.fieldtransformXPN),
        'medicaid_case_number': (8, None),
        'champus_sponsor_name': (9, compositetrans.fieldtransformXPN),
        'champus_id_number': (10, None),
        'dependent_of_champus_recipient': (11, compositetrans.fieldtransformCE),
        'champus_organization': (12, None),
        'champus_station': (13, None),
        'champus_service': (14, None),
        'champus_rankgrade': (15, None),
        'champus_status': (16, None),
        'champus_retire_date': (17, datetransform),
        'champus_non_avail_cert_on_file': (18, None),
        'baby_coverage': (19, None),
        'combine_baby_bill': (20, None),
        'blood_deductible': (21, None),
        'special_coverage_approval_name': (22, compositetrans.fieldtransformXPN),
        'special_coverage_approval_title': (23, None),
        'non_covered_insurance_code': (24, None),
        'payor_id': (25, compositetrans.fieldtransformCX),
        'payor_subscriber_id': (26, compositetrans.fieldtransformCX),
        'eligibility_source': (27, None),
        'room_coverage_typeamount': (28, compositetrans.fieldtransformCM),
        'policy_typeamount': (29, compositetrans.fieldtransformCM),
        'daily_deductible': (30, compositetrans.fieldtransformCM),
        'living_dependency': (31, None),
        'ambulatory_status': (32, None),
        'citizenship': (33, None),
        'primary_language': (34, compositetrans.fieldtransformCE),
        'living_arrangement': (35, None),
        'publicity_indicator': (36, compositetrans.fieldtransformCE),
        'protection_indicator': (37, None),
        'student_indicator': (38, None),
        'religion': (39, None),
        'mothers_maiden_name': (40, compositetrans.fieldtransformXPN),
        'nationality': (41, compositetrans.fieldtransformCE),
        'ethnic_group': (42, None),
        'marital_status': (43, None),
        'insureds_employment_start_date': (44, datetransform),
        'insureds_employment_stop_date': (45, datetransform),
        'job_title': (46, None),
        'job_codeclass': (47, compositetrans.fieldtransformJCC),
        'job_status': (48, None),
        'employer_contact_person_name': (49, compositetrans.fieldtransformXPN),
        'employer_contact_person_phone_number': (50, compositetrans.fieldtransformXTN),
        'employer_contact_reason': (51, None),
        'insureds_contact_persons_name': (52, compositetrans.fieldtransformXPN),
        'insureds_contact_person_telephone_number': (53, compositetrans.fieldtransformXTN),
        'insureds_contact_person_reason': (54, None),
        'relationship_to_the_patient_start_date': (55, datetransform),
        'relationship_to_the_patient_stop_date': (56, datetransform),
        'insurance_co_contact_reason': (57, None),
        'insurance_co_contact_phone_number': (58, compositetrans.fieldtransformXTN),
        'policy_scope': (59, None),
        'policy_source': (60, None),
        'patient_member_number': (61, compositetrans.fieldtransformCX),
        'guarantors_relationship_to_insured': (62, None),
        'insureds_telephone_number_home': (63, compositetrans.fieldtransformXTN),
        'insureds_employer_telephone_number': (64, compositetrans.fieldtransformXTN),
        'military_handicapped_program': (65, compositetrans.fieldtransformCE),
        'suspend_flag': (66, None),
        'copay_limit_flag': (67, None),
        'stoploss_limit_flag': (68, None),
        'insured_organization_name_and_id': (69, compositetrans.fieldtransformXON),
        'insured_employer_organization_name_and_id': (70, compositetrans.fieldtransformXON),
        'race': (71, None),
        'hcfa_patient_relationship_to_insured': (72, compositetrans.fieldtransformCE),
},
    'BLG': {\
        'when_to_charge': (1, compositetrans.fieldtransformCM),
        'charge_type': (2, None),
        'account_id': (3, compositetrans.fieldtransformCK),
},
    'NSC': {\
        'network_change_type': (1, None),
        'current_cpu': (2, None),
        'current_fileserver': (3, None),
        'current_application': (4, None),
        'current_facility': (5, None),
        'new_cpu': (6, None),
        'new_fileserver': (7, None),
        'new_application': (8, None),
        'new_facility': (9, None),
},
    'EQL': {\
        'query_tag': (1, None),
        'queryresponse_format_code': (2, None),
        'eql_query_name': (3, compositetrans.fieldtransformCE),
        'eql_query_statement': (4, None),
},
    'NST': {\
        'statistics_available': (1, None),
        'source_identifier': (2, None),
        'source_type': (3, None),
        'statistics_start': (4, datetransform),
        'statistics_end': (5, datetransform),
        'receive_character_count': (6, numtransform),
        'send_character_count': (7, numtransform),
        'messages_received': (8, numtransform),
        'messages_sent': (9, numtransform),
        'checksum_errors_received': (10, numtransform),
        'length_errors_received': (11, numtransform),
        'other_errors_received': (12, numtransform),
        'connect_timeouts': (13, numtransform),
        'receive_timeouts': (14, numtransform),
        'network_errors': (15, numtransform),
},
    'SEC': {\
        'login': (1, compositetrans.fieldtransformPPN),
        'password': (2, None),
        'clientid': (3, compositetrans.fieldtransformXON),
        'accesslevel': (4, None),
        'revised_by': (5, compositetrans.fieldtransformPPN),
},
    'MFI': {\
        'master_file_identifier': (1, compositetrans.fieldtransformCE),
        'master_file_application_identifier': (2, compositetrans.fieldtransformHD),
        'file_level_event_code': (3, None),
        'entered_datetime': (4, datetransform),
        'effective_datetime': (5, datetransform),
        'response_level_code': (6, None),
},
    'LOC': {\
        'primary_key_value': (1, compositetrans.fieldtransformPL),
        'location_description': (2, None),
        'location_type': (3, None),
        'organization_name': (4, compositetrans.fieldtransformXON),
        'location_address': (5, compositetrans.fieldtransformXAD),
        'location_phone': (6, compositetrans.fieldtransformXTN),
        'license_number': (7, compositetrans.fieldtransformCE),
        'location_equipment': (8, None),
},
    'UB2': {\
        'set_id': (1, None),
        'co_insurance_days_9': (2, None),
        'condition_code_24_30': (3, None),
        'covered_days_7': (4, None),
        'non_covered_days_8': (5, None),
        'value_amount_code': (6, compositetrans.fieldtransformCM),
        'occurrence_code_date_32_35': (7, compositetrans.fieldtransformCM),
        'occurrence_span_codedates_36': (8, compositetrans.fieldtransformCM),
        'ub92_locator_2_state': (9, None),
        'ub92_locator_11_state': (10, None),
        'ub92_locator_31_national': (11, None),
        'document_control_number': (12, None),
        'ub92_locator_49_national': (13, None),
        'ub92_locator_56_state': (14, None),
        'ub92_locator_57_national': (15, None),
        'ub92_locator_78_state': (16, None),
        'special_visit_count': (17, numtransform),
},
    'RXD': {\
        'dispense_sub_id_counter': (1, numtransform),
        'dispensegive_code': (2, compositetrans.fieldtransformCE),
        'datetime_dispensed': (3, datetransform),
        'actual_dispense_amount': (4, numtransform),
        'actual_dispense_units': (5, compositetrans.fieldtransformCE),
        'actual_dosage_form': (6, compositetrans.fieldtransformCE),
        'prescription_number': (7, None),
        'number_of_refills_remaining': (8, numtransform),
        'dispense_notes': (9, None),
        'dispensing_provider': (10, compositetrans.fieldtransformXCN),
        'substitution_status': (11, None),
        'total_daily_dose': (12, compositetrans.fieldtransformCQ),
        'dispense_to_location': (13, compositetrans.fieldtransformCM),
        'needs_human_review': (14, None),
        'pharmacytreatment_supplier_special_dispensing_instructions': (15, compositetrans.fieldtransformCE),
        'actual_strength': (16, numtransform),
        'actual_strength_unit': (17, compositetrans.fieldtransformCE),
        'substance_lot_number': (18, None),
        'substance_expiration_date': (19, datetransform),
        'substance_manufacturer_name': (20, compositetrans.fieldtransformCE),
        'indication': (21, compositetrans.fieldtransformCE),
        'dispense_package_size': (22, numtransform),
        'dispense_package_size_unit': (23, compositetrans.fieldtransformCE),
        'dispense_package_method': (24, None),
},
    'APR': {\
        'time_selection_criteria': (1, compositetrans.fieldtransformSCV),
        'resource_selection_criteria': (2, compositetrans.fieldtransformSCV),
        'location_selection_criteria': (3, compositetrans.fieldtransformSCV),
        'slot_spacing_criteria': (4, compositetrans.fieldtransformSCV),
        'filler_override_criteria': (5, compositetrans.fieldtransformSCV),
},
    'RDT': {\
        'column_value': (1, None),
},
    'OM3': {\
        'sequence_number_test_observation_master_file': (1, numtransform),
        'preferred_coding_system': (2, compositetrans.fieldtransformCE),
        'valid_coded_answers': (3, compositetrans.fieldtransformCE),
        'normal_textcodes_for_categorical_observations': (4, compositetrans.fieldtransformCE),
        'abnormal_textcodes_for_categorical_observations': (5, compositetrans.fieldtransformCE),
        'critical_text_codes_for_categorical_observations': (6, compositetrans.fieldtransformCE),
        'value_type': (7, None),
},
    'SPR': {\
        'query_tag': (1, None),
        'query_response_format_code': (2, None),
        'stored_procedure_name': (3, compositetrans.fieldtransformCE),
        'input_parameter_list': (4, compositetrans.fieldtransformQIP),
},
    'OM1': {\
        'sequence_number_testobservation_master_file': (1, numtransform),
        'producers_testobservation_id': (2, compositetrans.fieldtransformCE),
        'permitted_data_types': (3, None),
        'specimen_required': (4, None),
        'producer_id': (5, compositetrans.fieldtransformCE),
        'observation_description': (6, None),
        'other_testobservation_ids_for_the_observation': (7, compositetrans.fieldtransformCE),
        'other_names': (8, None),
        'preferred_report_name_for_the_observation': (9, None),
        'preferred_short_name_or_mnemonic_for_observation': (10, None),
        'preferred_long_name_for_the_observation': (11, None),
        'orderability': (12, None),
        'identity_of_instrument_used_to_perfrom_this_study': (13, compositetrans.fieldtransformCE),
        'coded_representation_of_method': (14, compositetrans.fieldtransformCE),
        'portable': (15, None),
        'observation_producing_departmentsection': (16, compositetrans.fieldtransformCE),
        'telephone_number_of_section': (17, compositetrans.fieldtransformXTN),
        'nature_of_testobservation': (18, None),
        'report_subheader': (19, compositetrans.fieldtransformCE),
        'report_display_order': (20, None),
        'datetime_stamp_for_any_change_in_definition_for_the_observation': (21, datetransform),
        'effective_datetime_of_change_in_test_procedure_that_make_results_non_comparable': (22, datetransform),
        'typical_turn_around_time': (23, numtransform),
        'processing_time': (24, numtransform),
        'processing_priority': (25, None),
        'reporting_priority': (26, None),
        'outside_sites_where_observation_may_be_performed': (27, compositetrans.fieldtransformCE),
        'address_of_outside_sites': (28, compositetrans.fieldtransformXAD),
        'phone_number_of_outside_site': (29, compositetrans.fieldtransformXTN),
        'confidentiality_code': (30, None),
        'observations_required_to_interpret_the_observation': (31, compositetrans.fieldtransformCE),
        'interpretation_of_observations': (32, None),
        'contraindications_to_observations': (33, compositetrans.fieldtransformCE),
        'reflex_testsobservations': (34, compositetrans.fieldtransformCE),
        'rules_that_trigger_reflex_testing': (35, None),
        'fixed_canned_message': (36, compositetrans.fieldtransformCE),
        'patient_preparation': (37, None),
        'procedure_medication': (38, compositetrans.fieldtransformCE),
        'factors_that_may_effect_the_observation': (39, None),
        'testobservation_performance_schedule': (40, None),
        'description_of_test_methods': (41, None),
        'kind_of_quantity_observed': (42, compositetrans.fieldtransformCE),
        'point_versus_interval': (43, compositetrans.fieldtransformCE),
        'challenge_information': (44, None),
        'relationship_modifier': (45, compositetrans.fieldtransformCE),
        'target_anatomic_site_of_test': (46, compositetrans.fieldtransformCE),
        'modality_of_imaging_measurement': (47, compositetrans.fieldtransformCE),
},
    'LDP': {\
        'ldp_primary_key_value': (1, compositetrans.fieldtransformPL),
        'location_department': (2, None),
        'location_service': (3, None),
        'speciality_type': (4, compositetrans.fieldtransformCE),
        'valid_patient_classes': (5, None),
        'activeinactive_flag': (6, None),
        'activation_date': (7, datetransform),
        'inactivation_date': (8, datetransform),
        'inactivated_reason': (9, None),
        'visiting_hours': (10, compositetrans.fieldtransformVH),
        'contact_phone': (11, compositetrans.fieldtransformXTN),
},
    'PDC': {\
        'manufacturerdistributor': (1, compositetrans.fieldtransformXON),
        'country': (2, compositetrans.fieldtransformCE),
        'brand_name': (3, None),
        'device_family_name': (4, None),
        'generic_name': (5, compositetrans.fieldtransformCE),
        'model_identifier': (6, None),
        'catalogue_identifier': (7, None),
        'other_identifier': (8, None),
        'product_code': (9, compositetrans.fieldtransformCE),
        'marketing_basis': (10, None),
        'marketing_approval_identifier': (11, None),
        'labeled_shelf_life': (12, compositetrans.fieldtransformCQ),
        'expected_shelf_life': (13, compositetrans.fieldtransformCQ),
        'date_first_marketed': (14, datetransform),
        'date_last_marketed': (15, datetransform),
},
    'PCP': {\
        'pcp_subject': (1, compositetrans.fieldtransformXCN),
        'external_id': (2, compositetrans.fieldtransformCX),
        'description': (3, None),
        'stateregistration': (4, None),
        'pcplisted': (5, None),
        'address': (6, compositetrans.fieldtransformXAD),
        'phone': (7, compositetrans.fieldtransformXTN),
        'specialty': (8, None),
        'revised_by': (9, compositetrans.fieldtransformPPN),
        'comment': (10, None),
        'standing': (11, None),
},
    'RXO': {\
        'requested_give_code': (1, compositetrans.fieldtransformCE),
        'requested_give_amount_minimum': (2, numtransform),
        'requested_give_amount_maximum': (3, numtransform),
        'requested_give_units': (4, compositetrans.fieldtransformCE),
        'requested_dosage_form': (5, compositetrans.fieldtransformCE),
        'providers_pharmacytreatment_instructions': (6, compositetrans.fieldtransformCE),
        'providers_administration_instructions': (7, compositetrans.fieldtransformCE),
        'deliver_to_location': (8, compositetrans.fieldtransformCM),
        'allow_substitutions': (9, None),
        'requested_dispense_code': (10, compositetrans.fieldtransformCE),
        'requested_dispense_amount': (11, numtransform),
        'requested_dispense_units': (12, compositetrans.fieldtransformCE),
        'number_of_refills': (13, numtransform),
        'ordering_providers_dea_number': (14, compositetrans.fieldtransformXCN),
        'pharmacisttreatment_suppliers_verifier_id': (15, compositetrans.fieldtransformXCN),
        'needs_human_review': (16, None),
        'requested_give_per_time_unit': (17, None),
        'requested_give_strength': (18, numtransform),
        'requested_give_strength_units': (19, compositetrans.fieldtransformCE),
        'indication': (20, compositetrans.fieldtransformCE),
        'requested_give_rate_amount': (21, None),
        'requested_give_rate_units': (22, compositetrans.fieldtransformCE),
},
    'PRD': {\
        'role': (1, compositetrans.fieldtransformCE),
        'provider_name': (2, compositetrans.fieldtransformXPN),
        'provider_address': (3, compositetrans.fieldtransformXAD),
        'provider_location': (4, compositetrans.fieldtransformPL),
        'provider_communication_information': (5, compositetrans.fieldtransformXTN),
        'preferred_method_of_contact': (6, compositetrans.fieldtransformCE),
        'provider_identifiers': (7, compositetrans.fieldtransformCM),
        'effective_start_date_of_role': (8, datetransform),
        'effective_end_date_of_role': (9, datetransform),
},
    'ORC': {\
        'order_control': (1, None),
        'placer_order_number': (2, compositetrans.fieldtransformEI),
        'filler_order_number': (3, compositetrans.fieldtransformEI),
        'placer_group_number': (4, compositetrans.fieldtransformEI),
        'order_status': (5, None),
        'response_flag': (6, None),
        'quantitytiming': (7, compositetrans.fieldtransformTQ),
        'parent': (8, compositetrans.fieldtransformCM),
        'datetime_of_transaction': (9, datetransform),
        'entered_by': (10, compositetrans.fieldtransformXCN),
        'verified_by': (11, compositetrans.fieldtransformXCN),
        'ordering_provider': (12, compositetrans.fieldtransformXCN),
        'enterers_location': (13, compositetrans.fieldtransformPL),
        'call_back_phone_number': (14, compositetrans.fieldtransformXTN),
        'order_effective_datetime': (15, datetransform),
        'order_control_code_reason': (16, compositetrans.fieldtransformCE),
        'entering_organization': (17, compositetrans.fieldtransformCE),
        'entering_device': (18, compositetrans.fieldtransformCE),
        'action_by': (19, compositetrans.fieldtransformXCN),
},
    'AL1': {\
        'set_id': (1, None),
        'allergy_type': (2, None),
        'allergy_codemnemonic_description': (3, compositetrans.fieldtransformCE),
        'allergy_severity': (4, None),
        'allergy_reaction': (5, None),
        'identification_date': (6, datetransform),
},
    'FT1': {\
        'set_id': (1, None),
        'transaction_id': (2, None),
        'transaction_batch_id': (3, None),
        'transaction_date': (4, datetransform),
        'transaction_posting_date': (5, datetransform),
        'transaction_type': (6, None),
        'transaction_code': (7, compositetrans.fieldtransformCE),
        'transaction_description': (8, None),
        'transaction_description_alternative': (9, None),
        'transaction_quantity': (10, numtransform),
        'transaction_amount_extended': (11, compositetrans.fieldtransformCP),
        'transaction_amount_unit': (12, compositetrans.fieldtransformCP),
        'department_code': (13, compositetrans.fieldtransformCE),
        'insurance_plan_id': (14, compositetrans.fieldtransformCE),
        'insurance_amount': (15, compositetrans.fieldtransformCP),
        'assigned_patient_location': (16, compositetrans.fieldtransformPL),
        'fee_schedule': (17, None),
        'patient_type': (18, None),
        'diagnosis_code': (19, compositetrans.fieldtransformCE),
        'performed_by_code': (20, compositetrans.fieldtransformXCN),
        'ordered_by_code': (21, compositetrans.fieldtransformXCN),
        'unit_cost': (22, compositetrans.fieldtransformCP),
        'filler_order_number': (23, compositetrans.fieldtransformEI),
        'entered_by_code': (24, compositetrans.fieldtransformXCN),
        'procedure_code': (25, compositetrans.fieldtransformCE),
},
    'ROL': {\
        'role_instance_id': (1, compositetrans.fieldtransformEI),
        'action_code': (2, None),
        'role': (3, compositetrans.fieldtransformCE),
        'role_person': (4, compositetrans.fieldtransformXCN),
        'role_begin_datetime': (5, datetransform),
        'role_end_datetime': (6, datetransform),
        'role_duration': (7, compositetrans.fieldtransformCE),
        'role_action_reason': (8, compositetrans.fieldtransformCE),
},
    'NK1': {\
        'set_id': (1, None),
        'name': (2, compositetrans.fieldtransformXPN),
        'relationship': (3, compositetrans.fieldtransformCE),
        'address': (4, compositetrans.fieldtransformXAD),
        'phone_number': (5, compositetrans.fieldtransformXTN),
        'business_phone_number': (6, compositetrans.fieldtransformXTN),
        'contact_role': (7, compositetrans.fieldtransformCE),
        'start_date': (8, datetransform),
        'end_date': (9, datetransform),
        'next_of_kinassociated_parties_job_title': (10, None),
        'next_of_kinassociated_parties_job_codeclass': (11, compositetrans.fieldtransformJCC),
        'next_of_kinassociated_parties_employee_number': (12, compositetrans.fieldtransformCX),
        'organization_name': (13, compositetrans.fieldtransformXON),
        'marital_status': (14, None),
        'sex': (15, None),
        'datetime_of_birth': (16, datetransform),
        'living_dependency': (17, None),
        'ambulatory_status': (18, None),
        'citizenship': (19, None),
        'primary_language': (20, compositetrans.fieldtransformCE),
        'living_arrangement': (21, None),
        'publicity_indicator': (22, compositetrans.fieldtransformCE),
        'protection_indicator': (23, None),
        'student_indicator': (24, None),
        'religion': (25, None),
        'mothers_maiden_name': (26, compositetrans.fieldtransformXPN),
        'nationality': (27, compositetrans.fieldtransformCE),
        'ethnic_group': (28, None),
        'contact_reason': (29, compositetrans.fieldtransformCE),
        'contact_persons_name': (30, compositetrans.fieldtransformXPN),
        'contact_persons_telephone_number': (31, compositetrans.fieldtransformXTN),
        'contact_persons_address': (32, compositetrans.fieldtransformXAD),
        'next_of_kinassociated_partys_identifiers': (33, compositetrans.fieldtransformCX),
        'job_status': (34, None),
        'race': (35, None),
        'handicap': (36, None),
        'contact_person_social_security_number': (37, None),
},
    'DG1': {\
        'set_id': (1, None),
        'diagnosis_coding_method': (2, None),
        'diagnosis_code': (3, compositetrans.fieldtransformCE),
        'diagnosis_description': (4, None),
        'diagnosis_datetime': (5, datetransform),
        'diagnosis_type': (6, None),
        'major_diagnostic_category': (7, compositetrans.fieldtransformCE),
        'diagnostic_related_group': (8, compositetrans.fieldtransformCE),
        'drg_approval_indicator': (9, None),
        'drg_grouper_review_code': (10, None),
        'outlier_type': (11, compositetrans.fieldtransformCE),
        'outlier_days': (12, numtransform),
        'outlier_cost': (13, compositetrans.fieldtransformCP),
        'grouper_version_and_type': (14, None),
        'diagnosis_priority': (15, numtransform),
        'diagnosing_clinician': (16, compositetrans.fieldtransformXCN),
        'diagnosis_classification': (17, None),
        'confidential_indicator': (18, None),
        'attestation_datetime': (19, datetransform),
},
    'ERR': {\
        'error_code_and_location': (1, compositetrans.fieldtransformCM),
},
    'ODS': {\
        'type': (1, None),
        'service_period': (2, compositetrans.fieldtransformCE),
        'diet_supplement_or_preference_code': (3, compositetrans.fieldtransformCE),
        'text_instruction': (4, None),
},
    'PD1': {\
        'living_dependency': (1, None),
        'living_arrangement': (2, None),
        'patient_primary_facility': (3, compositetrans.fieldtransformXON),
        'patient_primary_care_provider_name_id_no': (4, compositetrans.fieldtransformXCN),
        'student_indicator': (5, None),
        'handicap': (6, None),
        'living_will': (7, None),
        'organ_donor': (8, None),
        'separate_bill': (9, None),
        'duplicate_patient': (10, compositetrans.fieldtransformCX),
        'publicity_indicator': (11, compositetrans.fieldtransformCE),
        'protection_indicator': (12, None),
},
    'RXR': {\
        'route': (1, compositetrans.fieldtransformCE),
        'site': (2, compositetrans.fieldtransformCE),
        'administration_device': (3, compositetrans.fieldtransformCE),
        'administration_method': (4, compositetrans.fieldtransformCE),
},
    'OM2': {\
        'sequence_number_test_observation_master_file': (1, numtransform),
        'units_of_measure': (2, compositetrans.fieldtransformCE),
        'range_of_decimal_precision': (3, numtransform),
        'corresponding_si_units_of_measure': (4, compositetrans.fieldtransformCE),
        'si_conversion_factor': (5, None),
        'reference_normal_range_ordinal_continuous_observation': (6, compositetrans.fieldtransformCM),
        'critical_range_for_ordinal_continuous_observation': (7, compositetrans.fieldtransformCM),
        'absolute_range_for_ordinal_continuous_observation': (8, compositetrans.fieldtransformCM),
        'delta_check_criteria': (9, compositetrans.fieldtransformCM),
        'minimum_meaningful_increments': (10, numtransform),
},
    'CTI': {\
        'sponsor_study_id': (1, compositetrans.fieldtransformEI),
        'study_phase_identifier': (2, compositetrans.fieldtransformCE),
        'study_scheduled_time_point': (3, compositetrans.fieldtransformCE),
},
    'PRB': {\
        'action_code': (1, None),
        'action_datetime': (2, datetransform),
        'problem_id': (3, compositetrans.fieldtransformCE),
        'problem_instance_id': (4, compositetrans.fieldtransformEI),
        'episode_of_care_id': (5, compositetrans.fieldtransformEI),
        'problem_list_priority': (6, numtransform),
        'datetime_problem_established': (7, datetransform),
        'anticipated_problem_resolution_datetime': (8, datetransform),
        'actual_problem_resolution_datetime': (9, datetransform),
        'problem_classification': (10, compositetrans.fieldtransformCE),
        'problem_management_discipline': (11, compositetrans.fieldtransformCE),
        'problem_persistence': (12, compositetrans.fieldtransformCE),
        'problem_confirmation_status': (13, compositetrans.fieldtransformCE),
        'problem_life_cycle_status': (14, compositetrans.fieldtransformCE),
        'problem_life_cycle_status_datetime': (15, datetransform),
        'problem_date_of_onset': (16, datetransform),
        'problem_onset_text': (17, None),
        'problem_ranking': (18, compositetrans.fieldtransformCE),
        'certainty_of_problem': (19, compositetrans.fieldtransformCE),
        'probability_of_problem_0_1': (20, numtransform),
        'individual_awareness_of_problem': (21, compositetrans.fieldtransformCE),
        'problem_prognosis': (22, compositetrans.fieldtransformCE),
        'individual_awareness_of_prognosis': (23, compositetrans.fieldtransformCE),
        'familysignificant_other_awareness_of_problemprognosis': (24, None),
        'securitysensitivity': (25, compositetrans.fieldtransformCE),
},
    'CM1': {\
        'set_id': (1, None),
        'study_phase_identifier': (2, compositetrans.fieldtransformCE),
        'description_of_study_phase': (3, None),
},
    'CSP': {\
        'study_phase_identifier': (1, compositetrans.fieldtransformCE),
        'datetime_study_phase_began': (2, datetransform),
        'datetime_study_phase_ended': (3, datetransform),
        'study_phase_evaluability': (4, compositetrans.fieldtransformCE),
},
    'QRD': {\
        'query_datetime': (1, datetransform),
        'query_format_code': (2, None),
        'query_priority': (3, None),
        'query_id': (4, None),
        'deferred_response_type': (5, None),
        'deferred_response_datetime': (6, datetransform),
        'quantity_limited_request': (7, compositetrans.fieldtransformCQ),
        'who_subject_filter': (8, compositetrans.fieldtransformXCN),
        'what_subject_filter': (9, compositetrans.fieldtransformCE),
        'what_department_data_code': (10, compositetrans.fieldtransformCE),
        'what_data_code_value_qual': (11, compositetrans.fieldtransformCM),
        'query_results_level': (12, None),
},
    'TXA': {\
        'set_id_txa': (1, None),
        'document_type': (2, None),
        'document_content_presentation': (3, None),
        'activity_datetime': (4, datetransform),
        'primary_activity_provider_codename': (5, compositetrans.fieldtransformXCN),
        'origination_datetime': (6, datetransform),
        'transcription_datetime': (7, datetransform),
        'edit_datetime': (8, datetransform),
        'originator_codename': (9, compositetrans.fieldtransformXCN),
        'assigned_document_authenticator': (10, compositetrans.fieldtransformXCN),
        'transcriptionist_codename': (11, compositetrans.fieldtransformXCN),
        'unique_document_number': (12, compositetrans.fieldtransformEI),
        'parent_document_number': (13, compositetrans.fieldtransformEI),
        'placer_order_number': (14, compositetrans.fieldtransformEI),
        'filler_order_number': (15, compositetrans.fieldtransformEI),
        'unique_document_file_name': (16, None),
        'document_completion_status': (17, None),
        'document_confidentiality_status': (18, None),
        'document_availability_status': (19, None),
        'document_storage_status': (20, None),
        'document_change_reason': (21, None),
        'authentication_person_time_stamp': (22, compositetrans.fieldtransformPPN),
        'distributed_copies_code_and_name_of_recipients': (23, compositetrans.fieldtransformXCN),
},
    'PCI': {\
        'provider_id_internal': (1, compositetrans.fieldtransformXCN),
        'id': (2, compositetrans.fieldtransformCX),
        'classification_id': (3, None),
        'ssn': (4, None),
        'tax_id': (5, None),
        'date_of_birth': (6, datetransform),
        'is_usa_citizen': (7, None),
        'alien_number': (8, None),
        'birth_country_id': (9, None),
        'birth_city': (10, None),
        'birth_state_id': (11, None),
        'gender': (12, None),
        'original_state_id': (13, None),
        'original_year': (14, datetransform),
        'maiden_name': (15, compositetrans.fieldtransformXPN),
        'comment': (16, None),
        'standing_id': (17, None),
        'practicing_specialties': (18, None),
        'languages': (19, None),
        'provider_type': (20, None),
        'line_of_business': (21, None),
        'revised_by': (22, compositetrans.fieldtransformPPN),
},
    'LCI': {\
        'location_id_internal': (1, compositetrans.fieldtransformXON),
        'external_id': (2, compositetrans.fieldtransformCX),
        'address': (3, compositetrans.fieldtransformXAD),
        'phone': (4, compositetrans.fieldtransformXTN),
        'comment': (5, None),
        'standing_id': (6, None),
        'revised_by': (7, compositetrans.fieldtransformPPN),
},
    'LCH': {\
        'primary_key_value': (1, compositetrans.fieldtransformPL),
        'segment_action_code': (2, None),
        'segment_unique_key': (3, compositetrans.fieldtransformEI),
        'location_characteristic_id': (4, compositetrans.fieldtransformCE),
        'location_characteristic_value': (5, compositetrans.fieldtransformCE),
},
    'PCW': {\
        'organization': (1, compositetrans.fieldtransformXON),
        'organization_id': (2, compositetrans.fieldtransformCX),
        'position': (3, None),
        'dates': (4, compositetrans.fieldtransformDR),
        'practicing': (5, None),
        'address': (6, compositetrans.fieldtransformXAD),
        'phone': (7, compositetrans.fieldtransformXTN),
        'revised_by': (8, compositetrans.fieldtransformPPN),
        'comment': (9, None),
        'standing': (10, None),
},
    'ADD': {\
        'addendum_continuation_pointer': (1, None),
},
    'IN1': {\
        'set_id': (1, None),
        'insurance_plan_id': (2, compositetrans.fieldtransformCE),
        'insurance_company_id': (3, compositetrans.fieldtransformCX),
        'insurance_company_name': (4, compositetrans.fieldtransformXON),
        'insurance_company_address': (5, compositetrans.fieldtransformXAD),
        'insurance_co_contact_person': (6, compositetrans.fieldtransformXPN),
        'insurance_co_phone_number': (7, compositetrans.fieldtransformXTN),
        'group_number': (8, None),
        'group_name': (9, compositetrans.fieldtransformXON),
        'insureds_group_emp_id': (10, compositetrans.fieldtransformCX),
        'insureds_group_emp_name': (11, compositetrans.fieldtransformXON),
        'plan_effective_date': (12, datetransform),
        'plan_expiration_date': (13, datetransform),
        'authorization_information': (14, compositetrans.fieldtransformCM),
        'plan_type': (15, None),
        'name_of_insured': (16, compositetrans.fieldtransformXPN),
        'insureds_relationship_to_patient': (17, None),
        'insureds_date_of_birth': (18, datetransform),
        'insureds_address': (19, compositetrans.fieldtransformXAD),
        'assignment_of_benefits': (20, None),
        'coordination_of_benefits': (21, None),
        'coordination_of_benefits_priority': (22, None),
        'notice_of_admission_flag': (23, None),
        'notice_of_admission_date': (24, datetransform),
        'rpt_of_eligibility_flag': (25, None),
        'rpt_of_eligibility_date': (26, datetransform),
        'release_information_code': (27, None),
        'pre_admit_cert_pac': (28, None),
        'verification_datetime': (29, datetransform),
        'verification_by': (30, compositetrans.fieldtransformXCN),
        'type_of_agreement_code': (31, None),
        'billing_status': (32, None),
        'lifetime_reserve_days': (33, numtransform),
        'delay_before_l_r_day': (34, numtransform),
        'company_plan_code': (35, None),
        'policy_number': (36, None),
        'policy_deductible': (37, compositetrans.fieldtransformCP),
        'policy_limit_amount': (38, compositetrans.fieldtransformCP),
        'policy_limit_days': (39, numtransform),
        'room_rate_semi_private': (40, compositetrans.fieldtransformCP),
        'room_rate_private': (41, compositetrans.fieldtransformCP),
        'insureds_employment_status': (42, compositetrans.fieldtransformCE),
        'insureds_sex': (43, None),
        'insureds_employer_address': (44, compositetrans.fieldtransformXAD),
        'verification_status': (45, None),
        'prior_insurance_plan_id': (46, None),
        'coverage_type': (47, None),
        'handicap': (48, None),
        'insureds_id_number': (49, compositetrans.fieldtransformCX),
},
    'PCE': {\
        'position_id': (1, compositetrans.fieldtransformCX),
        'exceptiontype': (2, None),
        'value': (3, None),
        'sourceid': (4, None),
        'recommendation': (5, None),
        'revised_by': (6, compositetrans.fieldtransformPPN),
},
    'MSA': {\
        'acknowledgement_code': (1, None),
        'message_control_id': (2, None),
        'text_message': (3, None),
        'expected_sequence_number': (4, numtransform),
        'delayed_acknowledgement_type': (5, None),
        'error_condition': (6, compositetrans.fieldtransformCE),
},
    'PTH': {\
        'action_code': (1, None),
        'pathway_id': (2, compositetrans.fieldtransformCE),
        'pathway_instance_id': (3, compositetrans.fieldtransformEI),
        'pathway_established_datetime': (4, datetransform),
        'pathway_lifecycle_status': (5, compositetrans.fieldtransformCE),
        'change_pathway_lifecycle_status_datetime': (6, datetransform),
},
    'AUT': {\
        'authorizing_payor_plan_id': (1, compositetrans.fieldtransformCE),
        'authorizing_payor_company_id': (2, compositetrans.fieldtransformCE),
        'authorizing_payor_company_name': (3, None),
        'authorization_effective_date': (4, datetransform),
        'authorization_expiration_date': (5, datetransform),
        'authorization_identifier': (6, compositetrans.fieldtransformEI),
        'reimbursement_limit': (7, compositetrans.fieldtransformCP),
        'requested_number_of_treatments': (8, numtransform),
        'authorized_number_of_treatments': (9, numtransform),
        'process_date': (10, datetransform),
},
}
